[prometheus-adapter] Allow specifying service account annotations
prometheus-community/helm-charts pull request #1029
Opened 2021-06-01 06:29 UTC by chrissng

#### What this PR does / why we need it:

Allow specifying annotations in the K8s service account for e.g. to use AWS EKS IAM roles for service accounts

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - NA

#### Special notes for your reviewer:

Nil

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-06-05 13:10 UTC, monotek requested changes

2021-06-05 13:10 UTC, monotek commented on charts/prometheus-adapter/Chart.yaml
> +version: 2.13.1
new feature should raise minor version

2021-06-07 03:09 UTC, chrissng commented on charts/prometheus-adapter/Chart.yaml
> +version: 2.13.1
Fixed

2021-06-07 14:22 UTC, steven-sheehy approved these changes
LGTM

2021-06-07 23:37 UTC, merged