[prometheus-pushgateway] add extraVolumes and extraVolumeMounts to chart
prometheus-community/helm-charts pull request #1059
Opened 2021-06-10 07:16 UTC by DilasserT

Signed-off-by: DilasserT <dilassert@gmail.com>

#### What this PR does / why we need it:
Allow additionnal volumes to be added, can be used to add shared volumes

Also added emptyDir in case `persistentVolume.enabled: false`, as it is specified in `values.yaml`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-06-15 07:01 UTC, monotek submitted a review, later dismissed

2021-07-06 19:16 UTC, monotek requested changes
Please merge main into your branch to get the "node not ready" problem in ci fixed.
See: https://github.com/prometheus-community/helm-charts/pull/1140

2021-07-15 09:08 UTC, DilasserT commented
Is there something else I should do ?

2021-07-18 11:31 UTC, monotek approved these changes

2021-08-04 11:18 UTC, DilasserT commented
@monotek Do you believe this PR could be reviewed/merged before september ?

2021-08-10 06:48 UTC, monotek commented
@prometheus-community/helm-charts-admins please review :)

2021-09-10 12:39 UTC, DilasserT commented
Still hoping to have this feature

2021-09-13 02:32 UTC, zanhsieh approved these changes

2021-09-14 13:54 UTC, torstenwalter approved these changes

2021-09-14 13:55 UTC, merged