[kube-prometheus-stack] Add Extra Support for Amazon EKS KubeVersion on Ingress
prometheus-community/helm-charts pull request #1060
Opened 2021-06-10 13:00 UTC by Kirchen99

Signed-off-by: Kirchen99 <latias_latios@126.com>

#### What this PR does / why we need it:

This PR adds support when this Chart is deployed on an Amazon EKS Cluster. 

The Kube-Version of an EKS Cluster is like a pre-release version e.g. `v1.20.4-eks-6b7464`, which makes helm confused thus rendered wrong apiVersion for resources like ingress of Alertmanager and Prometheus.

This PR, for example, replaces `v1.20.4-eks-6b7464` with `1.20.4`, if there is an `eks` in it.

#### Which issue this PR fixes
  - fixes #1057

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-06-15 09:35 UTC, monotek commented
Why is this needed?
Does kubeVersionOverride not work for you?

2021-06-15 10:36 UTC, stevehipwell commented
I missed this PR when I opened issue https://github.com/prometheus-community/helm-charts/issues/1071 but I'm in agreement that this is needed.

Are there any other managed K8s distros that also misuse the `KubeVersion` field that should also be included in this?

2021-06-15 10:38 UTC, stevehipwell commented
@monotek `kubeVersionOverride` works but firstly you need to know to use it and secondly it's a static value that would need to be maintained over a cluster lifetime and could cause issues if not updated correctly. This fix is a significant improvement to the UX for this chart.

2021-06-15 11:37 UTC, z0rc commented
Actually it isn't EKS specific, other providers like GKE and microk8s do something similar with server version. Check out https://github.com/vmware-tanzu/sonobuoy/pull/1228 to see how other projects deal provider build strings.

2021-06-15 13:06 UTC, Kirchen99 commented
> Why is this needed?
> Does kubeVersionOverride not work for you?

`kubeVersionOverride` works functional but we want better user experience.

2021-06-15 13:27 UTC, Xtigyro requested changes
Thank you for the contribution, @Kirchen99! 🥇 

Could you please resolve the merge conflicts?

2021-06-15 13:27 UTC, Xtigyro commented
@Kirchen99 Also - please bump the minor version of the chart (not the patch version).

2021-06-15 13:51 UTC, z0rc requested changes

2021-06-15 13:51 UTC, z0rc commented on charts/kube-prometheus-stack/templates/_helpers.tpl
> +  {{/* Special use case for Aamzon EKS */}}
`Aamzon`

2021-06-15 14:25 UTC, Xtigyro commented on charts/kube-prometheus-stack/templates/_helpers.tpl
> +  {{/* Special use case for Aamzon EKS */}}
@Kirchen99 This one too.

2021-06-15 14:39 UTC, stevehipwell commented
@z0rc it's a shame Helm doesn't have lookahead assertions (negative) so we could implement a catch all for non SemVer pre-releases (e.g. keep `alpha`, `beta`, `rc` and trim others). I was thinking an option would be to check for the `.x` pre-release version but I don't know how consistently this is used in practice so I think what we've got here looks to be the best solution.

2021-06-15 15:04 UTC, z0rc commented
@stevehipwell @Kirchen99 At least maybe proposed regex can be improved to handle more cases (GKE, microk8s, see test cases from linked sonobuoy PR), instead of being EKS specific?

2021-06-15 15:17 UTC, stevehipwell commented
@z0rc that'd make sense if the regex patterns would be compatible (e.g. `$\\d+\\.\\d+\\.\\d+-(?:eks|gke).+$`).

2021-06-16 08:37 UTC, closed without merging

2021-06-16 08:48 UTC, Kirchen99 commented
This one is closed since I have tried to resolve the conflicts by git rebase. But it brings more problems(DCO) to solve. So I open a new pull request https://github.com/prometheus-community/helm-charts/pull/1083.