Add documentation on how to configure additionalPrometheusRulesMap
prometheus-community/helm-charts pull request #109
Opened 2020-09-17 09:34 UTC by omegas27

#### What this PR does / why we need it:

Add documentation to use additionalPrometheusRulesMap as finding the correct format is not straightforward

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-09-18 07:05 UTC, gkarthiks reviewed
lgtm, lets wait for one more reviewer

2020-09-19 14:55 UTC, scottrigby requested changes

2020-09-19 14:55 UTC, scottrigby commented on charts/kube-prometheus-stack/values.yaml
> +## Deprecated way to provide custom recording or alerting rules to be deployed into the cluster.
May be good to add:
> Instead use "additionalPrometheusRulesMap" below.

2020-09-21 09:12 UTC, omegas27 commented on charts/kube-prometheus-stack/values.yaml
> +## Deprecated way to provide custom recording or alerting rules to be deployed into the cluster.
Thanks for the input :D

2020-09-21 19:50 UTC, scottrigby approved these changes

2020-09-21 19:55 UTC, merged