[kube-prometheus-stack] Remove app label on ruleSelector
prometheus-community/helm-charts pull request #1113
Opened 2021-06-27 14:25 UTC by nlamirault

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-06-29 13:31 UTC, monotek reviewed
Could you please add explanation why its removed and why the you've raised the minor version?

2021-06-29 14:44 UTC, nlamirault commented
@monotek Sorry i think i forget to save my previous comment :(
Due to matchLabels change i update the minor version. Should a patch be better?

2021-07-18 11:23 UTC, monotek requested changes
Yes, if its a bugfix and no new features added, thje patch version should be raised.

2021-09-14 04:53 UTC, gkarthiks commented
> Could you please add explanation why its removed and why the you've raised the minor version?

hi @nlamirault as requested by @monotek, can you please add an explanation for why its being removed clearly?

2021-09-21 14:57 UTC, monotek approved these changes

2021-11-12 17:35 UTC, nlamirault commented
> > Could you please add explanation why its removed and why the you've raised the minor version?
> 
> hi @nlamirault as requested by @monotek, can you please add an explanation for why its being removed clearly?

@gkarthiks it's just to make all selectors work the same

2021-12-14 16:29 UTC, gkarthiks approved these changes

2021-12-14 16:29 UTC, merged

2021-12-14 16:37 UTC, mrueg commented on charts/kube-prometheus-stack/Chart.yaml
> +appVersion: 0.52.0
You downgraded the prometheus operator version here.

@nlamirault @gkarthiks