[prometheus-elasticsearch-exporter] Update Docker image to prometheus-community
prometheus-community/helm-charts pull request #1130
Opened 2021-07-02 09:59 UTC by hierynomus

#### What this PR does / why we need it:
The Docker image (and documentation) were still pointing to the `justwatch` repository. As work has been migrated to the prometheus-community, these links needed updating and the newly released version is now added to the Helm chart.

#### Which issue this PR fixes
n/a

#### Special notes for your reviewer:
n/a

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-07-02 10:10 UTC, vpartington requested changes

2021-07-02 10:10 UTC, vpartington commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +  tag: 1.2.1
The latest tag is `v1.2.1`, with a `v`.

2021-07-02 10:10 UTC, vpartington commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +  repository: quay.io/prometheuscommunity/elasticsearch-exporter
The image name is `prometheuscommunity/elasticsearch-exporter`.

2021-07-02 10:52 UTC, hierynomus commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +  tag: 1.2.1
Thanks, fixed that!

2021-07-06 19:16 UTC, monotek requested changes
Please merge main into your branch to get the "node not ready" problem in ci fixed.
See: https://github.com/prometheus-community/helm-charts/pull/1140

2021-08-11 09:48 UTC, hierynomus commented
Superseeded by #1126

2021-08-11 09:48 UTC, closed without merging