[prometheus-adapter] add pod securityContext
prometheus-community/helm-charts pull request #1136
Opened 2021-07-05 15:04 UTC by TheKangaroo

#### What this PR does / why we need it:
with k8s 1.21, we need to set fsGroup for all non-root pods to allow
access to the api token (via projected api).
ref: https://github.com/kubernetes/kubernetes/issues/70679

#### Which issue this PR fixes
  - fixes 1135

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-07-06 09:45 UTC, TheKangaroo commented
I'm not sure, why the linting failed. In the logs you can see node not-ready.
Is there something I can do?

2021-07-06 14:41 UTC, steven-sheehy submitted a review, later dismissed
LGTM. Weird that this change was needed since the referenced ticket had the text `Pods running as non root need an fsGroup or they will not have permission to read the token` in strikethrough as if it was not actually implemented.

2021-07-06 19:06 UTC, monotek requested changes
Please merge master into your branch to get the "node not ready" problem in ci fixed.

2021-07-12 15:21 UTC, TheKangaroo commented
rebases. sorry for the delay.

2021-07-12 16:14 UTC, steven-sheehy approved these changes

2021-07-18 11:31 UTC, monotek approved these changes

2021-07-18 11:31 UTC, merged

2021-07-21 17:09 UTC, tunguyen9889 commented
Hi @monotek, @steven-sheehy, @TheKangaroo, could you please help check, the latest version `2.15.1` was not uploaded to Chart repo yet:

```
➜  ~ helm search repo prometheus-adapter
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
prometheus-community/prometheus-adapter 2.15.0          v0.8.4          A Helm chart for k8s prometheus adapter
```

2021-07-21 18:28 UTC, monotek commented
It's there: https://github.com/prometheus-community/helm-charts/releases/tag/prometheus-adapter-2.15.1
But it's missing in the index.yaml: https://raw.githubusercontent.com/prometheus-community/helm-charts/gh-pages/index.yaml
Triggering the job again did not help: https://github.com/prometheus-community/helm-charts/runs/3127007145

So maybe we have to create a new bugfix version....

2021-07-21 18:47 UTC, monotek commented
https://github.com/prometheus-community/helm-charts/pull/1195