[kube-prometheus-stack] Update dependencies and dashboard
prometheus-community/helm-charts pull request #1179
Opened 2021-07-19 15:33 UTC by mrueg

#### What this PR does / why we need it:
Updates grafana, node-exporter dependencies as well as syncs dashboards

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-07-19 15:33 UTC, mrueg commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 16.14.2
node_exporter major bump is mainly about helm2 compatibility which this chart is unaffected by, thus not raising minor here.

2021-07-19 16:10 UTC, Xtigyro submitted a review, later dismissed
Thanks for the contribution, @mrueg! 🥇 

LGTM.

2021-07-19 20:34 UTC, Xtigyro reviewed
@mrueg It appears the chart cannot be installed properly.

2021-07-19 20:59 UTC, mrueg commented
> @mrueg It appears the chart cannot be installed properly.

Yes I'm looking into it. It could be related to https://github.com/prometheus-community/helm-charts/pull/1181

2021-07-20 10:16 UTC, mrueg commented
@Xtigyro this was broken by a change in grafana and got fixed through https://github.com/grafana/helm-charts/pull/575

2021-07-20 11:06 UTC, Xtigyro requested changes
Prometheus minor version is bumped. Please let's do so with the chart version.

2021-07-20 12:23 UTC, mrueg commented
> Prometheus minor version is bumped. Please let's do so with the chart version.

Done!

2021-07-20 12:28 UTC, Xtigyro approved these changes

2021-07-20 12:28 UTC, merged