[prometheus-elasticsearch-exporter] add optional annotations to deployment
prometheus-community/helm-charts pull request #1224
Opened 2021-07-30 18:29 UTC by jdgeisler

Signed-off-by: Geisler, James D <geislerjamesd@gmail.com>

#### What this PR does / why we need it:
This provides the ability to add arbitrary annotations to the prometheus-elasticsearch-exporter deployment. This will enable the use of any operators that rely on deployment annotations.

Example values.yaml:
```yaml
deployment:
  annotations:
    wave.pusher.com/update-on-config-change: "true"
```

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-08-04 06:41 UTC, monotek requested changes

2021-08-04 06:41 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.5.1
new feature should raise minor version.

2021-08-10 13:43 UTC, monotek approved these changes

2021-08-23 20:43 UTC, jdgeisler commented
@monotek thanks for the approval! Is this ready to be merged in?

2021-09-02 12:52 UTC, desaintmartin approved these changes
Thanks!

2021-09-02 12:53 UTC, merged