[prometheus-pushgateway] Updated push gateway version and ingress to stable
prometheus-community/helm-charts pull request #1238
Opened 2021-08-09 21:09 UTC by alecrajeev

#### What this PR does / why we need it:
Updates push gateway to latest version (1.4.1). Also updates ingress to use the stable release for newer versions of kubernets.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-08-09 21:10 UTC, alecrajeev commented
I think there is an older PR related to this, but this also updates ingress. I can merge main branch into his as well as needed.

2021-08-10 12:46 UTC, monotek requested changes

2021-08-10 12:46 UTC, monotek commented on charts/prometheus-pushgateway/templates/ingress.yaml
> +apiVersion: networking.k8s.io
```suggestion
apiVersion: networking.k8s.io/v1
```

2021-08-10 17:28 UTC, alecrajeev commented on charts/prometheus-pushgateway/templates/ingress.yaml
> +apiVersion: networking.k8s.io
Good catch! thanks!

2021-08-13 13:10 UTC, monotek submitted a review, later dismissed

2021-08-31 17:57 UTC, asherf commented
ping @gianrubio , can we get this merged?

2021-09-01 00:06 UTC, closed without merging

2021-09-01 00:34 UTC, alecrajeev commented
Apologies I rebased this incorrectly. Created a new PR here: https://github.com/prometheus-community/helm-charts/pull/1306