[prometheus] Add VPA support for pushgateway
prometheus-community/helm-charts pull request #1277
Opened 2021-08-23 04:07 UTC by tuananhnguyen-ct

Signed-off-by: Tuan Anh Nguyen <tuananh.nguyen-ext@commercetools.de>

#### What this PR does / why we need it:
This will add support for enabling/configuring vertical pod autoscaler for pushgateway component in prometheus chart.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-08-23 13:01 UTC, zanhsieh approved these changes

2021-08-27 09:46 UTC, zanhsieh submitted a review, later dismissed

2021-08-31 03:22 UTC, tuananhnguyen-ct commented
@monotek can you take another look please?

2021-09-20 14:02 UTC, monotek requested changes
Please update version to 14..8.0

2021-09-27 14:52 UTC, monotek approved these changes

2021-09-27 16:14 UTC, merged