[kube-prometheus-stack] Update prometheus-operator to 0.42.1
prometheus-community/helm-charts pull request #128
Opened 2020-09-22 14:02 UTC by bashofmann

#### What this PR does / why we need it:
Update prometheus-operator to 0.42.1.

This also introduces a new `Probes` CRD. Since Helm does not create this new CRD on a chart upgrade automatically, the chart version is bumped to 10 to indicate the breaking change.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-09-24 10:28 UTC, cablespaghetti commented
Would love for this to get merged. I've done this by hand by bumping image versions and deploying the CRDs by hand but the lack of "probes" in the ClusterRole makes things difficult.

2020-09-25 12:46 UTC, tiagomeireles commented
This also bumps the kubernetes prerequisite to 1.16+. prometheus-operator 0.39 introduced a requirement for kubernetes v1.16 or newer. https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.39.0

I'm +1 with getting this merged in.

2020-09-25 13:18 UTC, bashofmann commented
What do you think, should I add a `kubeVersion` field in the Chart.yaml to restrict this?

2020-09-27 10:57 UTC, bashofmann commented
`kubeVersion` requirement is added.

2020-09-27 12:25 UTC, scottrigby commented
Related to https://github.com/prometheus-community/helm-charts/issues/24

2020-09-27 12:31 UTC, scottrigby commented
Have these CRDs been updated in the upstream https://github.com/prometheus-operator/kube-prometheus project? This may be a question for @brancz

2020-09-27 14:32 UTC, bashofmann commented
I took the CRDs in this PR directly from here: https://github.com/prometheus-operator/prometheus-operator/tree/v0.42.1/example/prometheus-operator-crd

2020-09-27 19:17 UTC, scottrigby commented
@bashofmann OK thanks yes, it appears the source – generated as part of the `prometheus-operator/kube-prometheus` project (which this chart installs) – is here: https://github.com/prometheus-operator/kube-prometheus/tree/master/manifests/setup

These were updated recently upstream:

- to `0.42.0` https://github.com/prometheus-operator/kube-prometheus/pull/674
- to `0.42.1` https://github.com/prometheus-operator/kube-prometheus/pull/685

Which is interesting to me. I wonder:
1. why the chart [README](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#helm-fails-to-create-crds) recommends installing directly from `https://raw.githubusercontent.com/prometheus-operator/prometheus-operator` as opposed to from the `kube-prometheus` generated manifests
1. and why the chart [crds](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/crds) dir files have [similar comments](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanager.yaml#L1) listing `prometheus-operator/prometheus-operator` as the file source
1. Also, this chart's `hack` dir has sync scripts for grafana dashboards and prom rules, but not for CRDs – should it? 

Maybe some of the other `kube-prometheus` project maintainers can help me understand if these are just relics/gaps left over from the stable chart, or if there is some reason. Either way I think we can clean this up and decide on a nicer path forward to keep better in sync with the upstream `kube-prometheus` project. CC @metalmatze @paulfantom @lilic

2020-09-27 20:56 UTC, bashofmann commented
Are you sure that `kube-prometheus` is the source of truth for the CRDs? It feels more logical to me that the source of truth is in `prometheus-operator` which uses and implements logic for these CRDs and not in `kube-prometheus` which bundles the operator with monitors, dashboards and rules.

2020-09-28 07:54 UTC, paulfantom commented
The source of truth for CRDs is their [jsonnet definition in prometheus-operator repository](https://github.com/prometheus-operator/prometheus-operator/tree/master/jsonnet/prometheus-operator), this is used to generate [yaml files in prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/tree/master/example/prometheus-operator-crd) and it is also consumed by kube-prometheus.

2020-09-30 17:59 UTC, Nuru commented
This chart fails on AWS EKS and probably fails on GKE due to the `kubeVersion` constraint:
```
Error: UPGRADE FAILED: chart requires kubeVersion: >=1.16.0 which is incompatible with Kubernetes v1.17.9-eks-4c6976
```
Solution appears to be to change the constraint to `>=1.16.0-0`. See https://github.com/helm/helm/issues/3810#issuecomment-379877753 and [this documentation](https://github.com/Masterminds/semver#checking-version-constraints)

2020-10-01 09:32 UTC, bashofmann commented
Thanks, good catch. I fixed the constraint and rebased the PR.

2020-10-02 23:21 UTC, deleted commented
I would also love to see this PR land, as `prometheus-operator` v0.39 added support to enable the prometheus query logger.

2020-10-06 03:36 UTC, uptickmetachu commented
(Also keenly interested in this one for black box exporter)

2020-10-06 08:04 UTC, bashofmann commented
@scottrigby Is there anything else this PR needs besides the obvious rebase?

2020-10-06 08:32 UTC, monotek commented on charts/kube-prometheus-stack/values.yaml
> +      tag: v2.19.2
this could be v2.21.0

2020-10-06 08:34 UTC, monotek requested changes
resolve merge conflict please

2020-10-06 08:41 UTC, bashofmann commented on charts/kube-prometheus-stack/values.yaml
> +      tag: v2.19.2
Done

2020-10-06 09:26 UTC, monotek submitted a review, later dismissed

2020-10-07 08:40 UTC, bashofmann commented
I rebased the branch again to resolve conflicts.

2020-10-08 08:09 UTC, bashofmann commented
The lint task seems to have failed due to a network hickup. Is there a way to rerun it (with the right permissions), or do I need to make a tiny change and push again?

2020-10-08 21:30 UTC, monotek requested changes
@bashofmann 

Could you merge the changes from master to your branch introduced by #191 please?
After that linting should succeed :)

2020-10-09 07:47 UTC, bashofmann commented
@monotek rebased and pushed

2020-10-09 11:14 UTC, monotek approved these changes

2020-10-09 19:26 UTC, scottrigby approved these changes
Thanks for your work on this

2020-10-09 19:28 UTC, merged