[prometheus-cloudwatch-exporter] configurable annotations
prometheus-community/helm-charts pull request #1294
Opened 2021-08-30 06:53 UTC by chelomontilla

Signed-off-by: Chelo Montilla <chelo.montilla@lansweeper.com>

#### What this PR does / why we need it:
This PR allows to configure pod annotations in prometheus cloudwatch exporter chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-09-20 14:04 UTC, monotek requested changes

2021-09-20 14:04 UTC, monotek commented on charts/prometheus-cloudwatch-exporter/Chart.yaml
> +version: 0.16.1
new feature should raise minor version

2021-11-04 07:09 UTC, chelomontilla reviewed
thanks

2021-11-04 07:09 UTC, chelomontilla commented on charts/prometheus-cloudwatch-exporter/Chart.yaml
> +version: 0.16.1
ok

2021-11-04 07:10 UTC, chelomontilla commented
could someone please merge this ? the pr was auto closed

2021-11-04 07:43 UTC, monotek commented
You've still raising the patch version. 
Please raise minor version: https://semver.org/lang/de/

2021-11-04 07:44 UTC, monotek reviewed
You've still raising the patch version.
Please raise minor version: https://semver.org/lang/de/

2021-11-07 00:51 UTC, monotek approved these changes

2021-11-07 00:51 UTC, merged