allow for defining DATA_SOURCE_URI_FILE when used with vault-agent-in…
prometheus-community/helm-charts pull request #1309
Opened 2021-09-01 15:38 UTC by mike2194

…jector

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-09-03 07:46 UTC, zanhsieh commented
@mike2194 
Could you sign DCO please?

2021-09-03 13:09 UTC, mike2194 commented
> @mike2194
> Could you sign DCO please?

my fault, did not signoff on version bump commit.  FIXED

2021-09-04 03:04 UTC, zanhsieh approved these changes

2021-09-04 03:14 UTC, zanhsieh requested changes

2021-09-04 03:14 UTC, zanhsieh commented on charts/prometheus-postgres-exporter/Chart.yaml
> +version: 2.3.6
Hey @mike2194 

Probably needs another version bump.

```
...
"prometheus-community" has been added to your repositories
Linting chart 'prometheus-postgres-exporter => (version: "2.3.6", path: "charts/prometheus-postgres-exporter")'
Checking chart 'prometheus-postgres-exporter => (version: "2.3.6", path: "charts/prometheus-postgres-exporter")' for a version bump...
Error: Error linting charts: Error processing charts
Old chart version: 2.3.6
New chart version: 2.3.6
------------------------------------------------------------------------------------------------------------------------
 ✖︎ prometheus-postgres-exporter => (version: "2.3.6", path: "charts/prometheus-postgres-exporter") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
Error linting charts: Error processing charts
Error: Process completed with exit code 1.
```

2021-09-09 12:09 UTC, mike2194 commented on charts/prometheus-postgres-exporter/Chart.yaml
> +version: 2.3.6
Done!

2021-09-09 12:47 UTC, zanhsieh approved these changes

2021-09-09 12:55 UTC, zanhsieh commented
@mike2194 
Need to bump the chart version in Charts.yaml to latest. Without it, the lint-test won't pass.

2021-09-20 18:33 UTC, monotek requested changes
Please update chart versiobn too

2021-10-02 07:26 UTC, monotek requested changes
Please raise chart version

2021-11-15 15:59 UTC, closed without merging