[kube-prometheus-stack] Add a UID to the prometheus grafana chart
prometheus-community/helm-charts pull request #132
Opened 2020-09-22 23:12 UTC by cryptk

Signed-off-by: Chris Jowett <cryptk@gmail.com>
#### What this PR does / why we need it:
Adds a UID to the prometheus dashboard so the URL will remain consistent across container restarts

#### Which issue this PR fixes
No open issue currently, but I can open one if you like

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-09-27 15:53 UTC, Xtigyro commented
Hey @cryptk 👋 Thank you for the contribution - it's appreciated!

How did you generate the UID value? In other words, how did you come to the conclusion it should be the one you set?

2020-11-10 21:37 UTC, monotek approved these changes

2020-11-10 21:38 UTC, monotek requested changes
Please update version.

2020-11-11 00:30 UTC, bismarck requested changes
Please see the [note](https://github.com/prometheus-community/helm-charts/blob/f2d7ca7f5806ab42bef5801922baedce9d38c008/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml#L1-L5) at the top of the file. Need to fix this upstream.

2020-12-25 01:11 UTC, closed without merging