[alertmanager] Add support for ingressClassName
prometheus-community/helm-charts pull request #1371
Opened 2021-09-24 09:55 UTC by NiklasWagner

#### What this PR does / why we need it:
This PR adds support for ingressClassName since the old [ingress.class annotation](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) is now considered as deprecated.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

I had to introduce a breaking change to support the new pathType field.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-09-27 18:46 UTC, monotek requested changes
As we're already updating the ingress we could just use the default one the command `helm create alertmanager` creates, if helm 3.7.0 is used.

Thoughts?

2021-09-28 09:44 UTC, NiklasWagner commented
Yeah that is a good idea to avoid different implementation, I've updated the PR :)

2021-09-29 06:38 UTC, monotek requested changes
Please fix ci.

And did you also copied the ingress config from the helm created values file?

2021-09-29 07:56 UTC, NiklasWagner commented
Hi, yeah I did copy the original helm ingress from the helm template. I've fixed the CI.

2021-10-03 16:37 UTC, monotek approved these changes

2021-10-03 16:37 UTC, merged