[kube-prometheus-stack] Bump Kube-prometheus-stack versions
prometheus-community/helm-charts pull request #1397
Opened 2021-10-05 10:15 UTC by QuentinBisson

Signed-off-by: QuentinBisson <quentin@giantswarm.io>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-10-20 08:44 UTC, zanhsieh submitted a review, later dismissed

2021-10-24 21:15 UTC, monotek submitted a review, later dismissed

2021-11-15 06:53 UTC, zanhsieh approved these changes

2021-11-20 16:37 UTC, monotek requested changes

2021-11-20 16:37 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 20.0.2
imho minor version should be raised.

2021-11-20 16:37 UTC, monotek commented on charts/kube-prometheus-stack/values.yaml
> +      tag: v2.30.3
```suggestion
      tag: v2.31.1
```

2021-11-22 08:25 UTC, QuentinBisson commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 20.0.2
```suggestion
version: 20.1.0
```

2021-11-23 10:57 UTC, desaintmartin commented
Could you signoff the commit(s) to please DCO test?

2021-11-23 11:18 UTC, QuentinBisson commented
Sure, I thought I did yesterday

2021-11-23 21:55 UTC, zanhsieh approved these changes

2021-11-26 23:55 UTC, monotek approved these changes

2021-11-26 23:56 UTC, merged