[kube-prometheus-stack] Apply scrapeTimeout config to all kubelet service monitors
prometheus-community/helm-charts pull request #1408
Opened 2021-10-06 18:59 UTC by artificial-aidan

Signed-off-by: Aidan Jensen <aidan@artificial.com>

#### What this PR does / why we need it:

Applies existing scrapeTimeout to all service monitor endpoints for kubelet

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

@vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro 

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-11-15 19:03 UTC, artificial-aidan commented
Merged main again. What else is needed?

2021-11-16 05:55 UTC, zanhsieh approved these changes

2021-11-20 16:31 UTC, monotek requested changes
the new option should be reflectd in the values.yaml too.

2021-11-29 20:19 UTC, artificial-aidan commented
> the new option should be reflectd in the values.yaml too.

There is no new option, these options should have been applied the whole time, but it was missed. It follows the way other options are used.

2021-12-02 10:08 UTC, monotek approved these changes

2021-12-02 10:09 UTC, merged