Fix broken link in comment
prometheus-community/helm-charts pull request #141
Opened 2020-09-24 10:37 UTC by Haavare

Hi,
just a small change, the link should be like this:
https://prometheus.io/docs/alerting/latest/configuration/#tmpl_string

thanks

2020-09-24 16:19 UTC, monotek requested changes
Please raise chart version, & sign DCO.

2020-10-01 08:43 UTC, Haavare commented
@monotek
Now I think it is all done

2020-10-02 07:24 UTC, gkarthiks submitted a review, later dismissed

2020-10-06 19:35 UTC, gkarthiks approved these changes

2020-10-07 20:19 UTC, bismarck approved these changes
lgtm

2020-10-07 20:20 UTC, merged