[kube-prometheus-stack] add scheme and tlsConfig to node exporter ServiceMonitor
prometheus-community/helm-charts pull request #1488
Opened 2021-11-04 22:06 UTC by rcanderson23

#### What this PR does / why we need it:
This adds the ability to configure TLS and scheme to the node exporter ServiceMonitor.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-11-09 19:58 UTC, monotek requested changes

2021-11-09 19:58 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 19.2.4
new feature should raise minor version

2021-11-09 20:27 UTC, monotek requested changes

2021-11-09 20:27 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 19.3.3
```suggestion
version: 19.4.0
```

2021-11-10 11:15 UTC, monotek requested changes
please fix dco: https://github.com/prometheus-community/helm-charts/pull/1488/checks?check_run_id=4164371258

2021-11-10 15:51 UTC, rcanderson23 commented
Followed the instructions in the link but doesn't appear to have signed off the commit where it is missing. Any suggestions on how to resolve this?

2021-11-10 16:25 UTC, monotek commented
Rebase to main, squash and and force push....

2021-12-21 22:44 UTC, mrueg commented
kube-prometheus-stack is using now servicemonitor of the node-exporter chart. Do you want to target this one instead?

2022-02-05 03:12 UTC, closed without merging