[kube-prometheus-stack] removed app:alertmanager label
prometheus-community/helm-charts pull request #1494
Opened 2021-11-08 13:02 UTC by frittenlab

#### What this PR does / why we need it:

This PR removes the label selector app:alertmanager from the alertmanager service. As the label has been removed by the Prometheus Operator stateful set in the current version 0.52.2

#### Which issue this PR fixes

The alertmanager service does not have any endpoints after updating the Prometheus Operator image to 0.52.2. Because the label selector as been changed.

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-11-09 20:02 UTC, monotek requested changes
chart version needs to be raised...

2021-11-10 01:26 UTC, bismarck approved these changes
lgtm

2021-11-10 01:35 UTC, larivierec commented
can confirm this is the issue i was having with 20.0.0

2021-11-10 01:42 UTC, bismarck approved these changes

2021-11-10 01:52 UTC, merged