style(grafana): fix typo
prometheus-community/helm-charts pull request #150
Opened 2020-09-28 08:52 UTC by jai

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-09-28 09:03 UTC, monotek requested changes
You have to raise the chart version too.
An please sign your commits to get the DCO check passed: https://github.com/prometheus-community/helm-charts/pull/150/checks?check_run_id=1175570543

2020-09-29 05:04 UTC, jai commented
@monotek thanks, and done!

2020-10-02 03:34 UTC, gkarthiks approved these changes

2020-10-05 07:09 UTC, monotek approved these changes

2020-10-05 15:32 UTC, gkarthiks approved these changes

2020-10-05 15:33 UTC, merged