[prometheus-elasticsearch-exporter] Support extra arguments to the pod's container
prometheus-community/helm-charts pull request #1547
Opened 2021-11-30 10:14 UTC by mosheavni

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-12-02 09:33 UTC, monotek requested changes
Please also sign your commits and rebase with master

2021-12-02 09:33 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.9.1
new feature should raise minor version

2021-12-02 10:09 UTC, monotek approved these changes

2022-01-02 01:02 UTC, monotek requested changes

2022-01-02 01:02 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.10.0
```suggestion
version: 4.11.0
```

2022-01-02 11:34 UTC, monotek requested changes
Please rebase / resolve merge conflicts and sign your commits.

2022-01-02 13:24 UTC, mosheavni commented
i kinda regret trying to contribute here. too much bureaucracy and headache........

2022-01-02 22:33 UTC, monotek approved these changes

2022-01-02 22:33 UTC, merged