missplaced end tag in alertmanager chart
prometheus-community/helm-charts pull request #1575
Opened 2021-12-08 14:18 UTC by jouve

fix for #1572 + added some unittest for both the initial issue and this regression

2021-12-08 14:53 UTC, monotek requested changes
please sign your commits and fix typo

2021-12-08 15:21 UTC, jouve commented
CI is green.
The added tests [ran](https://github.com/prometheus-community/helm-charts/runs/4458897681?check_suite_focus=true):
```

### Chart [ kube-prometheus-stack ] charts/kube-prometheus-stack

 PASS  test alertmanager	charts/kube-prometheus-stack/unittests/alertmanager/alertmanager_test.yaml
 PASS  test ingress	charts/kube-prometheus-stack/unittests/alertmanager/ingress_test.yaml

Charts:      1 passed, 1 total
Test Suites: 2 passed, 2 total
Tests:       9 passed, 9 total
Snapshot:    0 passed, 0 total
Time:        77.410869ms
̀̀```

2021-12-08 16:40 UTC, gkarthiks approved these changes

2021-12-08 18:30 UTC, monotek requested changes

2021-12-08 18:30 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 23.1.2
```suggestion
version: 23.1.3
```

2021-12-09 08:45 UTC, merged

2021-12-09 11:21 UTC, jouve commented
I got busy with something else. thanks for the merge :)