Add support for indices mappings
prometheus-community/helm-charts pull request #1610
Opened 2021-12-16 21:38 UTC by chasain

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-12-17 13:13 UTC, monotek requested changes

2021-12-17 13:13 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.9.1
new feature shoud raise minor version

2021-12-20 21:23 UTC, chasain commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.9.1
updated

2021-12-20 22:26 UTC, monotek approved these changes

2021-12-20 22:43 UTC, merged