Proposition to not scrape not running pods
prometheus-community/helm-charts pull request #166
Opened 2020-09-30 15:54 UTC by mtparet

Prometheus try to scrape not running pods which cause reporting failures to scrape these ones. 

If it seems legit, I will review the PR to follow the contribution guidelines.

Best,

2020-09-30 22:12 UTC, zanhsieh commented
@mtparet 
Could you bum the Chart version to latest please?

2020-10-01 12:08 UTC, naseemkullah commented
It might make sense to first get it (and any prometheus.yml changes) merged in the [promtheus-kubernetes.yml](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) from the app repo, and then this chart can base the out of box config from there.

@prometheus-community/helm-charts-admin thoughts?

2020-10-01 12:47 UTC, Xtigyro commented
> 
> 
> It might make sense to first get it (and any prometheus.yml changes) merged in the [promtheus-kubernetes.yml](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) from the app repo, and then this chart can base the out of box config from there.
> 
> @prometheus-community/helm-charts-admin thoughts?

That might be a good idea but can the two files be absolutely the same at some point? I don't know whether the Prom devs would want that.

2020-10-01 12:49 UTC, Xtigyro requested changes
@mtparet The chart version needs bumping. Also - could you please sign your commits?

2020-10-01 13:23 UTC, brancz commented
I don't think the files being identical is the point, it's just that the upstream config should reflect configuration that applies to everyone, which this case falls into.

2020-10-01 13:55 UTC, Xtigyro commented
@brancz Agreed.

2020-10-01 18:14 UTC, kfox1111 commented
if it avoids scraping a non running pod, will prometheus still know to report that endpoint as up=0?

2020-10-03 09:18 UTC, monotek requested changes
This should be optional and default should be disabled, to not break current behaviour.

Minor Chart version needs to be raised. 

Commits needs to be signed: https://github.com/prometheus-community/helm-charts/pull/166/checks?check_run_id=1188733204

2020-10-05 08:40 UTC, mtparet commented
> @mtparet The chart version needs bumping. Also - could you please sign your commits?

@Xtigyro done :)


> Minor Chart version needs to be raised.
Commits needs to be signed: #166 (checks)

@Xtigyro done :)


> if it avoids scraping a non running pod, will prometheus still know to report that endpoint as up=0?

This metrics does not come from scrapping pods but from kube state metrics.

> This should be optional and default should be disabled, to not break current behaviour.

If the pods are not running, we already didn't collect any metrics when trying to scrape these one. So I do not think this is a breaking change. I'm happy to understand/hear the contrary :)

2020-10-05 09:12 UTC, Xtigyro commented
@naseemkullah @monotek Are we happy to merge this now? I think it should be ready.

2020-10-05 12:05 UTC, zanhsieh approved these changes

2020-10-05 13:35 UTC, naseemkullah commented
I still think config changes should go through [promtheus-kubernetes.yml](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) 🤷‍♀️ but don't want to block so do as you please.

2020-10-05 13:37 UTC, Xtigyro commented
@naseemkullah I agree with ya. What can we do to achieve that?

2020-10-05 13:42 UTC, naseemkullah commented
@mtparet would it be possible to make a PR to https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml ?

@Xtigyro we could add a note in readme that `prometheus.yml` changes should be made in that repo then they can make the PR here or maintainers periodically sync from there to here.

2020-10-05 13:46 UTC, monotek approved these changes

2020-10-05 13:47 UTC, monotek commented
Imho the sync issue should not prevent us to merge this.

2020-10-05 17:46 UTC, Xtigyro commented
Agreed - let's merge this and create a PR in the Prom repo and try to be in sync with it.

2020-10-05 17:46 UTC, Xtigyro approved these changes

2020-10-05 17:46 UTC, merged

2020-10-06 10:25 UTC, mtparet commented
Thanks for merging!

@naseemkullah I will do that:)

2020-10-06 10:43 UTC, mtparet commented
I just took a look at https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml there are already lot of difference with the current state of the file here.

I'm not sure if the purpose of the example is to be the exactly config file to be applied in production and if Prometheus maintainers want to maintain it in their repo.

2020-10-06 10:50 UTC, Xtigyro commented
@mtparet They don't need to be identical but the upstream config should reflect configuration that applies to everyone - so you can add just your code there from this PR.