[kube-prometheus-stack] image tag and sha logic for alertmanager instance
prometheus-community/helm-charts pull request #1684
Opened 2022-01-06 15:29 UTC by sbeginCoveo

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@andrewgkew @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro

#### What this PR does / why we need it:

We have strick requirements to use sha256 on all our container images. Alertmanager's template did not allow for that. Even though you can configure it in the spec.sha field, it wasn't used.

#### Special notes for your reviewer:

This is the same logic that is used to template the Prometheus instance
There should be no breaking changes

#### Checklist
- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-06 15:31 UTC, bmarquesCoveo approved these changes

2022-01-06 23:11 UTC, monotek requested changes
Works for me:

```
helm template . --set alertmanager.alertmanagerSpec.image.sha=FooBarSha | yq e 'select(.kind == "Alertmanager")' -
# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: RELEASE-NAME-kube-promethe-alertmanager
  namespace: strimzi
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "28.0.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-28.0.0
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  image: quay.io/prometheus/alertmanager:v0.23.0
  version: v0.23.0
  sha: FooBarSha
  replicas: 1
  listenLocal: false
  serviceAccountName: RELEASE-NAME-kube-promethe-alertmanager
  externalUrl: http://RELEASE-NAME-kube-promethe-alertmanager.strimzi:9093
  paused: false
  logFormat: "logfmt"
  logLevel: "info"
  retention: "120h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: http-web

```

2022-01-07 15:00 UTC, sbeginCoveo commented
Hey @monotek! And thanks for answering

Indeed it is properly templated in this resource. The issue is that it isn't used by the prometheus-operator to provision the alertmanager statefulset correctly. Maybe it should be fixed in the operator instead, I should've discussed this in an issue first.

Here is a breakdown of the inconsistencies causing the issue:

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml#L16
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
spec:
  image: ecr.us-east-1.amazonaws.com/prometheus/alertmanager:v0.21.0
  version: v0.21.0
  sha: 6ff21231231231236d44
```
which is later provisioned by the operator as
```
apiVersion: apps/v1
kind: StatefulSet
spec.template.spec:
  containers:
    - image: ecr.us-east-1.amazonaws.com/prometheus/alertmanager:v0.21.0
```

But with a very similar configuration used in the Prometheus crd, 
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L36
we end up with redundant information in the image itself
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  image: "ecr.us-east-1.amazonaws.com/prometheus/prometheus:v2.22.1@sha256:d0987987987228f2"
  version: v2.22.1
  sha: d0987987987228f2
```
and this time it makes its way to the STS:
```
apiVersion: apps/v1
kind: StatefulSet
spec.template.spec:
  containers:
    - image: ecr.us-east-1.amazonaws.com/prometheus/prometheus:v2.22.1@sha256:d0987987987228f2
```

2022-01-07 16:22 UTC, monotek requested changes
Thanks, now i see the difference:

```
 helm template . --set prometheus.prometheusSpec.image.sha=FooBarSha | yq e 'select(.kind == "Prometheus")' -
# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: RELEASE-NAME-kube-promethe-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "28.0.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-28.0.0
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: RELEASE-NAME-kube-promethe-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.32.1@sha256:FooBarSha"
  version: v2.32.1
  sha: FooBarSha
  externalUrl: http://RELEASE-NAME-kube-promethe-prometheus.monitoring:9090
  paused: false
  replicas: 1
  shards: 1
  logLevel: info
  logFormat: logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  routePrefix: "/"
  serviceAccountName: RELEASE-NAME-kube-promethe-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "RELEASE-NAME"
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "RELEASE-NAME"
  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "RELEASE-NAME"
  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "RELEASE-NAME"
  portName: http-web

```

Please update chart version....

2022-01-07 16:46 UTC, monotek approved these changes

2022-01-07 16:50 UTC, merged