[prometheus-node-exporter] reintroduce service monitor selectorOverride
prometheus-community/helm-charts pull request #1699
Opened 2022-01-11 02:58 UTC by jurgen-weber-deltatre

#### What this PR does / why we need it:
I am bringing back the service monitor selectorOverride option that were removed in v24 (https://github.com/prometheus-community/helm-charts/commit/c75ec1c8ead17a745b9e141da4ebd51922626794) when deprecating the kube-prom-stack Service Monitors in favour of the tools specific chart Service Monitors.

#### Which issue this PR fixes
While I could not find the old issue from many years ago, this override was introduced to solve problems with various deployment tools that take over labels. In our case ArgoCD which changes the value the instance label. Once I upgraded to 24 I realised I lost a lot of metrics and that is because the service monitor labels were all wrong and I could find no equivalent new field.

#### Special notes for your reviewer:

#### Checklist

- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-11 02:59 UTC, jurgen-weber-deltatre commented
as per https://github.com/prometheus-community/helm-charts/pull/1617

2022-01-11 08:38 UTC, monotek requested changes
new feature should raise minor version

2022-01-12 08:31 UTC, monotek approved these changes

2022-01-12 14:12 UTC, mrueg approved these changes

2022-01-12 22:08 UTC, jurgen-weber-deltatre commented
Can we merge please ? :)

2022-01-13 11:55 UTC, merged