[prometheus] Fix order of --web.route-prefix arg as described in https://github.co…
prometheus-community/helm-charts pull request #1715
Opened 2022-01-14 14:57 UTC by js8080

…m/prometheus-community/helm-charts/issues/1594

#### What this PR does / why we need it:
Fixes the order of the --web.route-prefix cli arg in the prometheus-server chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #1594 1594

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-15 01:53 UTC, zanhsieh submitted a review, later dismissed

2022-01-15 13:09 UTC, monotek approved these changes

2022-01-15 13:10 UTC, monotek requested changes
Changes in multiple charts do not work

2022-01-24 19:39 UTC, js8080 commented
> Changes in multiple charts do not work

Somehow another commit was added by another person. I just reverted that in my latest commit so this should be resolved now.

2022-01-24 19:58 UTC, js8080 commented
I screwed up the history on this somehow. I'm deleting it and making a new PR...

2022-01-24 19:58 UTC, closed without merging