[kube-prometheus-stack] Fix alertmanager podAntiAffinity
prometheus-community/helm-charts pull request #1717
Opened 2022-01-17 16:54 UTC by CVirus

#### What this PR does / why we need it:

This PR fixes the `matchExpression` for alertmanager `podAntiAffinity` configuration. Replacing `app` with `app.kubernetes.io/name` since alertmanager pods do NOT have an `app` label so the podAntiAffinity config didn't actually work.

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-17 17:01 UTC, CVirus commented
@andrewgkew @bismarck @desaintmartin @gianrubio @gkarthiks @scottrigby @Xtigyro Please review whenever you find. Thanks in advance!

2022-01-18 01:43 UTC, monotek approved these changes

2022-01-19 08:26 UTC, CVirus commented
@monotek Thanks for the approval. Do I need approval from ALL the maintainers to get this merged?

2022-01-19 15:17 UTC, mrueg approved these changes
not a maintainer but this makes sense to me.

2022-01-19 15:19 UTC, monotek requested changes

2022-01-19 15:19 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 30.0.2
```suggestion
version: 30.0.3
```

2022-01-19 15:49 UTC, monotek approved these changes

2022-01-19 16:28 UTC, CVirus commented
@monotek @mrueg Sorry had to sync fork. Please approve again whenever you can.

2022-01-19 16:50 UTC, mrueg approved these changes

2022-01-19 17:33 UTC, merged