[kube-prometheus-stack]  Scope CoreDNS dashboard to CoreDNS job
prometheus-community/helm-charts pull request #1730
Opened 2022-01-19 16:22 UTC by aslafy-z

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-19 17:35 UTC, monotek requested changes

2022-01-19 17:35 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 30.0.3
```suggestion
version: 30.0.4
```

2022-01-19 18:50 UTC, aslafy-z commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 30.0.3
I just bumped the version

2022-01-20 08:43 UTC, monotek requested changes

2022-01-20 08:43 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 30.0.4
```suggestion
version: 30.1.1
```

2022-01-20 08:44 UTC, monotek approved these changes

2022-02-07 11:58 UTC, desaintmartin commented
Thanks! Could you rebase?

2022-02-07 12:07 UTC, desaintmartin approved these changes

2022-02-07 12:08 UTC, monotek approved these changes

2022-02-07 12:16 UTC, merged