Add support for containerSecurityContext to fix #1741
prometheus-community/helm-charts pull request #1744
Opened 2022-01-25 16:46 UTC by AshutoshNirkhe

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-25 18:36 UTC, monotek requested changes
Please change minor chart version, not app version.

2022-01-27 05:10 UTC, AshutoshNirkhe commented
> Please change minor chart version, not app version.

Thanks @monotek I have updated it now, could you please check again ?

2022-01-28 14:04 UTC, monotek requested changes

2022-01-28 14:04 UTC, monotek commented on charts/prometheus-pushgateway/values.yaml
> +  allowPrivilegeEscalation: false
imho these vlaues should not be added by default or updating the chart for some users might break.

2022-01-28 22:36 UTC, monotek approved these changes

2022-01-28 22:37 UTC, merged

2022-01-31 16:06 UTC, djsly commented
thanks a lot @AshutoshNirkhe  for this work