[kube-prometheus-stack] Inhibit info alerts unless other alerts fire
prometheus-community/helm-charts pull request #1745
Opened 2022-01-26 12:40 UTC by wiegandf

#### What this PR does / why we need it:
Sync of https://github.com/prometheus-operator/kube-prometheus/pull/1507

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-01-26 16:11 UTC, monotek requested changes

2022-01-26 16:11 UTC, monotek commented on charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml
> +{{- if not (.Values.defaultRules.disabled.InfoInhibitor | default false) }}
https://github.com/prometheus-community/helm-charts/blob/fb2f8597cc2539c9ec9ef3edab1e4f5a04863b19/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml#L2-L4

2022-01-26 16:11 UTC, monotek commented on charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml
> +    - expr: |-
https://github.com/prometheus-community/helm-charts/blob/fb2f8597cc2539c9ec9ef3edab1e4f5a04863b19/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L2-L4

2022-01-26 16:11 UTC, monotek commented on charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
> +            kube_daemonset_status_updated_number_scheduled{job="kube-state-metrics", namespace=~"{{ $targetNamespace }}"}
https://github.com/prometheus-community/helm-charts/blob/fb2f8597cc2539c9ec9ef3edab1e4f5a04863b19/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L2-L4

2022-01-28 13:58 UTC, monotek commented
> @monotek sorry for not following the process, I thought I would.
> 
> I just did the last two points https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/README.md?plain=1#L20-L21
> 
> The alerts I want to sync are already on `prometheus-operator/kube-prometheus` master, so what am I missing?

You have to adjust the python scipt or your changes will be overwritten on next sync.

2022-02-04 08:48 UTC, wiegandf commented
I am sorry I don't get what needs to be changed. The readme doesn't contain any instructions for it and the python script doesn't links to main branch. https://github.com/prometheus-community/helm-charts/blob/3663f3c71b22938891318a352fea40208261e0de/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L33

2022-03-25 00:37 UTC, closed without merging