[kube-prometheus-stack] add support for configure services externalTr…
prometheus-community/helm-charts pull request #1757
Opened 2022-01-31 16:32 UTC by alonbhaim

…afficPolicy using values

Signed-off-by: Alon Ben Haim <alon.benhaim@kaltura.com>

#### What this PR does / why we need it:
Sometimes using when service we need the ability to control the external traffic policy of the service, now I added the following option using the values.yaml for all relevant services in the chart.

#### Which issue this PR fixes
* will close that #https://github.com/prometheus-community/helm-charts/issues/1755 issue when PR gets merged 

#### Checklist
- [X] [DCO] signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name

2022-02-03 00:02 UTC, yurrriq commented
@alonbhaim, can you bump the chart version? We need this too.

2022-02-03 07:41 UTC, alonbhaim commented
> @alonbhaim, can you bump the chart version? We need this too.

Sure, I'll pull changes from main branch to my fork and will push new version.

2022-02-03 08:22 UTC, alonbhaim commented
@yurrriq merged lastest changes from upstream and bumped the version.

2022-02-07 18:00 UTC, yurrriq commented
Thanks! Now we just need a code owner to approve.

2022-02-08 07:13 UTC, alonbhaim commented
@monotek can you re-run the lint checks ?

2022-02-08 08:35 UTC, monotek approved these changes

2022-02-09 08:02 UTC, alonbhaim commented
Hi,
Can you please review ? @andrewgkew @bismarck @desaintmartin @desaintmartin @gianrubio @gkarthiks @scottrigby @Xtigyro

2022-02-09 08:09 UTC, monotek requested changes

2022-02-09 08:09 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> -  - name: GMartinez-Sisti
please add back

2022-02-09 10:51 UTC, monotek approved these changes

2022-02-09 10:51 UTC, merged