[prometheus-stackdriver-exporter] Switch exporter config to agrs instead of env variables.
prometheus-community/helm-charts pull request #1790
Opened 2022-02-10 10:09 UTC by anas-aso

#### What this PR does / why we need it:
Upgrade app version to 0.12.0 https://github.com/prometheus-community/stackdriver_exporter/releases/tag/v0.12.0
This version comes with a breaking change of dropping env variables config for this exporter: https://github.com/prometheus-community/stackdriver_exporter/pull/142

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
I bumped the chart version to 2.0.0 due to the change in how config is passed to the exporter.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-02-10 10:20 UTC, monotek requested changes
Please add an info about this change to the upgrading section of the readme.

2022-02-10 10:22 UTC, anas-aso commented
@monotek there isn't really any breaking change for users of the chart itself. So I think that an upgrade guide is needed.

2022-02-10 10:32 UTC, monotek requested changes
People using .Values.extraArgs could run into problems, if something would be already declared. So at least a warning would be nice.

Also please fix ci.

2022-02-15 10:53 UTC, rpahli approved these changes

2022-02-15 10:53 UTC, merged