[kube-prometheus-stack] Expose the container-specific security context for Prometheus Operator
prometheus-community/helm-charts pull request #1811
Opened 2022-02-18 13:44 UTC by rdauncey53

#### What this PR does / why we need it:
We want to further configure the Kubernetes container security context for the Prometheus Operator, so we can set other container-specific settings such as capabilities -> drop -> ALL. Therefore we expose the container-specific security context using `containerSecurityContext` as the input (as used in other prometheus helm-charts e.g. [node-exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L79)).

#### Special notes for your reviewer:
We understand that some other Prometheus containers such as the node-exporter do not support dropping capabilities (in that case, because it did not have any in the first place) - this pull request assumes that isn't the case for Prometheus Operator, but please do let us know if that is an incorrect assumption.

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-02-18 13:49 UTC, monotek requested changes

2022-02-18 13:49 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 32.2.2
new feature should raise minor version
```suggestion
version: 32.3.0
```

2022-02-18 13:52 UTC, rdauncey53 commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 32.2.2
Sure, have done that.

2022-02-28 09:38 UTC, rdauncey53 commented
(28/2/2022 Fixed some merge conflicts)

2022-02-28 13:41 UTC, monotek approved these changes

2022-02-28 13:48 UTC, merged