[prometheus-blackbox-exporter] Configure namespace on prometheus-blackbox-exporter chart
prometheus-community/helm-charts pull request #1878
Opened 2022-03-16 11:06 UTC by fsequeira1

Configure namespace on prometheus-blackbox-exporter chart

@desaintmartin @gianrubio @rsotnychenko @monotek could you please review this?  

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-03-16 16:04 UTC, monotek requested changes
new feature should raise minor version

2022-03-16 17:52 UTC, fsequeira1 commented
@monotek I had an issue with the DCO I think it's fixed now

2022-03-18 09:32 UTC, monotek submitted a review, later dismissed

2022-03-18 12:51 UTC, monotek approved these changes

2022-03-18 12:51 UTC, merged

2022-03-21 00:50 UTC, calvinbui commented
getting this error:

```
Error: template: prometheus-blackbox-exporter/templates/_helpers.tpl:77:16: executing "prometheus-blackbox-exporter.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride
```