Delete statefulset.yaml
prometheus-community/helm-charts pull request #1892
Opened 2022-03-20 14:09 UTC by tamalsaha

Signed-off-by: Tamal Saha <tamal@appscode.com>

#### What this PR does / why we need it:
This was removed from the mixin project. But it was not removed from the chart.
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/598

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-03-21 08:15 UTC, monotek requested changes
please update chart version

2022-03-21 08:52 UTC, tamalsaha commented
done!

2022-03-21 12:08 UTC, monotek commented
Have you checked the update script for needed changes?
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py

2022-03-21 12:13 UTC, tamalsaha commented
Yes. I deleted the templates in this folder and then generated using that script.

2022-03-21 12:40 UTC, monotek submitted a review, later dismissed

2022-04-23 13:22 UTC, tamalsaha commented
ping!

2022-04-23 15:51 UTC, monotek approved these changes

2022-04-27 10:51 UTC, monotek requested changes

2022-04-27 10:51 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +appVersion: 0.57.0
```suggestion
appVersion: 0.56.0
```

2022-04-27 10:51 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 35.1.0
```suggestion
version: 35.0.1
```

2022-04-27 17:08 UTC, tamalsaha commented
Done!

2022-04-27 17:15 UTC, monotek approved these changes

2022-04-27 17:15 UTC, merged

2022-04-27 17:35 UTC, tamalsaha commented
Thanks!