[prometheus-adapter] support for topology spread constraints
prometheus-community/helm-charts pull request #1925
Opened 2022-03-28 18:39 UTC by sbeginCoveo

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@MattiasGees @steven-sheehy @hectorj2f

#### What this PR does / why we need it:

As we migrate most of our anti-affinities to topology spread constraints, we need a way to configure them on prometheus-adapter pods. This PR introduces this from the values.yaml. No breaking changes are introduced

#### Special notes for your reviewer:

Cheers!

#### Checklist
- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-03-28 21:28 UTC, monotek requested changes

2022-03-28 21:28 UTC, monotek commented on charts/prometheus-adapter/Chart.yaml
> +version: 3.0.4
New feature should raise minor version

2022-03-29 12:21 UTC, sbeginCoveo commented on charts/prometheus-adapter/Chart.yaml
> +version: 3.0.4
:heavy_check_mark:

2022-03-29 14:47 UTC, steven-sheehy approved these changes
LGTM

2022-03-29 14:47 UTC, merged