[kube-prometheus-stack] add support for enableRemoteWriteReceiver in the prometheuses crd and…
prometheus-community/helm-charts pull request #1963
Opened 2022-04-08 02:23 UTC by daveoy

… write that out into our crd if its in our values file

Signed-off-by: Dave Young <davey@themill.com>

#### What this PR does / why we need it:

the prometheus operator supposedly supports this field in prometheusSpec, but we aren't passing it to the prometheus object via the kube-prometheus-stack helm chart, its also notably missing in the crd.

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec

### Which issue this PR fixes
- fixes 1961

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-04-08 07:13 UTC, monotek requested changes
The CRDs will ve updated together with the prometheus-operator version, by a scrtipt: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/update_crds.sh 

So please always use it and also update prometheus operator to 0.55.1, updating all docker iamges, dadhboards and rules too.

2022-05-14 18:38 UTC, HaroonSaid commented
We are looking forward to turning on `enableRemoteWriteReceiver` 
Can it get merged?

2022-05-19 11:40 UTC, daveoy commented
> The CRDs will ve updated together with the prometheus-operator version, by a scrtipt: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/update_crds.sh
> 
> So please always use it and also update prometheus operator to 0.55.1, updating all docker iamges, dadhboards and rules too.

sorry for the delay, but i have done this. of note, the CRD still does not support enableRemoteWriteReceiver.

2022-05-19 23:07 UTC, monotek requested changes

2022-05-19 23:07 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 35.2.1
New feature should raise minor version.
```suggestion
version: 35.3.0
```

2022-05-20 00:37 UTC, daveoy commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 35.2.1
done

2022-05-21 14:06 UTC, monotek reviewed
i've updated the crd download script to work without input, taking the version form the Chart.yaml.

2022-05-21 14:07 UTC, monotek approved these changes

2022-05-21 14:07 UTC, merged

2022-05-21 14:10 UTC, daveoy commented
> i've updated the crd download script to work without input, taking the version form the Chart.yaml.
> 
> 

Great idea

Thank you for merging.