[prometheus] adding securityContext for prometheus server containers
prometheus-community/helm-charts pull request #1991
Opened 2022-04-15 10:31 UTC by caisindenis

#### What this PR does / why we need it:
This PR will allow set securityContext on containers level on Prometheus server, rather than just pod level that is currently implemented
#### Which issue this PR fixes

  - fixes #1990 

#### Special notes for your reviewer:
[@gianrubio](https://github.com/gianrubio) [@zanhsieh](https://github.com/zanhsieh) [@Xtigyro](https://github.com/Xtigyro) [@naseemkullah](https://github.com/naseemkullah) - Please review this PR and let me know if any change is required.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-04-15 19:49 UTC, zanhsieh requested changes

2022-04-15 19:49 UTC, zanhsieh commented on charts/prometheus/Chart.yaml
> +version: 15.8.2
15.8.4

2022-04-16 01:54 UTC, caisindenis commented on charts/prometheus/Chart.yaml
> +version: 15.8.2
@zanhsieh  updated the version

2022-04-16 07:15 UTC, zanhsieh approved these changes

2022-04-16 07:19 UTC, merged