[kube-prometheus-stack] Add thanosRuler configuration
prometheus-community/helm-charts pull request #1993
Opened 2022-04-15 19:59 UTC by artificial-aidan

#### What this PR does / why we need it:

Follows a similar pattern to `alertmanager` and allows configuration of a `ThanosRuler` instance and access.

#### Special notes for your reviewer:

I started by copying the whole alertmanager directory, but soon realized I would not be able to test all of those configurations. So I added what I can test to the best of my ability.

Mentions: @andrewgkew @desaintmartin @scottrigby @Xtigyro

#### Checklist

- [ X ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ X ] Chart Version bumped
- [ X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-04-29 22:06 UTC, artificial-aidan commented
@monotek Is there anyone else I should tag on this for review/discussion?

2022-05-04 09:50 UTC, monotek commented
One of the maintainers:
https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS#L10

2022-05-11 08:27 UTC, monotek requested changes

2022-05-11 08:27 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 34.11.0
```suggestion
version: 35.3.0
```

2022-06-10 18:05 UTC, artificial-aidan commented
Still waiting on approval

2022-06-10 21:59 UTC, monotek commented
Still waiting that merge conflicts are solved.

2022-06-11 10:41 UTC, monotek requested changes

2022-06-11 10:41 UTC, monotek commented on charts/kube-prometheus-stack/templates/ruler/servicemonitor.yaml
> +      self-monitor: "true"
```suggestion
      self-monitor: {{ .Values.thanosRuler.serviceMonitor.selfMonitor | quote }}
```

2022-06-11 10:41 UTC, monotek commented on charts/kube-prometheus-stack/templates/ruler/extrasecret.yaml
> +{{- if .Values.thanosRuler.extraSecret.data -}}
can we rename the directory from "ruler" to "thanos-ruler" please?

2022-06-23 11:39 UTC, monotek approved these changes

2022-06-23 11:40 UTC, merged