[prometheus] fixing indentation securityContext for prometheus server containers
prometheus-community/helm-charts pull request #1999
Opened 2022-04-20 02:45 UTC by caisindenis

#### What this PR does / why we need it:
PR fixes indentation on securityConext on container level for prometheus
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #1990 

#### Special notes for your reviewer:
[@gianrubio](https://github.com/gianrubio) [@zanhsieh](https://github.com/zanhsieh) [@Xtigyro](https://github.com/Xtigyro) [@naseemkullah](https://github.com/naseemkullah) - Please review this PR and let me know if any change is required.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-04-20 09:02 UTC, monotek approved these changes

2022-04-20 09:07 UTC, monotek requested changes
this looks wrong to me:

```
helm template . --set server.containerSecurityContext.foo=bar

...
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: storage-volume
              mountPath: /data
              subPath: ""
          securityContext:
                        foo: bar
      hostNetwork: false
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: release-name-prometheus-server
        - name: storage-volume
          persistentVolumeClaim:
            claimName: release-name-prometheus-server
```

2022-04-20 09:24 UTC, monotek approved these changes
nevermind. checkd our main branch instead of yours :D

2022-04-20 09:25 UTC, merged

2022-04-25 19:26 UTC, entscheidungsproblem commented
Thanks for getting this added! I noticed that there is no reference to `server.containerSecurityContext` in the `values.yaml` file. I'm not sure if that is usually added but it would be useful for visibility.
Thanks again! 😃 

linking https://github.com/prometheus-community/helm-charts/pull/1991