[prometheus-snmp-exporter] Add pod and container security context
prometheus-community/helm-charts pull request #2002
Opened 2022-04-21 12:44 UTC by tom1299

Signed-off-by: tom1299 <tom1299@jeeatwork.com>

#### What this PR does / why we need it:
Adds the ability to add pod security and container security context to the deployment by specifying them as values.

#### Which issue this PR fixes
None

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-04-21 13:04 UTC, monotek requested changes

2022-04-21 13:04 UTC, monotek commented on charts/prometheus-snmp-exporter/Chart.yaml
> +version: 1.0.2
new feature should raise minor version

2022-04-21 13:19 UTC, tom1299 commented on charts/prometheus-snmp-exporter/Chart.yaml
> +version: 1.0.2
Ok, I change to version to `1.1.0`

2022-04-21 14:30 UTC, monotek requested changes
please fix linter errors...

2022-04-22 08:31 UTC, tom1299 commented
I missed that error when I was testing locally. Now all checks should pass.

2022-04-22 08:46 UTC, monotek approved these changes

2022-04-22 08:46 UTC, merged