[kube-prometheus-stack] Bump to prometheus-operator 0.56.0
prometheus-community/helm-charts pull request #2005
Opened 2022-04-22 14:04 UTC by mrueg

* Sync dashboards
* Sync charts
* Sync crds
* Sync prometheus rules
* Bump prometheus to 2.35.0

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-04-23 15:55 UTC, monotek requested changes
Please fix markdown lint. 
Can we maybe update some of the other used docker images too? Alert manager, thanos etc.?

2022-04-23 21:35 UTC, mrueg commented
> Please fix markdown lint. Can we maybe update some of the other used docker images too? Alert manager, thanos etc.?

Fixed, any version bumps that are missing?

2022-04-24 02:56 UTC, monotek approved these changes

2022-04-24 02:58 UTC, monotek commented
> > Please fix markdown lint. Can we maybe update some of the other used docker images too? Alert manager, thanos etc.?
> 
> Fixed, any version bumps that are missing?

Not sure, didn't check as only on mobile till Monday 😁

2022-04-25 08:48 UTC, merged