[prometheus-blackbox-exporter] Add custom relabeling and quote values
prometheus-community/helm-charts pull request #2033
Opened 2022-05-05 17:23 UTC by epitstickpan

Adds `additionalRelabeling` to ServiceMonitor so that custom relabeling
can be done. I wanted this because I wanted to be able to add the module
as a label but I think there are other good reasons to have it.

While I was here I added `quote` for `additionalMetricsRelabels` so that
values wouldn't be converted.

Please make note of the fact I did a concat instead of replacing default values. I think this is more productive but it works differently than `additionalMetricsRelabels`. Let me know if you want me to change one or the other so they work the same. Wanted to avoid a major bump if I could.

@desaintmartin 

Signed-off-by: Evan Pitstick <epitstick@paloaltonetworks.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-05 17:41 UTC, monotek requested changes

2022-05-05 17:41 UTC, monotek commented on charts/prometheus-blackbox-exporter/Chart.yaml
> +version: 5.7.1
new feature should raise minor version

2022-05-06 15:36 UTC, epitstickpan commented on charts/prometheus-blackbox-exporter/Chart.yaml
> +version: 5.7.1
Thanks, got it.

2022-05-06 15:44 UTC, monotek approved these changes

2022-05-06 15:44 UTC, merged

2022-05-06 18:22 UTC, Gentoli commented
This causes a panic from helm when `target.additionalRelabeling` is not present:
```
Error: template: prometheus-blackbox-exporter/templates/servicemonitor.yaml:43:7: executing "prometheus-blackbox-exporter/templates/servicemonitor.yaml" at <concat .additionalRelabeling $.Values.serviceMonitor.defaults.additionalRelabeling>: error calling concat: runtime error: invalid memory address or nil pointer dereference
```

This is probably a helm issues, but right now it's broken when `target.additionalRelabeling` to not set.

helm version:
`version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}`

2022-05-06 20:41 UTC, epitstickpan commented
> This causes a panic from helm when `target.additionalRelabeling` is not present:
> 
> ```
> Error: template: prometheus-blackbox-exporter/templates/servicemonitor.yaml:43:7: executing "prometheus-blackbox-exporter/templates/servicemonitor.yaml" at <concat .additionalRelabeling $.Values.serviceMonitor.defaults.additionalRelabeling>: error calling concat: runtime error: invalid memory address or nil pointer dereference
> ```
> 
> This is probably a helm issues, but right now it's broken when `target.additionalRelabeling` to not set.
> 
> helm version: `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}`

I have a fix coming in for it. Thanks for the heads up.