[prometheus-elasticsearch-exporter] Allow to set global imagePullSecrets
prometheus-community/helm-charts pull request #2039
Opened 2022-05-09 14:16 UTC by hierynomus

#### What this PR does / why we need it:
The Bitnami charts have a convention that allows one to set a set of global imagePullSecrets which are inherited if you depend on a specific chart from another chart. This obviates the need to repetitively specify the same image pull secrets for all images and charts. This PR adds that same functionality to the elasticsearch-exporter.

Also this PR updates the PodSecurityPolicy to use the non-deprecated apiGroup if it is available, making the chart compatible with modern K8s versions.

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-11 07:16 UTC, monotek approved these changes

2022-05-13 07:35 UTC, hierynomus commented
@monotek Thanks for the review, I fixed one small mistake I made in merging.

2022-05-13 10:14 UTC, monotek requested changes
please fix linting errors

2022-06-13 11:18 UTC, monotek requested changes

2022-06-13 11:18 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.12.0
```suggestion
version: 4.13.0
```

2022-06-13 16:52 UTC, monotek approved these changes

2022-06-13 16:52 UTC, merged