[prometheus-node-exporter] Make liveness and readiness probes customi…
prometheus-community/helm-charts pull request #2053
Opened 2022-05-13 04:13 UTC by tdrachenic

#### What this PR does / why we need it:

I made liveness and readiness probes customizable to make node-exporter features like TLS and Basic-Auth fully available for chart users. When you enable those features in node-exporter configuration then probes crash. To use TLS, we need to change httpGet.scheme to HTTPS and for Basic-Auth we need to add httpHeaders in httpGet.

#### Checklist
- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-13 08:19 UTC, monotek requested changes

2022-05-13 08:19 UTC, monotek commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 3.2.1
```suggestion
version: 3.2.0
```

2022-05-14 01:53 UTC, tdrachenic commented on charts/prometheus-node-exporter/templates/daemonset.yaml
> +              httpHeaders:
It works fine without the "if", with value provided for the httpHeaders and without value. I think, the issue is about the convention which you want to have in the project, so I left this decision to you.

2022-05-22 23:02 UTC, monotek approved these changes

2022-05-22 23:04 UTC, monotek requested changes
Please fix CI error

2022-05-22 23:44 UTC, zanhsieh requested changes

2022-05-22 23:44 UTC, zanhsieh commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 3.2.0
3.2.1 for now

2022-05-23 19:58 UTC, tdrachenic commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 3.2.0
done

2022-05-26 06:25 UTC, zanhsieh approved these changes

2022-05-26 13:23 UTC, monotek requested changes

2022-05-26 13:23 UTC, monotek commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 3.2.1
new feature should raise minor version

```suggestion
version: 3.3.0
```

2022-05-26 21:24 UTC, tomasz-drachenberg commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 3.2.1
done

2022-05-26 21:25 UTC, tdrachenic commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 3.2.1
done

2022-05-26 21:48 UTC, monotek approved these changes

2022-05-26 21:48 UTC, merged