[prometheus-adapter] remove default rules which are causing resource spikes
prometheus-community/helm-charts pull request #2059
Opened 2022-05-14 10:35 UTC by junaid-ali

#### What this PR does / why we need it:

The default rules as described in this issue #2052 causing spikes in CPU and particularly for memory as the cluster grows. The metrics fetched due to those rules doesn't seem to be much related/needed for prometheus adapter. We essentially would only need resource rules, alongside any custom metrics. This PR removes those default rules from adapter chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #2052 

#### Special notes for your reviewer:

`kubectl` top pods/nodes alongside any HPA that depends on custom metrics are working as expected.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-15 17:49 UTC, monotek requested changes
Why not setting rules.default to false and using custom rules if the default does not fit your needs?

Like this it introduces a breaking change for no reason.

2022-05-16 01:06 UTC, junaid-ali commented
@monotek thanks for the review. I should have created the change as draft since I wanted to get feedback for those default rules first.

Currently, I'm using `rules.default: false` but IMO we should have those disabled by default (or removed if not needed) since at some point those rules will cause issues for everyone. Could you please suggest a way to do that without introducing a breaking change?

2022-05-17 10:32 UTC, monotek commented
There is no way to do it without a new major version.
As it's already configurable i don't see the need for it.

2022-05-17 10:54 UTC, junaid-ali commented
@monotek what about if we change the default value to `false`. I assume that wouldn't bring in any breaking change.

2022-05-17 10:56 UTC, junaid-ali commented
My confusion is whether those metrics are really required for prometheus-adapter, if not: at least disable those by default.

2022-05-21 13:15 UTC, monotek commented
You can't change an existing value without makin it a breaking change.
If somebody has installed it before and relies on the default it would change, which is bad.

2022-05-21 15:19 UTC, steven-sheehy commented
I agree with @monotek. You can just set it to false for your deployments.

2022-05-23 08:42 UTC, junaid-ali commented
I do agree that it's a major change (don't think it would be a breaking change since that means a failure/issues to existing deployments).

Do you think we should have it documented at least in the values.yaml or README.md?

2022-05-27 14:04 UTC, monotek commented
why change it at all if it's already configurable?

2022-07-12 03:48 UTC, closed without merging