[kube-prometheus-stack] fix ServiceMonitor for kubelet over http
prometheus-community/helm-charts pull request #2072
Opened 2022-05-18 02:49 UTC by r0bj

#### What this PR does / why we need it:
Fix ServiceMonitor for kubelet over http by adding missing endpoint for path `/metrics/probes`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #2070

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-27 14:28 UTC, monotek requested changes

2022-05-27 14:28 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 35.4.0
```suggestion
version: 35.5.0
```

2022-06-07 01:32 UTC, zanhsieh approved these changes

2022-06-10 22:25 UTC, monotek approved these changes

2022-06-10 22:25 UTC, merged