[kube-prometheus-stack] Add missing fields to prometheus and alertmanager
prometheus-community/helm-charts pull request #208
Opened 2020-10-13 15:25 UTC by bashofmann

#### What this PR does / why we need it:
I went through the api specs of prometheus-operator 0.42.1 and added all the missing fields to the Prometheus and Alertmanager resources that I could find.

See https://github.com/prometheus-operator/prometheus-operator/blob/v0.42.1/Documentation/api.md

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-10-13 19:53 UTC, bashofmann commented
Rebased and changed it to a minor version bump.

2020-12-02 16:31 UTC, bashofmann commented
Rebased. @monotek is there something else that blocks merging this?

2020-12-04 01:16 UTC, monotek requested changes
Please update version again.

I cant merge your pr, as I'm not one of the maintainers of the chart.

2020-12-05 10:34 UTC, monotek approved these changes

2020-12-07 08:37 UTC, gkarthiks approved these changes

2020-12-07 08:41 UTC, merged