[prometheus-elasticsearch-exporter] allow configuration of deployment labels
prometheus-community/helm-charts pull request #2085
Opened 2022-05-24 09:49 UTC by FIIRLEBR

#### What this PR does / why we need it:

Allows configuration of deployment labels.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-27 13:58 UTC, monotek requested changes
value should aslo be reflected in values.yaml

2022-05-27 13:58 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.12.1
new feature shoudl raise minor version.
```suggestion
version: 4.13.0
```

2022-06-10 14:06 UTC, monotek requested changes

2022-06-10 14:06 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
> +{{- if .Values.deployment.labels }}
the variable should also be reflected in values.yaml

2022-07-11 09:02 UTC, monotek requested changes
The rules are genrated by the files in the hack directory, which downloads them.
Please fix upstream.

2022-08-09 07:01 UTC, monotek requested changes

2022-08-09 07:01 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.14.1
New feature should raise minor version

2022-08-09 09:40 UTC, zanhsieh commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.14.1
```suggestion
version: 4.15.0
```

2022-08-19 09:02 UTC, monotek requested changes
Please rebase to fix dco. You might need to squash the online commit.

2022-09-20 21:47 UTC, zanhsieh approved these changes

2022-09-21 10:47 UTC, monotek approved these changes

2022-09-21 10:47 UTC, merged