[alertmanager] - Upgrade pdb version to apiVersion: policy/v1
prometheus-community/helm-charts pull request #2095
Opened 2022-05-27 01:54 UTC by haijun2022

Signed-off-by: Zhang, Henry <Haijun.Zhang@fmr.com>

#### What this PR does / why we need it:
The policy/v1beta1 API version of PodDisruptionBudget will no longer be served in v1.25.
Migrate manifests and API clients to use the policy/v1 API version, available since v1.21.

#### Which issue this PR fixes
  - fixes #1967 

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-05-27 13:45 UTC, monotek requested changes
chart version has to be raised...

2022-05-28 13:57 UTC, haijun2022 commented
> chart version has to be raised...

Thanks for the comments, fixed!

2022-05-29 08:52 UTC, monotek requested changes

2022-05-29 08:52 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 0.19.0
```suggestion
version: 0.18.1
```

2022-05-30 08:21 UTC, monotek requested changes
Soory, it had to be 0.18.2

2022-05-30 08:51 UTC, haijun2022 commented
> 

no worries, I am going to update it now, thank you for your quick review.

2022-05-30 10:39 UTC, monotek requested changes
can you please rebase too / fix the linting errors

2022-06-17 01:25 UTC, closed without merging