[prometheus-mongodb-exporter] - Added podLabels
prometheus-community/helm-charts pull request #2105
Opened 2022-06-01 09:04 UTC by barisik

Signed-off-by: Bilovus, Ihor <ihor.bilovus@outlook.com>

#### What this PR does / why we need it:
In order to add additional labels to pod one can provide podLabels

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-06-01 09:25 UTC, monotek requested changes

2022-06-01 09:25 UTC, monotek commented on charts/prometheus-mongodb-exporter/Chart.yaml
> +version: 2.9.1
new feature should raise minor version

2022-06-01 09:37 UTC, barisik commented on charts/prometheus-mongodb-exporter/Chart.yaml
> +version: 2.9.1
updated

2022-06-01 12:54 UTC, monotek submitted a review, later dismissed

2022-06-01 14:37 UTC, steven-sheehy submitted a review, later dismissed

2022-06-01 19:08 UTC, monotek reviewed
Not sure why the dco check not runs.
Could you rebase please?

2022-06-02 07:12 UTC, monotek approved these changes

2022-06-02 07:12 UTC, merged