[kube-prometheus-stack] dynamic endpoint configuration according to k8s version
prometheus-community/helm-charts pull request #2121
Opened 2022-06-06 10:53 UTC by jabbors

#### What this PR does / why we need it:

Dynamically configures the port for kube-controller-manager and
kube-scheduler endpoints according to targeted k8s version.

#### Which issue this PR fixes
- fixes #2079

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-06-10 14:25 UTC, monotek requested changes

2022-06-10 14:25 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 35.5.2
```suggestion
version: 35.5.3
```

2022-06-16 06:17 UTC, jabbors commented
Thanks for keeping the PR up-to-date. Is there anything I can do to speed up an approval and merge?

2022-06-16 07:21 UTC, monotek requested changes
seems to be oboslte as https://github.com/prometheus-community/helm-charts/pull/2162 was merged

2022-06-16 08:10 UTC, jabbors commented
yeah, then we can close this PR

2022-06-16 08:10 UTC, closed without merging