[prometheus-blackbox-exporter] Bugfix: additionalRelabeling was appen…
prometheus-community/helm-charts pull request #2179
Opened 2022-06-20 15:27 UTC by schmiddim

…ded to metricRelabelings instead of relabelings

#### What this PR does / why we need it:
The List additionalRelabeling was appended to metricRelabelings in the ServiceMonitor Configuration.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
@desaintmartin @gianrubio @rsotnychenko @monotek  I've bumped the major version because the PR will break current Setups
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-03 01:35 UTC, zanhsieh submitted a review, later dismissed

2022-07-08 09:15 UTC, monotek requested changes
please commit suggestion. there is no "helm Repository" command.

2022-07-08 16:55 UTC, schmiddim reviewed
Readme update

2022-07-11 09:03 UTC, monotek approved these changes

2022-07-11 09:04 UTC, merged