Update metric relabel values
prometheus-community/helm-charts pull request #2197
Opened 2022-06-27 16:32 UTC by SuperQ

#### What this PR does / why we need it:

Add some default metric relabel config values to cAdvisor and apiserver
configuration to reduce default cardinality. This will likely save a
couple hundred MiB of memory off Prometheus in the default
configuration.

#### Which issue this PR fixes

Fixes: https://github.com/prometheus-community/helm-charts/issues/2133

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-08 09:21 UTC, monotek requested changes
this changes the defaults and is therefore a breaking change.
not sure if necessarily needed if its already configurable.

2022-07-08 09:57 UTC, SuperQ commented
The problem is that the current defaults are very bad for most users. Users with lower resources have a hard time deploying kube-prometheu-stack due to the amount of memory consumed.

The metrics being removed are also quite useless.
* Excessive high cardinality in the API server metrics provide no value, but upstream Kubernetes is not really fixing this.
* Many of the cAdvisor metrics produce no data (all zeros) or are overlapping / low value.

2022-07-08 12:41 UTC, monotek commented
Still possible somebody is using / relying on it.
Maybe it could be implemented as option or as comment?

2022-07-08 15:06 UTC, monotek commented
If so major version needs to be raised and some notes added to the upgrading section.
I would like to see some other reviews from the cart maintainers too.

2022-07-11 14:55 UTC, monotek requested changes

2022-07-12 17:39 UTC, merged