[prometheus-cloudwatch-exporter] Allow Helm variables in config
prometheus-community/helm-charts pull request #220
Opened 2020-10-16 08:43 UTC by rsotnychenko

Signed-off-by: Rostyslav Sotnychenko <me@sota.sh>

#### What this PR does / why we need it:
One might want to collect the exact same set of metrics in different environments, with a difference only in tag filter value (`aws_tag_select.tag_selections.someLabel=XXXX`).
Given that definition of what metrics to collect takes most of the configuration file, it's handy to have an ability to change a single variable instead of overwritten the whole config from scratch. 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-10-16 14:31 UTC, monotek requested changes
Maybe a hint in the values.yaml that the variable is templated would be nice.

2020-10-19 08:53 UTC, rsotnychenko commented
@monotek readme for this chart does not contain any information regarding chart's variables, but a link to `values.yaml`. So I added the note directly into `values.yaml`

2020-10-19 12:37 UTC, torstenwalter commented on charts/prometheus-cloudwatch-exporter/templates/configmap.yaml
> +{{ tpl .Values.config . | indent 4 }}
```suggestion
    {{ tpl .Values.config . | nindent 4 }}
```

2020-10-20 13:12 UTC, rsotnychenko commented on charts/prometheus-cloudwatch-exporter/templates/configmap.yaml
> +{{ tpl .Values.config . | indent 4 }}
@torstenwalter that is done.

2020-10-20 14:05 UTC, torstenwalter approved these changes

2020-10-20 14:06 UTC, torstenwalter commented
@monotek For me this looks good now. You requested changes earlier on. I think those are already implemented. Could you approve and merge?

2020-10-20 22:05 UTC, monotek approved these changes

2020-10-20 22:06 UTC, merged