[prometheus-node-exporter] Update labels to match best practices
prometheus-community/helm-charts pull request #2212
Opened 2022-06-29 12:47 UTC by QuentinBisson

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

This PR updates the node exporter labels to match the best practice described here: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-06-29 12:49 UTC, monotek requested changes
This is a breaking change for users which already have installed an older version.
So upgradepath has to be defined and documented.

2022-06-29 12:52 UTC, QuentinBisson commented
@monotek do we have an example I could use as I think it's not the first time this happened in this repo ? :D

2022-06-29 13:05 UTC, QuentinBisson commented
I found an example for the stackdriver exporter that exactly matches what I needed :)

2022-06-29 14:05 UTC, QuentinBisson commented
@monotek what do you think about this one ?

2022-06-29 22:48 UTC, zanhsieh approved these changes

2022-07-08 09:14 UTC, monotek requested changes
Please try the upgrade out at least once and fix the readme regarding to the errors you'll find.

2022-07-11 13:04 UTC, QuentinBisson commented
@monotek I will try the upgrade but the readme was changed https://github.com/prometheus-community/helm-charts/pull/2212/commits/af533d6fd5765b143dcbd70dc50667dfdfe80b23

2022-07-27 16:05 UTC, zanhsieh submitted a review, later dismissed

2022-07-27 16:34 UTC, mrueg submitted a review, later dismissed

2022-08-14 18:03 UTC, mrueg commented
@monotek looks like I can't see your review in this one. Anything that it still open from your side here?

2022-08-15 07:52 UTC, monotek commented
Yes, my posted suggestion. Not the deployment but the deaminset has to be deleted.

2022-08-15 07:54 UTC, mrueg commented on charts/prometheus-node-exporter/README.md
> +kubectl delete daemonset -l app=prometheus-node-exporter
@monotek looks like the suggestion here is to delete the daemonset now, am I missing anything?

2022-08-20 05:57 UTC, monotek requested changes
Please rebase and fix readme.

2022-08-22 08:32 UTC, QuentinBisson commented
@monotek the readme is fixed

2022-08-22 08:33 UTC, QuentinBisson commented on charts/prometheus-node-exporter/README.md
> +Starting from version 4.0.0, the `node exporter` chart is using the [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). Therefore you ha
The command is just below :)

2022-08-22 09:50 UTC, monotek requested changes

2022-08-22 09:50 UTC, monotek commented on charts/prometheus-node-exporter/README.md
> +This chart bootstraps a prometheus [`Node Exporter`](http://github.com/prometheus/node_exporter) deployment on a [Kubernetes](http://kubernetes.io) cluster using the [Helm](https://helm.sh) package m
```suggestion
This chart bootstraps a prometheus [`Node Exporter`](http://github.com/prometheus/node_exporter) daemonset on a [Kubernetes](http://kubernetes.io) cluster using the [Helm](https://helm.sh) package manager.
```

2022-08-22 09:54 UTC, monotek requested changes
Servicemonitor Labels need to be changed too

2022-08-22 12:45 UTC, QuentinBisson commented
I signed off your commit but this should be fine now, sorry about all those missed parts :(

2022-08-22 21:08 UTC, monotek approved these changes

2022-08-22 21:09 UTC, merged