[kube-prometrheus-stack] fix: rename thanos sidecar servicemonitor
prometheus-community/helm-charts pull request #2216
Opened 2022-06-30 17:45 UTC by aslafy-z

Signed-off-by: Zadkiel Aharonian <zadkiel_aharonian@carrefour.com>

#### What this PR does / why we need it:

Renames the sidecar thanos ServiceMonitor from `{fullname}-thanos-discovery` to `{fullname}-thanos-sidecar`.
This would make the official Thanos Sidecar grafana dashboard work out of the box with this implementation. See https://github.com/thanos-io/thanos/blob/v0.25.2/examples/dashboards/sidecar.json#L1462. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-01 08:05 UTC, monotek requested changes

2022-07-01 08:05 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 36.3.0
```suggestion
version: 36.2.1
```

2022-07-01 08:07 UTC, aslafy-z commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 36.3.0
You're right. Done!

2022-07-01 09:22 UTC, monotek approved these changes

2022-07-01 09:32 UTC, merged

2022-07-06 14:02 UTC, rouke-broersma commented
@monotek @aslafy-z maybe I'm missing something here but if the servicemonitor is changed but the thanos sidecar service is not, how is this change supposed to work? Seems to me there is now a disconnect between the thanos sidecar service and the servicemonitor since the service name is still discovery instead of sidecar.

2022-07-06 17:44 UTC, rouke-broersma commented
> @rouke-broersma The ServiceMonitor name has no need to match the Service name. If the selector is well defined, it should not cause any issues AFAIK

But the service label is still thanos-discovery, it does not match with the new selector thanos-sidecar in the servicemonitor.

2022-07-06 17:48 UTC, aslafy-z commented
@rouke-broersma I just opened https://github.com/prometheus-community/helm-charts/pull/2244 to fix the issue. Sorry for the noise!