[kube-prometheus-stack] support additional labels on exporters servicemonitors
prometheus-community/helm-charts pull request #2219
Opened 2022-07-01 22:07 UTC by marquezika

#### What this PR does / why we need it:

This MR adds support to define additional labels on exporters' `servicemonitors`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-05 09:33 UTC, monotek requested changes
Not sure if this is realy needed as we already can define commonlabels: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L62

2022-07-05 12:50 UTC, marquezika commented
> Not sure if this is realy needed as we already can define commonlabels: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L62

commonlabels will add labels to all objects, right?

2022-07-05 13:08 UTC, nlamirault commented
@monotek these labels are only for the Prometheus Operator CRD (ServiceMonitor, PodMonitor, PrometheusRule). Not all resources like `commonLabels`

2022-07-08 09:17 UTC, monotek commented
So why not adding commonlabels where they are missing?

2022-07-08 19:19 UTC, marquezika commented
My bad (sorry), I didn't explain the motivation... today I have a single prometheus instance scraping metrics from a "monitoring" namespace. However, kubelet is generating too many metrics (more than 3M series). So, I need to create prometheus' shards to scrape some components individually through `serviceMonitorSelector`  - `commonlabels` won't work for my case.

2022-07-14 08:15 UTC, monotek requested changes

2022-07-14 08:15 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 37.2.1
new feature should raise minor version
```suggestion
version: 37.3.0
```

2022-07-20 18:07 UTC, monotek approved these changes

2022-07-20 18:11 UTC, merged