[kube-prometheus-stack]: Add objectStorageConfig for thanos-ruler
prometheus-community/helm-charts pull request #2232
Opened 2022-07-05 20:46 UTC by daniel-maganto

#### What this PR does / why we need it:
This PR adds support for `objectStorageConfig` on thanos-ruler template
#### Which issue this PR fixes
  - fixes #2226 

#### Special notes for your reviewer:

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-05 21:17 UTC, monotek requested changes
Please fix linting error

2022-07-06 05:56 UTC, daniel-maganto commented
> Please fix linting error

done @monotek

2022-07-06 06:14 UTC, daniel-maganto commented
Sorry again, @monotek , I think now is completely fine

2022-07-08 09:03 UTC, monotek approved these changes

2022-07-08 09:03 UTC, merged