Setting a custom timeout in admission mutatingWebhookConfiguration - Prometheus Operator chart Template
prometheus-community/helm-charts pull request #2233
Opened 2022-07-05 21:47 UTC by stazdx

#### What this PR does / why we need it:

We need to set `timeoutSecond` in helm template for admission MutatingWebhookConfiguration in Prometheus Operator

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #2020,#1041

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-06 12:28 UTC, monotek requested changes
Please sign your commits and raise minor chart verion.

Is 10 seconds the current value/default?

2022-08-21 06:17 UTC, monotek requested changes

2022-08-21 06:17 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 36.6.2
```suggestion
version: 39.9.0
```

2022-08-21 06:40 UTC, monotek approved these changes

2022-08-21 06:40 UTC, merged

2023-03-01 19:41 UTC, halradaideh commented
the timeout is not enough, even with 30s

the hook is being terminated before the pods become up

```
helm upgrade -i --create-namespace prometheus-operator -n prometheus-operator prometheus-community/kube-prometheus-stack -f values-prom.yaml
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://prometheus-operator-kube-m-operator.prometheus-operator.svc:443/admission-prometheusrules/mutate?timeout=30s": no endpoints available for service "prometheus-operator-kube-m-operator"
```

I think same as in here https://github.com/prometheus-community/helm-charts/issues/3074