[kube-prometheus-stack] Fix/yaml error tag yaml 2002 value
prometheus-community/helm-charts pull request #2238
Opened 2022-07-06 12:37 UTC by Moep90

@andrewgkew
@bismarck
@gianrubio

#### What this PR does / why we need it:
This will fix a pyaml issue which causes the equal sign to throw a `could not determine a constructor for the tag 'tag:yaml.org,2002:value'` error.

2022-07-08 08:36 UTC, monotek requested changes
crds are created automatically by the scripts in the hack dir.
your change would get lost when recreated.
please fix upstream.

2022-07-09 16:52 UTC, zanhsieh commented
Source PR here:

https://github.com/prometheus-operator/prometheus-operator/pull/4897

2022-07-18 12:55 UTC, Moep90 commented
see: https://github.com/yaml/pyyaml/issues/89

2022-09-29 21:24 UTC, dotdc commented
Agree with the previous comments, this should be done directly in [prometheus-operator/prometheus-operator](https://github.com/prometheus-operator/prometheus-operator)
Closing this PR.

2022-09-29 21:24 UTC, closed without merging