[prom-label-proxy] Setup chart
prometheus-community/helm-charts pull request #2269
Opened 2022-07-12 13:45 UTC by jkroepke

#### What this PR does / why we need it:
Helm chart for https://github.com/prometheus-community/prom-label-proxy

#### Which issue this PR fixes
None

#### Special notes for your reviewer:
If chart needs a maintainer, I can take ownership of this.

I tried to follow https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md, but there is no process for new charts.

#### Checklist

- [x]  [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-12 17:37 UTC, monotek requested changes

2022-07-12 17:37 UTC, monotek commented on charts/prom-label-proxy/README.md
> +_See [helm repo](https://helm.sh/docs/helm/helm_repo/) for command documentation._
```suggestion
_See [`helm repo`](https://helm.sh/docs/helm/helm_repo/) for command documentation._
```

2022-07-12 20:23 UTC, jkroepke commented
I used https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway as base for the new README. Looks like the README.md from pushgateway is older than the linter on the workflow.

2022-07-13 08:08 UTC, monotek approved these changes

2022-07-13 08:08 UTC, merged

2022-07-13 08:47 UTC, jkroepke commented
Thanks!