[kube-prometheus-stack]: add labels spec for thanos-ruler
prometheus-community/helm-charts pull request #2270
Opened 2022-07-12 14:46 UTC by daniel-maganto

#### What this PR does / why we need it:
This PR adds support for `labels` on spec for thanos-ruler template
#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-12 17:40 UTC, monotek requested changes

2022-07-12 17:40 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 36.7.0
```suggestion
version: 37.1.0
```

2022-07-12 18:16 UTC, daniel-maganto commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 36.7.0
Fixed

2022-07-13 12:20 UTC, daniel-maganto commented
I already have updated to the next minor version, right now 37.2.0

@monotek when you have time could you take a look. 

Many thanks

2022-07-13 13:26 UTC, monotek approved these changes

2022-07-13 13:27 UTC, monotek commented
Can you please rebase?
I can't add changes to your repo.

2022-07-13 15:26 UTC, merged