[kube-prometheus-stack]: bump grafana version
prometheus-community/helm-charts pull request #2283
Opened 2022-07-18 07:38 UTC by stevo-f3

Signed-off-by: Stevo Slavić <stevo.slavic@form3.tech>

#### What this PR does / why we need it:

Updates grafana chart dependency for security vulnerability fixes, see https://grafana.com/blog/2022/07/14/grafana-v9-0-3-8-5-9-8-4-10-and-8-3-10-released-with-high-severity-security-fix/ and https://github.com/grafana/helm-charts/pull/1606

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-18 08:00 UTC, stevo-f3 commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 37.2.1
Bumping just minor version as by related recent recommendation https://github.com/prometheus-community/helm-charts/pull/2268#discussion_r919240177

2022-07-18 11:35 UTC, stevo-f3 commented
@andrewgkew @bismarck @desaintmartin @gianrubio @gkarthiks @scottrigby @Xtigyro @monotek can you please have a look?

2022-07-20 18:13 UTC, monotek requested changes

2022-07-28 08:29 UTC, monotek approved these changes

2022-07-28 08:29 UTC, merged