[kube-prometheus-stack] add flag to open and close alerts
prometheus-community/helm-charts pull request #2308
Opened 2022-07-26 12:31 UTC by lusson-luo

Signed-off-by: lusson <lusson@foxmail.com>

#### What this PR does / why we need it:
These two alerts are always being sent, there is no bad impact on the business system, so I added a switch to allow it to be turned on or off
support use it without KubeControllerManager and KubeScheduler alerts

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-26 13:01 UTC, monotek requested changes
Rules files are createrd dynamicaly by the scripts in the hack directory.
Your changes will get lost if script is run so you would have to adjust the script.

2022-07-26 13:01 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 38.0.3
new feature should raise minor version.

2022-07-26 14:40 UTC, lusson-luo commented
> Rules files are createrd dynamicaly by the scripts in the hack directory.

i see hack script, it has a template to createrd Rules files. if i adjust script, all rule will change and has alertRule tag, o you approve of this way？
![image](https://user-images.githubusercontent.com/19859400/181035106-475b1b74-a412-4fb8-bfe5-d1c4c905da85.png)

2022-07-27 02:47 UTC, lusson-luo commented
@monotek thanks, i will close this pr, cause i find a config to resolve my question #1173 
i find `defaultRules.disabled.KubeSchedulerDown` can help me , it allow disable any specific alert in prometheusrules

2022-07-27 02:47 UTC, closed without merging

2022-08-30 03:26 UTC, lusson-luo commented
open a new pr https://github.com/prometheus-community/helm-charts/pull/2410