[prometheus] Add support for pvc.spec.volumeName
prometheus-community/helm-charts pull request #2311
Opened 2022-07-27 09:54 UTC by jjaniec

Signed-off-by: Joffrey JANIEC <16088893+jjaniec@users.noreply.github.com>

#### What this PR does / why we need it:

Allow specifying volumeName to PVCs deployed by the prometheus chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-27 14:07 UTC, monotek requested changes

2022-07-27 14:07 UTC, monotek commented on charts/prometheus/Chart.yaml
> +version: 15.10.6
new feature should raise minor version

2022-07-27 15:05 UTC, zanhsieh approved these changes

2022-07-28 08:26 UTC, monotek approved these changes

2022-07-28 08:27 UTC, merged