[kube-prometheus-stack-operator] add securityContext on container level for operator
prometheus-community/helm-charts pull request #2326
Opened 2022-07-29 21:22 UTC by ChrisFraun

his PR is only a small change in the helm chart of **prometheus-operator**.

**What**: Deployments can have security settings in their manifest on two levels: pod and container. However, there are some capabilities only configurable in one of the respective levels(https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#securitycontext-v1-core). This PR sets a default configuration for container securityContext, which denies privilege escalation and drops all POSIX capabilities. These are and should be standard settings in the context of Kubernetes. It also adds the possibility of running prometheus-operator in an Kubernetes environment without PSP (to be removed in v1.25 https://kubernetes.io/docs/concepts/security/pod-security-policy/), but with OpenPolicyAgent (a or possibly the PSP substitute) with the same capabilities as a restricted PSP instead.

**Problem**: There is already a securityContext in the values.yaml, however, this should have entries for pods AND container be be called podSecurityContext since it's on pod level, but it hasn't. To not break backwards compatibility of prometheus-operator, this PR hardcodes the respective capabilities on container level with a new variable calles `containersSecurityContext`.

**Test**: was `helm lint .` and `helm template .`, which both compiled.

Other suggestions are welcome!
Signed-off-by: Christoph Fraundorfer <christoph.fraundorfer@allianzdirect.de>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-07-30 08:14 UTC, monotek requested changes
please raise minor chart version

2022-08-01 06:16 UTC, ChrisFraun commented
Done!

2022-08-01 06:56 UTC, monotek requested changes

2022-08-01 06:56 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.2.0
```suggestion
version: 39.3.0
```

2022-08-01 09:41 UTC, ChrisFraun commented
I just realized that the future is already implemented.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1832-L1834
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L119

2022-08-01 09:45 UTC, ChrisFraun commented
I just realized that the future is already implemented.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1832-L1834
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L119

2022-08-01 09:45 UTC, closed without merging