[prometheus-json-exporter] feat: Implement mounting of additional volumes.
prometheus-community/helm-charts pull request #2352
Opened 2022-08-07 17:48 UTC by fhreichert

Signed-off-by: Felix <mail@freichert.de>

#### What this PR does / why we need it

This allows to mount arbitrary volumes. 
This is needed for including password files for basic auth, that are deployed with e.g. sealed-secrets.

The `additionalVolume` and `additionalVolumeMounts` Values were added.

#### Which issue this PR fixes

_none_

#### Special notes for your reviewer

_none_

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-08-07 18:14 UTC, monotek approved these changes

2022-08-07 18:16 UTC, monotek requested changes
Would you please also update json exporter to the latest version 0.5.0?

2022-08-07 20:36 UTC, fhreichert commented
@monotek The Change from v0.4.0 to v0.5.0 requires a new config-format for json-exporter. I marked the commit as breaking.

If you prefer, I can open a different PR for that.

2022-08-07 22:53 UTC, zanhsieh approved these changes

2022-08-08 06:53 UTC, monotek approved these changes
Lgtm. As the chart is in version 0.x.x I guess we don't need to change major version because of the config change. Let's see what the other chart maintainers think.

2022-08-08 07:44 UTC, merged