[prometheus-statsd-exporter]: parameterize readiness and liveness pro…
prometheus-community/helm-charts pull request #2355
Opened 2022-08-08 18:58 UTC by makeittotop

…bes using `/health` instead of `/metrics` endpoint (#2305)

    
Signed-off-by: Abhishek Pareek <makeittotop@gmail.com>

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #2305 

cc @scDisorder 

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-08-09 07:03 UTC, monotek requested changes

2022-08-09 07:03 UTC, monotek commented on charts/prometheus-statsd-exporter/Chart.yaml
> +version: 0.5.1
New feature should raise minor version.

2022-08-09 09:36 UTC, zanhsieh commented on charts/prometheus-statsd-exporter/Chart.yaml
> +version: 0.5.1
```suggestion
version: 0.6.0
```

2022-08-10 09:42 UTC, monotek approved these changes

2022-08-10 13:52 UTC, merged