feat[kube-state-metrics]: add image sha support for image specified
prometheus-community/helm-charts pull request #2370
Opened 2022-08-15 18:08 UTC by francRang

Signed-off-by: francisco.rangel-heb <rangel.francisco@heb.com>

#### What this PR does / why we need it
This PR adds support for image sha (also called digest) for the image field. This is needed when signed images are used vs regular images with only tag.
#### Which issue this PR fixes

- fixes #2369

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-08-15 19:00 UTC, monotek requested changes

2022-08-15 19:00 UTC, monotek commented on charts/kube-state-metrics/Chart.yaml
> +version: 4.15.1
New feature should raise minor version

2022-08-15 19:48 UTC, francRang commented
@monotek applied suggested changes, let me know if there's anything I missed.

2022-08-16 07:50 UTC, monotek approved these changes

2022-08-16 07:50 UTC, merged