[prometheus-stackdriver-exporter] Fix spec.serviceAccountName
prometheus-community/helm-charts pull request #2378
Opened 2022-08-17 10:41 UTC by tuananhnguyen-ct

Signed-off-by: Tuan Anh Nguyen <tuananh.nguyen-ext@commercetools.de>

#### What this PR does / why we need it
With the serviceAccountName spec missing, helm won't be able to apply the change to deployment when we change the service account name.

Step to reproduce the bug
- Install prometheus-stackdriver-exporter using helm with default setting
  - `helm get manifest` shows `serviceAccount: default`
  - `kubectl get deployment` shows `serviceAccount: default` and `serviceAccountName: default`
- Change serviceAccount.create to true and upgrade the current release. 
  - `helm get manifest` shows  `serviceAccount: ` with new value (generated from release name)
  - `kubectl get deployment` still shows `serviceAccount: default` and `serviceAccountName: default`
 
The correct spec is `serviceAccountName` following https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

And we still need to keep spec.serviceAccount due to https://github.com/kubernetes/kubernetes/issues/72519

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-08-17 11:16 UTC, monotek requested changes

2022-08-17 11:16 UTC, monotek commented on charts/prometheus-stackdriver-exporter/Chart.yaml
> +version: 4.1.0
As this seems only to be a Bugfix:

```suggestion
version: 4.0.1
```

2022-08-18 07:18 UTC, rpahli approved these changes

2022-08-18 09:14 UTC, monotek approved these changes

2022-08-18 09:14 UTC, merged