[prometheus-redis-exporter] support redis password file secret volume mount
prometheus-community/helm-charts pull request #2401
Opened 2022-08-26 18:55 UTC by sat-devopsnow

Signed-off-by: sat-devopsnow <sat@opsverse.io>

#### What this PR does / why we need it

Especially useful when one exporter is scraping multiple targets with different password by [taking advantage of the exporter's `redis.password-file | REDIS_PASSWORD_FILE` options](https://github.com/oliver006/redis_exporter/tree/v1.27.0#command-line-flags)... Details here and in the `Test Results` section:

The Redis exporter [supports metric scraping of multiple redis instances by exposing the `/scrape` endpoint](https://github.com/oliver006/redis_exporter/tree/v1.27.0#prometheus-configuration-to-scrape-multiple-redis-hosts). However, if auth is enabled on those instances (and if each of these instances have different passwords), the only workaround is to run multiple exporters - because only a single password can be passed to the exporter.

This PR utilizes the exporter's `redis.password-file | REDIS_PASSWORD_FILE` options - which allow a password file with multiple redis instances as keys with corresponding password as value: e.g.,https://github.com/oliver006/redis_exporter/blob/v1.27.0/contrib/sample-pwd-file.json

#### Which issue this PR fixes

N/A; addendum to #2199 

#### Special notes for your reviewer

* Please look at `Test Results` for the testing / in action
* As an aside: I feel `appVersion` in Chart.yaml is wrong (it should probably be pointing to the default redis-exporter version in values.yaml, which is 1.27.0) - but that's outside the purview of this specific PR

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

#### Test Results

(1) Create two redis instances on test k8s (v1.21) cluster:

```
helm upgrade --install redis-1 --set global.redis.password=foo --set replica.replicaCount=0 bitnami/redis
helm upgrade --install redis-2 --set global.redis.password=bar --set replica.replicaCount=0 bitnami/redis
```

(2) Create a secret with the password file contents as the key value:

```
kubectl create secret generic redis-auth --from-literal=redis-password-file.json='{"redis://redis-1-master.default.svc.cluster.local:6379": "foo", "redis://redis-2-master.default.svc.cluster.local:6379": "bar"}'
```

(3) Updated values.yaml of redis exporter to enable the password file secret mount:

```
 ...
 auth:
   # Use password authentication
-  enabled: false
+  enabled: true
   # Use existing secret (ignores redisPassword)
   secret:
     name: ""
@@ -162,3 +162,14 @@ auth:
   redisPassword: ""
   # Redis user (version 6.X and above)
   redisUser: ""
+  # Redis password file (e.g., https://github.com/oliver006/redis_exporter/blob/v1.27.0/contrib/sample-pwd-file.json)
+  # secret (useful for multiple redis instances with different passwords). If secret name and key are set
+  # this will ignore the single password auth.secret.*
+  redisPasswordFile:
+    # The secret key will be mounted into this path as a file
+    # e.g., if secret key is pass.json, the env variable
+    # REDIS_PASSWORD_FILE will be set to /auth/pass.json
+    mountPath: /auth
+    secret:
+      name: "redis-auth"
+      key: "redis-password-file.json"
```

(4) Installed this exporter chart and port-forwarded the resulting service

```
helm install test-redexp .
...
kubectl port-forward svc/test-redexp-prometheus-redis-exporter 9121:9121
```

(5) Verified metrics for the 2 instances were coming in (using [the /scrape endpoint for multiple targets](https://github.com/oliver006/redis_exporter/tree/19f7b036bb46869858eec74d8d3fc2186d641399#prometheus-configuration-to-scrape-multiple-redis-hosts)):

```
$ curl -s -XGET http://localhost:9121/scrape?target=redis-1-master.default.svc.cluster.local:6379 | tail -n 1
redis_uptime_in_seconds 3772

$ curl -s -XGET http://localhost:9121/scrape?target=redis-2-master.default.svc.cluster.local:6379 | tail -n 1
redis_uptime_in_seconds 3685
```

(6) Updated the secret with a bad password for redis-2, restarted the exporter pod, and verified showed redis-2 as down:

```
$ curl -s -XGET http://localhost:9121/scrape?target=redis-1-master.default.svc.cluster.local:6379 | tail -n 1
redis_uptime_in_seconds 4841

$ curl -s -XGET http://localhost:9121/scrape?target=redis-2-master.default.svc.cluster.local:6379 | tail -n 1
redis_up 0
```
##### Additional tests

Per contributing guidelines, also ran `ct`:

```
$ ct lint --chart-dirs . --charts .
Linting charts...
Version increment checking disabled.

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 prometheus-redis-exporter => (version: "5.1.0", path: ".")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'prometheus-redis-exporter => (version: "5.1.0", path: ".")'
Validating /<redacted>/helm-charts/charts/prometheus-redis-exporter/Chart.yaml...
Validation success! 👍
Validating maintainers...
==> Linting .
[INFO] Chart.yaml: icon is recommended
[WARNING] templates/podsecuritypolicy.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ prometheus-redis-exporter => (version: "5.1.0", path: ".")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

2022-08-27 01:39 UTC, zanhsieh submitted a review, later dismissed

2022-08-27 16:15 UTC, monotek requested changes

2022-08-27 16:15 UTC, monotek commented on charts/prometheus-redis-exporter/templates/deployment.yaml
> +
Please remove blank line

2022-08-27 16:28 UTC, sat-devopsnow commented on charts/prometheus-redis-exporter/templates/deployment.yaml
> +
Ah, missed this. Pushed update.

2022-08-28 12:18 UTC, monotek approved these changes

2022-08-28 14:28 UTC, zanhsieh approved these changes

2022-08-28 14:28 UTC, merged