[kube-prometheus-stack] add recording and alerting switch to kubeScheduler
prometheus-community/helm-charts pull request #2410
Opened 2022-08-30 03:24 UTC by lusson-luo

Signed-off-by: lusson <lusson@foxmail.com>

#### What this PR does / why we need it
can disabled kubeScheduler alert or record alone, before kubeSchedulerAlert and kubeSchedulerRecord control by one switch kubeScheduler

#### Which issue this PR fixes

according to prs #2308 #2397 

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-01 05:57 UTC, lusson-luo reviewed
finish my review

2022-09-03 10:26 UTC, monotek requested changes
This would require new major version, as an existing config value is changed

2022-09-03 10:27 UTC, monotek requested changes
See also: https://github.com/prometheus-community/helm-charts/pull/2410/files#L3

2022-09-05 02:27 UTC, lusson-luo commented
> First-time contributors need a maintainer to

ok,i upgrade major version to 40.0.0

2022-09-15 13:20 UTC, lusson-luo commented
> See also: https://github.com/prometheus-community/helm-charts/pull/2410/files#L3

@monotek ok,i upgrade major version to 40.0.0

2022-09-16 09:59 UTC, monotek requested changes
Plaese raise version to 41.0.0

Readme needs upgrading instructions.

I would like to do this together with nex prometheus operator update.

2022-09-16 12:06 UTC, lusson-luo commented
> Plaese raise version to 41.0.0
> 
> Readme needs upgrading instructions.
> 
> I would like to do this together with next prometheus operator update.

@monotek ok, thanks
1. i raise version to 41.0.0
2. The original readme no related configuration, so i think don't upgrading Readme.
3. Okay, I'm waiting for other prometheus operator update.

2022-09-16 12:15 UTC, monotek commented
> @monotek ok, thanks
> 

> 2. The original readme no related configuration, so i think don't upgrading Readme.

All major versions need an entry in the updating section, describing whats changed and what to do to get old behaviour.

2022-09-16 12:52 UTC, lusson-luo commented
> > @monotek ok, thanks
> 
> > 2. The original readme no related configuration, so i think don't upgrading Readme.
> 
> All major versions need an entry in the updating section, describing whats changed and what to do to get old behaviour.

understand, i add major versions updating section in readme

2022-09-16 12:56 UTC, monotek requested changes

2022-09-16 12:56 UTC, monotek commented on charts/kube-prometheus-stack/README.md
> +### From 40.x to 41.x
```suggestion
### From 40.x to 41.x

```

2022-09-17 01:55 UTC, lusson-luo commented on charts/kube-prometheus-stack/README.md
> +### From 40.x to 41.x
i add space line

2022-09-17 09:18 UTC, lusson-luo commented
@monotek readme has add empty line

2022-10-11 11:27 UTC, monotek approved these changes

2022-10-11 11:46 UTC, merged