[kube-prometheus-stack]
prometheus-community/helm-charts pull request #2411
Opened 2022-08-30 07:01 UTC by moroviintaas

[kube-prometheus-stack]
* Hint for replacing image sources for containers:
	- grafana
	- sidecar
	- kube-state-metrics
	- prometheus-node-exporter

Signed-off-by: moroviintaas <moroviintaas@gmail.com>

[kube-prometheus-stack]

* Bump chart version

Signed-off-by: moroviintaas <moroviintaas@gmail.com>

#### What this PR does / why we need it

I was deploying kube-prometheus-stack on offline environment with internal image registry. I have created own values.yml file with changed image sources pointing to my registry. Yet some images failed to be pulled, as they had been defined in dependency charts. Maybe it is worth to note that default grafana image tag (in dependency chart) is currently set to "", which should resolve to "latest" as far as I know and potentially lead to stability issue.   

This PR does not change chart behavior, only adds comment hints on where I had to insert my registry paths in kube-prometheus-stack values.yml file in order to set up containers. It may save some time of digging for other offline deployers.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-08-30 13:48 UTC, Xtigyro requested changes
Thanks for the contribution, @moroviintaas! 🥇

Could you please bump the minor (and not the bugfix) chart version in `Chart.yaml`?

2022-08-30 14:53 UTC, monotek submitted a review, later dismissed
I don't think that's needed as the defaults are used anyway. Values file is already big enough.

2022-08-30 15:02 UTC, Xtigyro commented
> I don't think that's needed as the defaults are used anyway. Values file is already big enough.

@monotek We do that for other components too. I think it's a good practice.

2022-08-30 15:21 UTC, moroviintaas commented
> Thanks for the contribution, @moroviintaas! 🥇
> 
> Could you please bump the minor (and not the bugfix) chart version in `Chart.yaml`?

Done in replace commit [9ceee96](https://github.com/prometheus-community/helm-charts/commit/9ceee968f9375f8f73f1b75bc68bbceda3b517d2)

2022-08-30 15:39 UTC, moroviintaas commented
> I don't think that's needed as the defaults are used anyway. Values file is already big enough.

In most cases it works well, however when I needed to change image sources (offline deployment), I firstly changed only these visible in this file and deployment failed. Components [prometheus-node-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter) and [kube-state-metrics](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics) are managed in this very repository so in online it is ok. However sidecar's and grafana's image is defaulted in external repository [grafana/helm-charts](https://github.com/grafana/helm-charts), with sidecar tagged properly and grafana not tagged (resolving to latest). However I am new to Kubernetes and Helm so I might be wrong.

2022-08-30 19:53 UTC, Xtigyro approved these changes

2022-08-31 06:09 UTC, merged

2022-09-03 05:52 UTC, monotek commented
@Xtigyro imho Bugfix version would have been right, as no new features have been added.