[kube-prometheus-stack] Fix variable WalCompression
prometheus-community/helm-charts pull request #2412
Opened 2022-08-30 08:39 UTC by vzemtsov

Signed-off-by: Zemtsov Vladimir <vl.zemtsov@gmail.com>

#### What this PR does / why we need it
`walCompression` - bool variable
In helm construction:
```
{{- if .Values.prometheus.prometheusSpec.walCompression }}
  walCompression: {{ .Values.prometheus.prometheusSpec.walCompression }}
{{- end }}
```
If walCompression = true, in CRD Prometheus added:
```
walCompression: true
```
if walCompression = false, IF in helm don't add walCompression field to CRD, and Prometheus used default - TRUE

Doesn't matter what you set to `walCompression` variable in helm, WalCompression always be enable in Prometheus.

I fix it.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-12 15:28 UTC, monotek requested changes
is this now enabled by default?
whats the default if it's not defined in the current version?
please update version.

2022-09-13 06:04 UTC, vzemtsov commented
> is this now enabled by default? whats the default if it's not defined in the current version? please update version.

In the current version variable `walCompression` set to `false` by default, but Wal Compression enable!

If `walCompression` not defined, [Prometheus enable Wal Compression](https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects). (`This flag was introduced in 2.11.0 and enabled by default in 2.20.0`)

2022-09-13 09:16 UTC, monotek requested changes
please update chart version

2022-09-13 09:56 UTC, monotek requested changes
please rebase with current main so the changes to other charts are removed

2022-09-13 10:05 UTC, monotek requested changes
chjart.yaml needs version bump.

2022-09-13 11:20 UTC, vzemtsov commented
All ok?

2022-09-13 12:47 UTC, zanhsieh approved these changes

2022-09-13 13:58 UTC, monotek approved these changes

2022-09-13 13:58 UTC, merged