[prometheus-json-exporter] open service configuration
prometheus-community/helm-charts pull request #2414
Opened 2022-08-31 03:13 UTC by gitgaoxiang

Signed-off-by: gaoxiang <gao_xiang@126.com>

#### What this PR does / why we need it
open service configuration

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-08-31 04:53 UTC, monotek requested changes

2022-08-31 04:53 UTC, monotek commented on charts/prometheus-json-exporter/Chart.yaml
> +version: 0.3.1
New feature should raise minor version.

2022-08-31 05:46 UTC, gitgaoxiang commented on charts/prometheus-json-exporter/Chart.yaml
> +version: 0.3.1
have changed

2022-09-01 11:35 UTC, zanhsieh approved these changes

2022-09-03 07:17 UTC, monotek approved these changes

2022-09-03 07:17 UTC, merged