[kube-prometheus-stack] Add template to storage configurations
prometheus-community/helm-charts pull request #2415
Opened 2022-08-31 14:21 UTC by nhudson

Signed-off-by: Nick Hudson <nick.hudson@gmail.com>

#### What this PR does / why we need it

Adds the `tpl` function around the `storageSpec` configuration in prometheus templates and `storage` configuration in the alertmanager templates.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-14 09:36 UTC, monotek requested changes

2022-09-14 09:36 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.0
```suggestion
version: 40.1.0
```

2022-09-14 12:54 UTC, nhudson commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.0
Thanks.  Updated

2022-09-14 16:34 UTC, monotek requested changes

2022-09-14 16:34 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 40.1.0
```suggestion
version: 40.0.1
```

2022-09-14 16:34 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 40.1.0
sorry, typo...

2022-09-14 21:21 UTC, nhudson commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 40.1.0
ha no worries.  Fixed!

2022-09-16 08:56 UTC, monotek requested changes

2022-09-16 08:56 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 40.0.1
```suggestion
version: 40.0.2
```

2022-09-16 09:04 UTC, monotek approved these changes

2022-09-16 09:04 UTC, merged