[kube-state-metrics] Bump kube-state-metrics version
prometheus-community/helm-charts pull request #2422
Opened 2022-09-02 07:27 UTC by chrischdi

#### What this PR does / why we need it

Bumps the version of the referenced kube-state-metrics image to the latest released version v2.6.0.

#### Which issue this PR fixes

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-02 11:29 UTC, dotdc requested changes
LGTM, just revert the change in `charts/kube-prometheus-stack/values.yaml` and we can merge.

2022-09-02 11:29 UTC, dotdc commented on charts/kube-prometheus-stack/values.yaml
> -  #  tag: v2.5.0
This should be done in a separate pull request for kube-prometheus-stack. It will also require a version bump.

2022-09-03 05:47 UTC, monotek requested changes
Please remove kube Prometheus stack changes

2022-09-03 10:44 UTC, chrischdi commented
Removed the Prometheus Stack changes 😊

2022-09-03 12:15 UTC, monotek approved these changes

2022-09-04 18:38 UTC, dotdc approved these changes
LGTM

2022-09-04 18:39 UTC, merged

2022-09-04 18:40 UTC, dotdc commented
Thank you for your contribution @chrischdi !