[kube-prometheus-stack]  Add support for templating in excludedFromEnforcement parameter
prometheus-community/helm-charts pull request #2429
Opened 2022-09-05 08:19 UTC by amuraru

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-08 18:02 UTC, Allex1 commented
@monotek @andrewgkew @desaintmartin @gianrubio @gkarthiks @scottrigby @Xtigyro please have a look

2022-09-13 09:55 UTC, monotek requested changes

2022-09-13 09:55 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.1
```suggestion
version: 39.13.2
```

please merge after: https://github.com/prometheus-community/helm-charts/pull/2430#pullrequestreview-1105487003 which has version 39.13.1

2022-09-13 11:04 UTC, amuraru commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.1
Done

2022-09-13 13:59 UTC, monotek requested changes

2022-09-13 13:59 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.13.2
```suggestion
version: 39.13.3
```

2022-09-13 15:52 UTC, monotek approved these changes

2022-09-13 15:56 UTC, merged