[kube-prometheus-stack] - Add support for templating in additionalAle…
prometheus-community/helm-charts pull request #2430
Opened 2022-09-05 11:06 UTC by Allex1

…rtManagerConfigs

Signed-off-by: birca <Allex21ro@yahoo.com>

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-08 18:02 UTC, Allex1 commented
@monotek @andrewgkew @desaintmartin @gianrubio @gkarthiks @scottrigby @Xtigyro please have a look

2022-09-13 09:54 UTC, monotek requested changes

2022-09-13 09:54 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.1
```suggestion
version: 39.13.1
```

2022-09-13 10:58 UTC, Allex1 commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.1
done

2022-09-13 13:59 UTC, monotek requested changes

2022-09-13 13:59 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.13.1
```suggestion
version: 39.13.2
```

2022-09-13 14:05 UTC, Allex1 commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.13.1
@monotek done

2022-09-13 15:51 UTC, monotek approved these changes

2022-09-13 15:52 UTC, merged