bump grafana 6.35.0 (9.1.1)
prometheus-community/helm-charts pull request #2431
Opened 2022-09-05 14:43 UTC by andrejshapal

Signed-off-by: andrejshapal <96792836+andrejshapal@users.noreply.github.com>

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-05 14:44 UTC, andrejshapal commented
Hello, 
Really sorry if I did something wrong. Just looked in previous similar prs how grafana is getting bumped and tried to do the same.

2022-09-08 08:15 UTC, monotek requested changes
Please raise chart version too

2022-09-08 18:04 UTC, Allex1 commented
@andrejshapal you need to update the dependencies in Chart.yaml and then do a `helm dep update` in order for the Chart.lock to get updated. Can you please update the Grafana to latest ? 6.37.*

2022-09-08 20:23 UTC, andrejshapal commented
> @andrejshapal you need to update the dependencies in Chart.yaml and then do a `helm dep update` in order for the Chart.lock to get updated. Can you please update the Grafana to latest ? 6.37.*

Thank you. Have updated version in chart.yaml and run `helm dep update`.

2022-09-08 22:28 UTC, andrejshapal commented
If I understand correctly from the error was in lint test "Chart is not ok. Need to bump version", it was due to chart version was not changed. The last commit is correct?

2022-09-08 23:32 UTC, zanhsieh commented
@andrejshapal 
I would suggest you bump to Grafana chart version: 6.37.1 appVersion: 9.1.2 due to CVE:

https://grafana.com/blog/2022/08/30/security-release-new-versions-of-grafana-and-grafana-image-renderer-with-a-high-severity-security-fix-for-cve-2022-31176/

2022-09-08 23:38 UTC, andrejshapal commented
@zanhsieh Bumped to this one, will update title.

2022-09-09 07:39 UTC, andrejshapal reviewed
@monotek Should not you review this?

2022-09-09 07:44 UTC, Allex1 commented
Maybe we should split this pr in 2: 
- 1 for the kube-prometheus-stack version bumps which should also include kube-state-metrics dependencies bumps
- 1 for kube-state-metrics bumps.

2022-09-09 08:04 UTC, dotdc requested changes

2022-09-09 08:04 UTC, dotdc commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 39.11.1
This should be 39.12.0 because you bump minors in both sub charts.

2022-09-09 08:35 UTC, andrejshapal commented
> Maybe we should split this pr per chart:
> 
> * 1 for the kube-prometheus-stack version bumps which should also include kube-state-metrics dependencies bumps
> * 1 for kube-state-metrics bumps.

You mean one pr for grafana and one for  kube-state-metrics? Or I did not get it.

2022-09-09 08:50 UTC, dotdc commented
> > Maybe we should split this pr per chart:
> > 
> > * 1 for the kube-prometheus-stack version bumps which should also include kube-state-metrics dependencies bumps
> > * 1 for kube-state-metrics bumps.
> 
> You mean one pr for grafana and one for kube-state-metrics? Or I did not get it.

Just checked, only the change for `kube-prometheus-stack` is needed. 
You just need to drop your changes in `kube-state-metrics` in this PR because the chart is already updated: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/Chart.yaml

2022-09-09 08:59 UTC, dotdc commented
@andrejshapal You delete the entire files in https://github.com/prometheus-community/helm-charts/pull/2431/commits/39954a859d08b67c1b387dae99f9e4fab6dc8106 and https://github.com/prometheus-community/helm-charts/pull/2431/commits/0f156a47adb92dd0725f61ef4803ce296ef70058, this is not good, just revert your changes.

2022-09-09 09:00 UTC, andrejshapal commented
@dotdc Yeah, I already searching revert button)

2022-09-09 09:16 UTC, dotdc commented
The code seems good now, you just need to have the DCO right: 
- https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md
- https://github.com/prometheus-community/helm-charts/pull/2431/checks?check_run_id=8266798972

2022-09-09 09:22 UTC, andrejshapal commented
> The code seems good now, you just need to have the DCO right:
> 
> * https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md
> * https://github.com/prometheus-community/helm-charts/pull/2431/checks?check_run_id=8266798972

Yep, a bit messy, but fixed it in the end of the end.

2022-09-09 09:31 UTC, dotdc commented
Not a big deal because it will be squash in the end, but it's generally better if you do it in your branch :wink:

2022-09-09 09:35 UTC, dotdc approved these changes

2022-09-09 09:37 UTC, dotdc commented
LGTM :+1: 
You just need to wait for a `kube-prometheus-stack` maintainer to accept your PR.

2022-09-09 09:38 UTC, andrejshapal commented
@dotdc Many thanks. Have a good rest of the day ;)

2022-09-10 02:37 UTC, zanhsieh approved these changes

2022-09-10 13:59 UTC, monotek approved these changes

2022-09-10 14:00 UTC, merged