[prometheus-pushgateway] update notes.txt notify port
prometheus-community/helm-charts pull request #2462
Opened 2022-09-18 01:45 UTC by lusson-luo

#### What this PR does / why we need it

prometheus-pushgateway pod port is 9091, but install notify is 8080. i update to real port 9091.

#### Which issue this PR fixes

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-18 14:17 UTC, zeritti commented
I allow myself a comment on the change. The proposed change would not yield the desired results - the connection would get forwarded from the local 9091/tcp to the pod's 80/tcp. There is, however, nothing listening at 80/tcp in the pod by default.
I would suggest the change as follows:
```
kubectl port-forward $POD_NAME 9091
```
so that the user can just point their browser to `http://localhost:9091`.

Alternatively, if a "known" unprivileged port number is desired, then
```
kubectl port-forward $POD_NAME 8080:9091
```
which would mean opening `http://localhost:8080` in a browser.

2022-09-18 18:25 UTC, monotek requested changes
I don't think port 80 is a good idea, as that would need privileged linux user to bind to it. 

So imho original port should be used.

2022-09-18 18:25 UTC, monotek commented on charts/prometheus-pushgateway/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 9091:80
```suggestion
  kubectl port-forward $POD_NAME 9091
```

2022-09-19 05:59 UTC, lusson-luo commented
i change as follows:

`kubectl port-forward $POD_NAME 9091`

then open browser to http://localhost:9091

2022-09-19 08:27 UTC, monotek approved these changes

2022-09-19 08:27 UTC, merged