[prometheus-blackbox-exporter] Add selfMonitor support
prometheus-community/helm-charts pull request #2471
Opened 2022-09-20 13:55 UTC by tr3mor

#### What this PR does / why we need it

#### Which issue this PR fixes

Now if you deploy blackbox-exporter via this chart it will not create ServiceMonitor for itself, only for targets. This PR provides the ability to do it by overriding variables and enabling selfMonitor, similar to what kube-prometheus-stack chart does for alert-manager for example https://github.com/prometheus-community/helm-charts/blob/63a64f62d19f2c505a5139e91dc544ad1891273e/charts/kube-prometheus-stack/values.yaml#L405-L409 The problem was originally raised in #1936

#### Special notes for your reviewer
Not sure about value structure and formatting, open to suggestions
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-21 10:49 UTC, monotek requested changes

2022-09-21 10:49 UTC, monotek commented on charts/prometheus-blackbox-exporter/values.yaml
> +  selfMonitor: false
i would prefer it like this:

```suggestion
  selfMonitor: 
    enabled: false
    additionalMetricsRelabels: {}
    additionalRelabeling: []
    labels: {}
    interval: 30s
    scrapeTimeout: 30s
```

2022-09-21 12:10 UTC, tr3mor commented on charts/prometheus-blackbox-exporter/values.yaml
> +  selfMonitor: false
Updated

2022-09-21 15:25 UTC, monotek requested changes
please fix yaml lint

2022-09-22 11:51 UTC, monotek approved these changes

2022-09-22 11:51 UTC, merged