Added new diagram
prometheus-community/helm-charts pull request #2478
Opened 2022-09-22 10:07 UTC by XDavidT

Signed-off-by: David Tayar <38883783+XDavidT@users.noreply.github.com>

Only new diagram

2022-09-28 13:35 UTC, kylewin approved these changes

2022-09-28 14:04 UTC, monotek requested changes
pleaee use issue template and raise chart version

2022-09-29 01:27 UTC, zanhsieh commented
@XDavidT 
The diagram is not accessible.

2022-09-29 21:02 UTC, dotdc commented
Don't think the diagram is a good addition.
But if we do add it, it's probably better to load it directly from GitHub rather than an external website like imgur.com. 

My two cents.

2022-11-13 09:20 UTC, closed without merging