[prometheus-stackdriver-exporter] Adding support for container-level security context settings.
prometheus-community/helm-charts pull request #2486
Opened 2022-09-24 03:06 UTC by mitchmckenzie

Signed-off-by: Mitch McKenzie <mitch.mckenzie@outlook.com>

#### What this PR does / why we need it

Currently, the chart only allows setting pod-level security context settings, which adds support for adding container-level security context settings.   Some organizations require certain security settings to be applied at both the pod and container levels in order to be compliant(e.g. Open Policy Agent / Gatekeeper).  

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-24 07:26 UTC, monotek requested changes

2022-09-24 07:26 UTC, monotek commented on charts/prometheus-stackdriver-exporter/Chart.yaml
> +version: 4.0.2
New feature should raise minor version

2022-09-24 13:52 UTC, monotek approved these changes

2022-09-26 06:35 UTC, rpahli approved these changes

2022-09-26 06:36 UTC, merged