Add extraEnv to prometheus-cloudwatch-exporter
prometheus-community/helm-charts pull request #2500
Opened 2022-09-27 18:41 UTC by AClarkie

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-09-28 19:02 UTC, AClarkie commented
@asherf @gianrubio @torstenwalter any chance we can get some eyes on this today?

2022-09-29 01:58 UTC, zanhsieh requested changes

2022-09-29 01:58 UTC, zanhsieh commented on charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
> +        {{- end }}
This should be better to deal with empty object `{}`:

```suggestion
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
```

2022-09-29 07:14 UTC, monotek requested changes
Why don't you define the pod ip via extraenv? 
Imho it's not needed to be hard coded.

2022-09-29 08:10 UTC, AClarkie commented
> Why don't you define the pod ip via extraenv?
Imho it's not needed to be hard coded.

It's purely to simplify the env logic otherwise you need to check if each of the other variables like `.Values.aws.secret.name`, `.Values.aws.aws_secret_access_key` etc. are set before adding in the `env:` which imo would complicate the setup. A very similar approach is taken in the other community charts, see the below examples:

https://github.com/prometheus-community/helm-charts/blob/d7a033184b896d865b76507e585366c86d3cec65/charts/prometheus/templates/alertmanager/deploy.yaml#L53

https://github.com/prometheus-community/helm-charts/blob/d7a033184b896d865b76507e585366c86d3cec65/charts/prometheus/templates/alertmanager/sts.yaml#L52

2022-09-29 11:34 UTC, monotek approved these changes

2022-09-29 11:38 UTC, monotek requested changes

2022-09-29 11:48 UTC, monotek approved these changes

2022-09-29 11:50 UTC, merged