kube-prometheus-stack: Allow annotations on the admissionWebhook Jobs
prometheus-community/helm-charts pull request #2528
Opened 2022-10-06 11:58 UTC by marcofranssen

#### What this PR does / why we need it

When deploying via ArgoCD the ArgoCD app will be in a synchronization loop due to the kube-prometheus-stack jobs being removed due the `ttlAfterFinished: 0`. Using annotations we can inform ArgoCD not to recreate the Jobs in an infinite loop.

Currently the jobs can't be annotated and therefore we need this PR to allow the deployment of `kube-prometheus-stack` using ArgoCD.

#### Which issue this PR fixes

N.A.

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

@andrewgkew @desaintmartin @gianrubio

2022-10-11 14:01 UTC, monotek requested changes

2022-10-12 07:16 UTC, marcofranssen commented on charts/kube-prometheus-stack/values.yaml
> +    # annotations:
What is the difference here? I don't see what changed here.

2022-10-12 07:22 UTC, marcofranssen commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 40.5.1
Next minor version number is `41.2.0`. I have bumped it there.

2022-10-12 07:24 UTC, marcofranssen commented
@monotek Thanks for the feedback. Processed your feedback, though I did bump the version to `41.2.0` as that is the next patch release.

2022-10-12 10:34 UTC, monotek requested changes
41.2.0 was just merged.

2022-10-12 10:34 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 41.2.0
```suggestion
version: 41.3.0
```

2022-10-12 10:45 UTC, merged