[prometheus-smartctl-exporter] Quick mapping of chart to new 0.8.0 config and updated to that version.
prometheus-community/helm-charts pull request #2530
Opened 2022-10-06 16:38 UTC by kfox1111

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-10-07 11:48 UTC, monotek requested changes
why is the configmap not used anymore?

2022-10-07 19:00 UTC, onedr0p commented
@monotek looks to be related to https://github.com/prometheus-community/smartctl_exporter/pull/68

@kfox1111 you should also update the repository to be `quay.io/prometheuscommunity/smartctl-exporter`

2022-10-11 16:38 UTC, onedr0p commented
Looks like some of the changes made it in via https://github.com/prometheus-community/helm-charts/pull/2542

2022-10-11 22:31 UTC, monotek approved these changes

2022-10-11 22:31 UTC, merged