[kube-prometheus-stack]: Alert mgr service monitor: enableHttp2
prometheus-community/helm-charts pull request #2540
Opened 2022-10-11 11:37 UTC by gadisn

Signed-off-by: gadisn <gadisn@gmail.com>

Signed-off-by: gadisn <gadisn@users.noreply.github.com>

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-10-11 13:56 UTC, monotek requested changes

2022-10-11 13:56 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 41.0.1
new feature should raise minor verison

```suggestion
version: 41.1.0
```

2022-10-11 23:04 UTC, monotek requested changes
whats the default setting?
imho new feature should be disabled by default.

2022-10-12 05:01 UTC, gadisn commented
> whats the default setting? imho new feature should be disabled by default.

The default for `enableHttp2` in [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config), which is the equivalent of service monitor, is indeed `true`.

So this new feature of **being able to avoid http2** is indeed disabled by default

2022-10-12 10:33 UTC, monotek approved these changes

2022-10-12 10:33 UTC, merged