[kube-prometheus-stack] avoid alerting field in prometheus CR, if alertmanager config is empty
prometheus-community/helm-charts pull request #2600
Opened 2022-10-23 01:06 UTC by jkroepke

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>

#### What this PR does / why we need it

If no alertmanager or alerting config is present, avoid the alerting key in the prometheus CR. This is needed, if the prometheus is configured for agent mode. See linked issue.

Let me know, if a dedicated toggle if preferred over an implicit one.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- relates https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1277362029

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-10-31 23:49 UTC, monotek requested changes

2022-10-31 23:49 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 41.7.1
```suggestion
version: 41.7.2
```

2022-10-31 23:51 UTC, monotek approved these changes

2022-10-31 23:54 UTC, merged

2025-10-28 13:58 UTC, rmorilha commented
Never got to test it. The project I was developing got canceled and thrown into the trash. sorry but thanks ppl.