[kube-prometheus-stack] bump grafana to 6.43.0 (9.2.1)
prometheus-community/helm-charts pull request #2602
Opened 2022-10-24 15:17 UTC by nourspace

#### What this PR does / why we need it

Updated grafana to helm version 6.43.0 and app version 9.2.1

Changes: https://github.com/grafana/helm-charts/compare/grafana-6.40.4...grafana-6.43.0

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-10-24 20:41 UTC, monotek approved these changes

2022-10-24 20:44 UTC, monotek requested changes
Please run helm dependency build again...

2022-10-24 21:02 UTC, nourspace commented
> Please run helm dependency build again...

I'm not able to run the build, and when I run `helm dep update` it updates other subcharts as well. Any suggestions?

2022-10-24 21:08 UTC, nourspace commented
I mean unless we have an issue with auto minor version updates, the last commit should build.

2022-10-25 07:54 UTC, monotek approved these changes

2022-10-25 07:54 UTC, merged

2022-10-25 07:55 UTC, monotek commented
> when I run `helm dep update` it updates other subcharts as well. Any suggestions?

thats ok, as the wildcard for the patch verison is used for all the subcharts...