[prometheus-kafka-exporter] Bump kafka-exporter to 1.6.0
prometheus-community/helm-charts pull request #2613
Opened 2022-10-26 09:05 UTC by zied-jt

Signed-off-by: Zied ABID <zied.abid@jobteaser.com>

#### What this PR does / why we need it

Bump kafka-exporter to 1.6.0 acording to https://github.com/danielqsj/kafka_exporter/releases/tag/v1.6.0 along with new features

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-10-26 09:21 UTC, BenjaminVouillaumeJT approved these changes

2022-10-26 09:30 UTC, monotek requested changes
Image tag needs to be updated too: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-kafka-exporter/values.yaml#L3

PR could be extended to allow such changes in the future.

Can be done like here: https://github.com/prometheus-community/helm-charts/commit/980563d47e172f2d275ff4fd7bcd6abedb3b2d5d

2022-10-26 16:43 UTC, monotek requested changes

2022-10-26 16:43 UTC, monotek commented on charts/prometheus-kafka-exporter/values.yaml
> +  tag: ""
please add the info too...
```suggestion
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

2022-10-26 16:43 UTC, monotek approved these changes

2022-10-26 16:47 UTC, merged

2022-10-27 07:18 UTC, zied-jt commented
@monotek Thanks for guidance and the acceptance !