[kube-prometheus-stack] Bump prometheus-node-exporter subchart version
prometheus-community/helm-charts pull request #2619
Opened 2022-10-28 14:53 UTC by Evilong

Signed-off-by: João Estrela <jestrela@barracuda.com>

#### What this PR does / why we need it

Bump prometheus-node-exporter subchart version as it is now 4.4.*

#### Special notes for your reviewer

Changes tested by diffing results with default values

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-10-28 15:20 UTC, monotek requested changes

2022-10-28 15:20 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 41.6.2
i would go with feature version too, if subchart raised feature version.
```suggestion
version: 41.7.0
```

2022-10-28 15:23 UTC, monotek approved these changes

2022-10-28 15:35 UTC, merged

2022-10-30 03:49 UTC, gruberdev commented
:warning: Syncing [kube-prometheus](https://argocd.gr.wtf/applications/kube-prometheus) to 0b8ac6cd6407d492b2d2c12e1d3432d5e5ced227

2022-10-30 03:56 UTC, gruberdev commented
## :x: Sync Failed: [kube-prometheus](https://argocd.gr.wtf/applications/kube-prometheus)
Error while syncing to 0b8ac6cd6407d492b2d2c12e1d3432d5e5ced227:
- SyncFailed `monitoring/prometheuses.monitoring.coreos.com`: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
- SyncFailed `monitoring/kube-prometheus-kube-prome-prometheus`: unable to recognize "/dev/shm/3518900193": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"