[kube-prometheus-stack] Fix CoreDNS dashboard for v1.7.0+
prometheus-community/helm-charts pull request #264
Opened 2020-10-27 11:53 UTC by cablespaghetti

#### What this PR does / why we need it:
Updates the CoreDNS dashboard to support versions after 1.7.0 which changed a number of metrics and broke the existing dashboard.

#### Which issue this PR fixes
fixes #207 

#### Special notes for your reviewer:
This is a slightly tweaked version of this dashboard and seems to work just fine before and after the 1.7.0 upgrade: https://grafana.com/grafana/dashboards/12539

Before new dashboard (you can see where I upgraded coredns and the metrics disappeared):
![Screenshot_2020-10-27 CoreDNS - Grafana](https://user-images.githubusercontent.com/11150054/97298167-f317c580-184a-11eb-9f01-6cc1874a647e.png)

After new dashboard:
![Screenshot_2020-10-27 CoreDNS - Grafana(1)](https://user-images.githubusercontent.com/11150054/97298180-f8751000-184a-11eb-8d51-d71a83c9f6c0.png)

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-10-27 12:12 UTC, cablespaghetti commented
I'm fairly sure I didn't break the CI at the moment. Potentially due to the new Helm 3.4.0 release coming out?

2020-11-05 22:10 UTC, invidian submitted a review, later dismissed
PR needs rebasing, but I tested it on my cluster (rebased) and it indeed finally fixes CoreDNS dashboard. Great work @cablespaghetti!

2020-11-11 21:18 UTC, cablespaghetti commented
@invidian Done!

2020-11-14 13:24 UTC, monotek approved these changes

2020-11-15 02:54 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 11.1.2
can you bump the version pls?

2020-11-15 08:34 UTC, cablespaghetti commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 11.1.2
Done!

2020-11-15 20:42 UTC, monotek submitted a review, later dismissed

2020-11-16 11:44 UTC, vsliouniaev approved these changes

2020-11-16 11:45 UTC, vsliouniaev requested changes
Could you please bump the chart version again?

2020-11-16 11:45 UTC, vsliouniaev commented
/retest

2020-11-16 11:54 UTC, cablespaghetti commented
![Your wish is my command](https://i.makeagif.com/media/5-02-2017/fnQGcK.gif)

2020-11-16 11:59 UTC, invidian commented
This bumping chart version as gate for merging PRs is so ridiculous :smile:

2020-11-16 14:47 UTC, vsliouniaev submitted a review, later dismissed

2020-11-16 14:48 UTC, vsliouniaev commented
Looks like something else was merged in, could you do it again please?

2020-11-16 14:52 UTC, vsliouniaev commented
Looks like there are conflicts that prevent me from merging this PR.

2020-11-16 14:55 UTC, cablespaghetti commented
Ok. Should be good now. :crossed_fingers:

2020-11-16 15:05 UTC, vsliouniaev approved these changes

2020-11-16 15:05 UTC, merged