[alertmanager] update to current release
prometheus-community/helm-charts pull request #2644
Opened 2022-11-03 21:16 UTC by kubicgruenfeld

#### What this PR does / why we need it

It updates the alertmanager appVersion to the current release.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-11-03 23:01 UTC, naseemkullah submitted a review, later dismissed

2022-11-03 23:16 UTC, monotek requested changes
please also update configmap-reload image to v0.8.0

2022-11-04 08:22 UTC, kubicgruenfeld commented
> please also update configmap-reload image to v0.8.0

done

2022-11-04 08:28 UTC, monotek approved these changes

2022-11-04 08:28 UTC, merged