[prometheus-node-exporter] Refactor
prometheus-community/helm-charts pull request #2650
Opened 2022-11-06 02:34 UTC by zanac1986

Signed-off-by: zanac1986 <zanhsieh@protonmail.com>

#### What this PR does / why we need it

Refactor 

#### Which issue this PR fixes

- From `{{- if .Values.foo }}` to `{{- with }}` and using the context under it
- Get rid of `{{- if .Values.foo }}` combining with `{{ range $key, $value := .Value.foo }}`
- `template` and `include` binding to root (`$`)
- Indention

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name

2022-11-06 12:18 UTC, monotek requested changes

2022-11-06 12:18 UTC, monotek commented on charts/prometheus-node-exporter/templates/daemonset.yaml
> +    {{- include "prometheus-node-exporter.labels" $ | indent 4 }}
i would use the default here, like "helm create" would do it.:
```
metadata:
  name: {{ include "prometheus-node-exporter.fullname" . }}
  labels:
    {{- include "prometheus-node-exporter.labels" . | nindent 4 }}

```

2022-11-11 10:47 UTC, monotek approved these changes

2022-11-11 14:27 UTC, zanhsieh approved these changes

2022-11-11 14:27 UTC, merged