[prometheus-pushgateway] Ensure PDB labels are same as the matchLabels of the owner app
prometheus-community/helm-charts pull request #2666
Opened 2022-11-09 10:54 UTC by mikhailadvani

#### What this PR does / why we need it

To support multiple releases of pushgateway in a single namespace.

#### Which issue this PR fixes

- fixes #2665 

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-11-09 11:02 UTC, monotek approved these changes

2022-11-22 22:29 UTC, zanhsieh requested changes

2022-11-22 22:29 UTC, zanhsieh commented on charts/prometheus-pushgateway/templates/deployment.yaml
> +{{- include "prometheus-pushgateway.selectorLabels" . | indent 6 }}
```suggestion
      {{- include "prometheus-pushgateway.selectorLabels" . | nindent 6 }}
```

2022-11-22 22:29 UTC, zanhsieh commented on charts/prometheus-pushgateway/templates/pdb.yaml
> +{{- end -}}
```suggestion
      {{- include "prometheus-pushgateway.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end -}}
```

2022-11-22 22:29 UTC, zanhsieh commented on charts/prometheus-pushgateway/templates/_helpers.tpl
> +{{- end }}
Align with previous _helpers.tpl
```suggestion
{{- define "prometheus-pushgateway.selectorLabels" -}}
app: {{ template "prometheus-pushgateway.name" . }}
release: {{ .Release.Name }}
{{- end -}}
```

2022-11-22 22:29 UTC, zanhsieh commented on charts/prometheus-pushgateway/templates/statefulset.yaml
> +{{- include "prometheus-pushgateway.selectorLabels" . | indent 6 }}
```suggestion
      {{- include "prometheus-pushgateway.selectorLabels" . | nindent 6 }}
```

2022-11-25 13:01 UTC, zanhsieh requested changes

2022-11-25 13:01 UTC, zanhsieh commented on charts/prometheus-pushgateway/templates/statefulset.yaml
>          {{- end }}
```suggestion
        {{- with .Values.persistentVolume.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
```

2022-11-26 01:07 UTC, zanhsieh approved these changes

2022-11-26 21:20 UTC, zanhsieh approved these changes

2022-11-30 20:52 UTC, monotek approved these changes

2022-11-30 20:53 UTC, merged