[kube-prometheus-stack] add support for additional labels on operator's ServiceMonitor
prometheus-community/helm-charts pull request #2687
Opened 2022-11-15 16:02 UTC by aubm

#### What this PR does / why we need it

This PR add support for placing additional custom labels on the ServiceMonitor resource created for the Prometheus operator deployment.

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-11-15 18:24 UTC, monotek requested changes

2022-11-15 21:41 UTC, aubm commented on charts/kube-prometheus-stack/values.yaml
> +    labels: {}
Hello @monotek thank you for your feedback, I've just pushed a new commit to reproduce your suggestion as I also needed to adapt the template.

2022-11-16 15:34 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 41.8.0
```suggestion
version: 41.9.0
```

2022-11-16 15:35 UTC, monotek approved these changes

2022-11-17 00:05 UTC, merged