[kube-prometheus-stack] Fix PSP deprecation after k8s 1.25+
prometheus-community/helm-charts pull request #2691
Opened 2022-11-16 09:28 UTC by QuentinBisson

Signed-off-by: QuentinBisson <quentin@giantswarm.io>

#### What this PR does / why we need it

This PR fixes PSP deprecation after k8s 1.25+ added for the prometheus operator patch jobs.

#### Which issue this PR fixes

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-11-16 12:47 UTC, QuentinBisson commented
@monotek do you mind reviewing this?

2022-11-16 19:43 UTC, monotek requested changes

2022-11-16 19:43 UTC, monotek commented on charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
> +{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
Please use "if and"

2022-11-16 19:43 UTC, monotek commented on charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
> +{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
Please add to if clause above

2022-11-17 11:22 UTC, QuentinBisson commented
@monotek it's fixed

2022-11-19 11:25 UTC, monotek approved these changes

2022-11-19 11:25 UTC, merged