[prometheus-crds]: CRDs provided in separate Chart
prometheus-community/helm-charts pull request #2697
Opened 2022-11-16 13:22 UTC by dacamposol

#### What this PR does / why we need it

Using `kube-prometheus-stack` from GitOps tools like Argo CD poses a problem in the way that currently the CRDs are defined to be used.

Since there are some CRDs (like `prometheuses`) which have a lot of changes between versions, the annotations exceed the maximum size, ending up in synchronise issues which can only be solved manually (for example by forcing Argo CD to `replace` that resource instead of `applying` changes to it). This behaviour can be modified at resource level, but that would require to be able to modify the annotations of the proper CRDs... Which we can not when they are under the `crd` folder.

Due to that, I'm presenting this PR, where we introduce the [CRDs as a separate Chart](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts) and also I'm allowing to introduce some custom annotations for compatibility with GitOps tools which can rely on those for adding custom logic on how those resources need to be applied.

For example, I would desire to have the following annotation on my CRDs for ArgoCD:

```yaml
argocd.argoproj.io/sync-options: Replace=true
```

Also, this won't break compatibility of the already existing `kube-prometheus-stack`, since it contains the CRDs in the `crd` folder (according to Helm 3 specification), so we can just avoid to install those with the `skipCRDs` flag present in almost all the GitOps tools which rely on Helm, and include the CRDs by this new Chart.

#### Which issue this PR fixes

This issue has been discussed before, but it was closed without an actual solution moreover than recommending to apply the CRDs manually through `kubectl create` or `kubectl apply --force-conflicts=true --server-side`, which is not an actual solution but more a patch.

#### Special notes for your reviewer

This is just a proposal, so I acknowledge that some changes should be made before it's being accepted to be included.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Title of the PR starts with chart name (new Chart)

Signed-off-by: Daniel Campos Olivares <dacamposol@gmail.com>

2022-11-16 20:41 UTC, mrueg commented
I would suggest to rename the chart to prometheus-operator-crds as prometheus can run without those.

2022-11-16 20:44 UTC, dacamposol commented
> I would suggest to rename the chart to prometheus-operator-crds as prometheus can run without those.

Fair enough 😄

2022-11-30 20:36 UTC, monotek requested changes
Maintainers are missing.
@desaintmartin do you want to co maintain?

2022-12-07 14:46 UTC, desaintmartin commented
Indeed, I am interested! It would be even more awesome to have it automated somehow, discussing in https://github.com/prometheus-community/helm-charts/issues/2612.

2022-12-08 16:28 UTC, desaintmartin commented
There are still linting errors @dacamposol.

2022-12-12 20:42 UTC, jcpunk commented on charts/prometheus-operator-crds/Chart.yaml
> +  A Helm chart that collects custom resource definitions (CRDs) from the Prometheus Operator, allowing for seamless
Resolving the trailing spaces here might cleanup the linting error.

2022-12-13 12:17 UTC, dacamposol commented
> There are still linting errors @dacamposol.

Resolved. 

Could you please trigger the tests?

2022-12-20 20:10 UTC, desaintmartin commented
Looks good! Should we merge this? And my first contribution will be to update them. :)

2022-12-20 20:10 UTC, desaintmartin approved these changes

2022-12-20 20:40 UTC, monotek approved these changes

2022-12-20 20:40 UTC, merged