[kube-state-metrics] Refactor
prometheus-community/helm-charts pull request #2778
Opened 2022-12-02 22:40 UTC by zanac1986

Signed-off-by: zanac1986 <zanhsieh@protonmail.com>

#### Which issue this PR fixes

Refactor following:

- Fix indention
- Reformat `templates/_helper.tpl` to close to the code similar to the one thru `helm create kube-state-metrics`
- Move pdb apiVersion to `templates/_helper.tpl`

No change to values.yaml, which means backward compatible.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-04 04:58 UTC, zanhsieh requested changes

2022-12-04 04:58 UTC, zanhsieh commented on charts/kube-state-metrics/README.md
> +_See [helm repository](https://helm.sh/docs/helm/helm_repo/) for command documentation._
```suggestion
_See [`helm repo`](https://helm.sh/docs/helm/helm_repo/) for command documentation._
```

2022-12-05 13:12 UTC, zanhsieh approved these changes

2022-12-05 13:36 UTC, mrueg commented
@zanac1986 @zanhsieh are you approving your own changes here or is the name just a coincidence?

2022-12-05 14:29 UTC, zanhsieh commented
@mrueg 
I can't merge it. Only you can.

2022-12-05 15:39 UTC, monotek commented
That does not answer the question, which i like to get answered too.

2022-12-05 16:47 UTC, mrueg commented
> @mrueg @monotek I think just coincidence. I don't know that guy.

What a coincidence! Thanks for clarifying. I was wondering because your emails did only differ in provider name as well as both of your github account names were "MH" :D

2022-12-07 09:26 UTC, dotdc requested changes
+1 @monotek 

For the PR itself, it is a lot of changes to test for limited benefits, and the risk of breaking something is high in my opinion. 

@zanac1986, If you want these changes to be merged, cut them into smaller PR's and explain why we should merge for each of them.

Do we agree to close this PR? 
@mrueg @monotek

2022-12-07 11:39 UTC, closed without merging