[prometheus-node-exporter] Adds podTargetLabels configuration to service monitor
prometheus-community/helm-charts pull request #2785
Opened 2022-12-05 06:06 UTC by cdivitotawela

Kubernetes service monitor supports [podTargetLabels](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitor) which allows extracting pod labels into the metrics by specifying list of label names to be included.

Signed-off-by: Chaminda Divitotawela <cdivitotawela@gmail.com>

2023-01-05 03:40 UTC, zanhsieh requested changes
@cdivitotawela 
Thanks for your contribution. Would you mind to provide some explanation in README.md for those trying to upgrade from prometheus-node-exporter 4.8.x -> 4.9.0? Like checklist before upgrade, procedure to upgrade, what were supported and what were dropped.

2023-01-09 19:33 UTC, monotek reviewed
@zanhsieh 
i don't see why upgrade instructions would be needed for a feature update?
can you elaborate?

2023-01-10 14:29 UTC, zanhsieh submitted a review, later dismissed

2023-01-10 15:46 UTC, zanhsieh approved these changes

2023-01-10 15:46 UTC, merged