[kube-prometheus-stack ]Upgrade to 43.0.0
prometheus-community/helm-charts pull request #2789
Opened 2022-12-05 17:03 UTC by irizzant

Signed-off-by: irizzant <i.rizzante@gmail.com>

#### What this PR does / why we need it
This PR upgrades the chart to version 43.0.0 in order to document a change to Grafana sub chart which prevents Grafana Pod to be deployed.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #2788

#### Special notes for your reviewer

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-05 18:59 UTC, monotek requested changes
Can you please also add the update to prom operator  0.61.1 and also update the docker image versions?

2022-12-06 07:42 UTC, irizzant commented
@monotek I don't know how to make the branch writable but I think I copied everything you asked me.

2022-12-06 11:58 UTC, monotek requested changes
all the changes to the crds, dashboards and so on are missing.

about write access: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

2022-12-06 11:58 UTC, monotek commented on charts/kube-prometheus-stack/README.md
> +This version upgrades Prometheus-Operator to v0.61.1, Prometheus to v2.40.5 and Thanos to v0.29.10
```suggestion
This version upgrades Prometheus-Operator to v0.61.1, Prometheus to v2.40.5 and Thanos to v0.29.0
```

2022-12-06 13:27 UTC, irizzant commented
@monotek I've also added the missing resources you requested

2022-12-06 15:51 UTC, monotek requested changes
I just checked the update from 41.0.0 to 42.0.0 to 42.2.0 and did not hit any Grafana related errror using the default configuration of our chart, so i dont think we have to extend our upgrading docs at all.

So i would remove the grafana instructions here as it might be misleading for users which are just using the default config.

2022-12-06 16:37 UTC, irizzant commented
@monotek apparently they released a new Grafana chart 6.45.1 which contains https://github.com/grafana/helm-charts/pull/2041 and allows the previous configuration to work again.

If you prefer I can upgrade the dependency instead

2022-12-06 22:22 UTC, monotek commented
Yes, please update dependency

2022-12-12 09:52 UTC, cod-r commented
prometheus-operator v0.61.1 added a new spec field `spec.alertmanagerConfigMatcherStrategy.type:`. See: https://github.com/prometheus-operator/prometheus-operator/issues/3737#issuecomment-1326667523
I can't find this option in kube-prometheus-stack `values.yaml` file

2022-12-13 11:39 UTC, monotek approved these changes

2022-12-13 11:43 UTC, merged

2022-12-13 12:21 UTC, cod-r commented
Hi @monotek, you merged the PR but I still can't see the option to enable `spec.alertmanagerConfigMatcherStrategy.type` in `values.yaml`

It should be:
```
alertmanager:
  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
```

Am I missing something?