[alertmanager] feat: support for custom volumes and environment variables
prometheus-community/helm-charts pull request #2797
Opened 2022-12-07 11:34 UTC by kshcherban

#### What this PR does / why we need it

This PR adds support for custom environment variables and volumes to alertmanager container.
Can be useful if you want to use secrets from [CSI secrets store](https://secrets-store-csi-driver.sigs.k8s.io/) in alertmanager configuration.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-07 17:56 UTC, kshcherban commented on charts/alertmanager/templates/_helpers.tpl
> +Based on bitnami common
Added as dependency.

2022-12-07 17:56 UTC, kshcherban commented on charts/alertmanager/values.yaml
> +extraEnvVars: []
Renamed.

2022-12-07 17:56 UTC, kshcherban commented on charts/alertmanager/templates/statefulset.yaml
> +            {{- include "alertmanager.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
Renamed.

2022-12-07 23:10 UTC, naseemkullah approved these changes

2022-12-07 23:11 UTC, naseemkullah approved these changes

2022-12-08 00:03 UTC, monotek requested changes
chart version eeds to be updated.

i'm not sure if its desirable to use bitnami/common as dependency, as we have no control over it,

i had a prometheus-community/common chart in mind before, which would be used by all charts here, but would be a lot of work to build and maintain it and refactor all the charts.

2022-12-08 16:53 UTC, kshcherban commented on charts/alertmanager/.gitignore
> +requirements.lock
I copied .gitignore from [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus). Thought if there are dependencies you need to add it.
Ok will remove.

2022-12-13 16:20 UTC, monotek requested changes

2022-12-13 16:20 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 0.22.3
new feautere should raise minor version

2022-12-13 18:48 UTC, kshcherban commented on charts/alertmanager/Chart.yaml
> +version: 0.22.3
Done.

2022-12-16 12:26 UTC, monotek approved these changes

2022-12-16 12:26 UTC, merged