[kube-prometheus-stack] Update grafana chart version
prometheus-community/helm-charts pull request #2805
Opened 2022-12-13 07:44 UTC by Sumoa

Signed-off-by: Christof Huber <christof-huber@gmx.de>

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-13 08:04 UTC, monotek approved these changes

2022-12-13 16:15 UTC, monotek requested changes
please resolve merge conflicts

2022-12-15 11:22 UTC, Sumoa commented
> please resolve merge conflicts

@monotek Done

2022-12-15 11:29 UTC, monotek approved these changes

2022-12-15 11:29 UTC, merged