[prometheus-rabbitmq-exporter] Updated rabbitmq exporter maintainer list
prometheus-community/helm-charts pull request #282
Opened 2020-10-29 14:51 UTC by iamabhishek-dubey

Signed-off-by: iamabhishek-dubey <abhishekbhardwaj510@gmail.com>

#### What this PR does / why we need it:

This PR is for adding @iamabhishek-dubey as maintainer for RabbitMQ exporter

#### Special notes for your reviewer:

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-10-29 14:57 UTC, scottrigby requested changes

2020-10-29 14:57 UTC, scottrigby commented on .github/CODEOWNERS
> +/charts/prometheus-rabbitmq-exporter/ @juanchimienti @iamabhishek-dubey
This should be sorted. There is a script in this repo you can run that should do this for you locally based on maintainers listed in the charts

2020-10-29 15:03 UTC, scottrigby commented
Relates to #21

2020-10-29 15:18 UTC, iamabhishek-dubey commented
I have made the changes @scottrigby

2020-10-29 17:52 UTC, torstenwalter approved these changes

2020-10-29 17:53 UTC, torstenwalter commented
Another maintainer of the chart needs to approve and can merge it directly afterwards.

2020-10-29 19:14 UTC, scottrigby commented
Yep, per PROCESSES.md

2020-10-29 19:45 UTC, torstenwalter commented
@scottrigby you still have a review, where you request changes. Can you dismiss that one or approve as well?

2020-10-29 21:39 UTC, monotek approved these changes

2020-11-29 01:32 UTC, scottrigby approved these changes

2020-11-29 15:22 UTC, scottrigby commented
@Juanchimienti just checking in. Ideally a current maintainer of a chart would sign off on adding any additional maintainers. In our PROCESSES doc we say a repo administrator can decide to merge a PR if maintainers of the chart don't reply within 2 weeks. However adding a new maintainer should probably wait a bit longer (maybe we should specify that in PROCESSES). This PR has been open for a month.

In general I'd recommend only adding maintainers who have contributed non-insignificant PRs to the repo in the past. @iamabhishek-dubey has contributed to this repo a bit: one PR to add the Druid exporter (https://github.com/prometheus-community/helm-charts/pull/114). We also have a goal of having more than one maintainer for each chart (#21), and this chart has only one maintainer. Let's wait just a bit longer for @Juanchimienti to reply. But at a certain point, it would be good to have at least one other active maintainer for this chart.

2021-01-09 17:46 UTC, monotek commented
@scottrigby seems we should just move forward with this one.

2021-01-13 00:53 UTC, scottrigby commented
Agreed 👍

2021-01-13 00:53 UTC, scottrigby approved these changes

2021-01-13 15:20 UTC, merged