[prometheus-json-exporter] Automatically rollover deployment when configmap changed.
prometheus-community/helm-charts pull request #2831
Opened 2022-12-20 13:28 UTC by stefanandres

#### What this PR does / why we need it

Add annotation to deployment to auto rollover the deployment on changes to the configmap
(https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)

#### Which issue this PR fixes

Currently you need to manually delete the pod to get the new config from the configmap.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-20 22:51 UTC, zanhsieh submitted a review, later dismissed

2022-12-21 08:08 UTC, stefanandres commented
Sorry, I wrongly rebased the branch, it's up2date now again.

2022-12-21 17:56 UTC, monotek commented
could you please rebase again?
ci sees still the old version.

2022-12-21 17:56 UTC, monotek reviewed
could you please rebase again?
ci sees still the old version.

2022-12-21 17:56 UTC, monotek requested changes
could you please rebase again?
ci sees still the old version.

2022-12-22 09:11 UTC, monotek requested changes
chart version needs to be updated, not the appversion

2022-12-22 09:24 UTC, stefanandres commented
> chart version needs to be updated, not the appversion

Yeah, that got mixed up the the bogus rebase in the beginning. I hope it's done now, since the Chart is now also 0.6 and not 0.5 anymore ;)

2022-12-22 09:34 UTC, monotek approved these changes

2022-12-22 09:34 UTC, merged