[prometheus-postgres-exporter] fix: propagate warning from upstream
prometheus-community/helm-charts pull request #2838
Opened 2022-12-21 15:32 UTC by hajdukda

#### What this PR does / why we need it

This propagates important notification that is available in source and ppl still get caught by that: https://github.com/prometheus-community/postgres_exporter/issues/549

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer
This just propagates the warning from upstream to chart.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped - does it really have to be ??
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-21 17:46 UTC, monotek approved these changes

2022-12-21 17:46 UTC, monotek requested changes
please sign your commits to get dco check passing

2022-12-23 15:42 UTC, hajdukda commented
Rebased + signed

2022-12-23 19:42 UTC, monotek approved these changes

2022-12-23 19:42 UTC, merged