[prometheus] Enable pulling images by digest
prometheus-community/helm-charts pull request #2849
Opened 2022-12-23 19:02 UTC by ivyostosh

#### What this PR does / why we need it
Pulling images by digest allows users to “pin” an image to that version, and guarantee that the image is always the same ([read more](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier)). This is not currently supported by the helm chart.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2022-12-23 19:45 UTC, monotek requested changes

2022-12-23 19:45 UTC, monotek commented on charts/prometheus/values.yaml
> +    # digest: ""
```suggestion
    digest: ""
```

2022-12-23 19:45 UTC, monotek commented on charts/prometheus/values.yaml
> +      # digest: ""
```suggestion
      digest: ""
```

2022-12-24 17:58 UTC, monotek requested changes

2022-12-24 17:58 UTC, monotek commented on charts/prometheus/Chart.yaml
> +version: 19.1.1
```suggestion
version: 19.1.0
```

2022-12-25 09:29 UTC, monotek requested changes
Sorry, Version needs to be 19.2.0 now...

2022-12-25 14:33 UTC, ivyostosh commented
> Sorry, Version needs to be 19.2.0 now...

@monotek Updated!

2022-12-25 20:01 UTC, monotek approved these changes

2022-12-25 22:34 UTC, zanhsieh approved these changes

2022-12-26 00:03 UTC, merged