[kube-prometheus-stack] Change helm stable repo in docs
prometheus-community/helm-charts pull request #286
Opened 2020-10-30 09:41 UTC by arslanbekov

#### What this PR does / why we need it:
Actualize docs

#### Special notes for your reviewer:
New URL for [stable](https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository) helm chart

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-10-30 16:52 UTC, monotek approved these changes

2020-10-30 16:59 UTC, monotek approved these changes
Please raise version to 10.3.3

2020-10-30 22:24 UTC, arslanbekov commented
Oh, this is the first time I encountered a signature and it gives me trouble

2020-10-31 21:31 UTC, monotek approved these changes

2020-10-31 21:33 UTC, monotek requested changes
Just rebase, removing my commits, and you should be fine.

2020-10-31 22:20 UTC, closed without merging