[kube-prometheus-stack] Allow to define cluster label on all kube-prometheus-stack monitors
prometheus-community/helm-charts pull request #2877
Opened 2023-01-02 16:05 UTC by jkroepke

#### What this PR does / why we need it

With #1132 we can use multi-cluster dashboards with depends on the cluster label. While its possible to set the cluster label on federated metrics, its not possible to define this metric on the own metrics.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-01-09 19:36 UTC, monotek requested changes
please add it via more generic approach, where labels can be added freely.

otherwise if some other label would be needed a new option has to be added.

2023-01-09 20:31 UTC, jkroepke commented
It should be more generic now.

2023-01-16 10:01 UTC, monotek requested changes
imho labels and targetLabels are differents things and should not be configureed via a single variable.

2023-01-16 11:24 UTC, jkroepke commented on charts/kube-prometheus-stack/templates/prometheus/servicemonitors.yaml
> +      - cluster
thanks

2023-01-16 11:26 UTC, jkroepke commented
About the `targetLabels` thing, before the PR, `targetLabels` was not configurable at all.

2023-01-29 09:46 UTC, closed without merging

2024-02-25 22:19 UTC, oshamin commented
I am looking for a solution to add "cluster" label to all ServiceMonitors. This PR could solve my problem, but it was not merged :(.

Are there any other simple options to do that?