[prometheus-kafka-exporter] Annotate tests/* with "helm.sh/hook: test" so that we don't launch stray Kafka/ZooKeeper pods.
prometheus-community/helm-charts pull request #288
Opened 2020-10-30 21:56 UTC by vitaliyf

#### What this PR does / why we need it:

Currently, deploying this chart leaves behind pods running Kafka and ZooKeeper.

#### Which issue this PR fixes

n/a

#### Special notes for your reviewer:

This change was mentioned by @scottrigby when this chart was contributed here: https://github.com/prometheus-community/helm-charts/pull/91#issuecomment-695144728 but never added.

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-01 17:32 UTC, gkarthiks commented
why not have https://github.com/prometheus-community/helm-charts/pull/289 as well in the same chart version?

2020-11-01 18:22 UTC, vitaliyf commented
> why not have #289 as well in the same chart version?

Done. Mostly because I created this PR as I was settings things up and the other after I was done and thought some things I discovered would be helpful to others.

2020-12-02 10:59 UTC, gkarthiks commented on charts/prometheus-kafka-exporter/Chart.yaml
> +version: 0.1.5
Hi, why don't you rebase and raise the chart verison?

2021-01-09 18:09 UTC, monotek requested changes
@vitaliyf  please check the failing chart install test

2021-02-22 19:25 UTC, closed without merging