[kube-prometheus-stack] add alertmanagerConfigMatcherStrategy for alertmanager
prometheus-community/helm-charts pull request #2882
Opened 2023-01-04 02:27 UTC by jojotong

#### What this PR does / why we need it
Prometheus operator release feature `alertmanagerConfigMatcherStrategy` by https://github.com/prometheus-operator/prometheus-operator/pull/5084 at `v0.61.0`, but not contains in this helm chart.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-01-05 06:19 UTC, jojotong commented
@andrewgkew @gianrubio @gkarthiks @scottrigby @Xtigyro

2023-01-09 19:48 UTC, monotek requested changes

2023-01-09 19:48 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 43.2.2
new featue should raise minor version

2023-01-11 05:05 UTC, jojotong commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 43.2.2
Updated.

2023-01-16 09:43 UTC, monotek requested changes

2023-01-16 09:43 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 43.3.0
```suggestion
version: 44.2.0
```

2023-01-16 09:49 UTC, monotek approved these changes

2023-01-16 09:49 UTC, merged