[prometheus-mysql-exporter] add imagePullSecrets and fullname override
prometheus-community/helm-charts pull request #2905
Opened 2023-01-09 20:37 UTC by yaskinny

#### What this PR does / why we need it
let user set registry pull secrets if they want to use their private registry.

#### Which issue this PR fixes
add imagePullSecrets to mysql-exporter chart  
add fullname override(You had it in helpers templates but not in values file)  
set default image tag from .Values.image.tag to .Chart.AppVersion  

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-01-10 02:33 UTC, monotek requested changes

2023-01-10 02:33 UTC, monotek commented on charts/prometheus-mysql-exporter/Chart.yaml
> +version: 1.11.2
New feature should raise minor version.

2023-01-10 02:33 UTC, monotek commented on charts/prometheus-mysql-exporter/values.yaml
> +  ## default on chart appVersion
```suggestion
  ## if not set charts appVersion var is used
```

2023-01-11 07:09 UTC, yaskinny commented
I made your requested changes,  
if there's no more changes that I need to make, merge this PR.

2023-01-11 15:47 UTC, monotek approved these changes

2023-01-11 15:47 UTC, merged