[prometheus-postgres-exporter] add parameters to helm
prometheus-community/helm-charts pull request #2943
Opened 2023-01-23 16:00 UTC by sinacek

#### What this PR does / why we need it
Allow setup more parameters/flags for [Prometheus postgres exporter](https://github.com/prometheus-community/postgres_exporter#flags ) 

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-01-23 16:17 UTC, monotek requested changes

2023-01-23 16:17 UTC, monotek commented on charts/prometheus-postgres-exporter/Chart.yaml
> +version: 4.1.4
new feature should raise minor version

2023-01-24 09:41 UTC, monotek requested changes

2023-01-24 10:38 UTC, sinacek commented on charts/prometheus-postgres-exporter/templates/deployment.yaml
> +          - "--collector.bgwriter=false"
collectors are enabled by default, so if `disableCollectorBgwriter` is true, then we would like to disable this collector

2023-01-24 10:39 UTC, sinacek commented on charts/prometheus-postgres-exporter/templates/deployment.yaml
> +          - "--disable-settings-metrics=false"
No, it's same like `collector.bgwriter`. I just fixed wrong parameter name to `--collector.database=false`

2023-01-24 10:48 UTC, monotek approved these changes

2023-01-24 10:53 UTC, merged