[prometheus-stackdriver-exporter] Add dropDelegatedProjects to stackdriver-exporter
prometheus-community/helm-charts pull request #296
Opened 2020-11-02 12:32 UTC by opdude

Allow for enabling the ability to drop delegated projects from the scraped data in stackdriver-exporter using the STACKDRIVER_EXPORTER_DROP_DELEGATED_PROJECTS env var.

#### What this PR does / why we need it:

Adds the ability to drop delegated projects from scraped data using the STACKDRIVER_EXPORTER_DROP_DELEGATED_PROJECTS env var.

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-02 15:04 UTC, monotek requested changes
new feature should raise minor version.

2020-11-10 10:19 UTC, opdude commented
@monotek Can you review this one after the changes?

2020-11-10 21:41 UTC, monotek approved these changes

2020-11-10 21:41 UTC, merged

2020-11-12 13:47 UTC, opdude commented
Not sure if you know @monotek  but pushing the latest release of this chart failed. Not sure if a re-run will kick it back into action or something else is needed?

https://github.com/prometheus-community/helm-charts/runs/1382194915?check_suite_focus=true

2020-11-16 10:31 UTC, opdude commented
@prometheus-community/helm-charts-admins Can someone help with the above?

2020-11-16 10:34 UTC, opdude commented
@apenney @rpahli Are you able to help with the above?

2020-11-16 10:54 UTC, rpahli commented
I have currently no change to re-run the build @torstenwalter  can you add me to the prometheus-community as mentioned her: https://github.com/prometheus-community/helm-charts/pull/183#issuecomment-709910061

2020-11-16 12:58 UTC, torstenwalter commented
It's fixed now: https://github.com/prometheus-community/helm-charts/runs/1406404564?check_suite_focus=true
Should be online in a couple of minutes.