[kube-prometheus-stack] Add alertmanager.stringConfig
prometheus-community/helm-charts pull request #2992
Opened 2023-02-06 15:26 UTC by jkroepke

Signed-off-by: Jan-Otto Kröpke <joe@cloudeteer.de>

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #2950

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-02-07 12:29 UTC, monotek requested changes

2023-02-07 12:29 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 44.3.2
new feature should raise minor version

2023-02-09 08:38 UTC, jkroepke commented
@monotek version bumped and rebased

2023-02-10 09:17 UTC, jkroepke commented
I would really appreciate it, if this can be merged soon :)

2023-02-14 13:32 UTC, monotek approved these changes

2023-02-14 13:35 UTC, merged