[kube-prometheus-stack] allow overriding of selector for kube-state-metrics serviceMonitor
prometheus-community/helm-charts pull request #303
Opened 2020-11-04 13:48 UTC by janlud

app.kubernetes.io/instance is overriden by ArgoCD on the service and because of that this serviceMonitor fails to detect the service

Signed-off-by: Jan Ludvik <jan.ludvik@deltatre.com>

#### What this PR does / why we need it:
Allows optionally overriding of kube-state-metrics serviceMonitor.
The reason is that ArgoCD overrides the `app.kubernetes.io/instance` of all deployment so this serviceMonitor cannot then detect anything to scrape.

Using this override will allow any to replace the selector with any value while keeping backwards compatibility with previous versions.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-16 11:49 UTC, vsliouniaev approved these changes

2020-11-17 18:20 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 11.0.1
upgrade the chart version

2020-11-21 16:47 UTC, monotek requested changes
Please merge master and raise minor version, as your pr add new feature.

2020-12-10 08:22 UTC, janlud commented
Sorry it took so long! I updated my branch from master and raised the minor version as requested

2020-12-10 18:38 UTC, monotek approved these changes

2021-01-09 19:51 UTC, monotek submitted a review, later dismissed

2021-01-29 10:25 UTC, vsliouniaev approved these changes

2021-01-29 13:29 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 12.11.0
please sync your fork to resolve the merge conflicts.

2021-01-29 13:30 UTC, gkarthiks reviewed
please bump the chart version

2021-02-04 11:04 UTC, monotek commented
chart version updated

2021-02-04 18:00 UTC, gkarthiks commented
@monotek so sorry. But can you please bump the chart version one more time? 🙏

2021-02-09 11:10 UTC, monotek commented
done :-)
p.s. you should be ablte to do it too...

2021-02-09 18:32 UTC, gkarthiks approved these changes

2021-02-09 18:32 UTC, merged