[prometheus-druid-exporter] support podAnnotations
prometheus-community/helm-charts pull request #306
Opened 2020-11-05 11:54 UTC by AWaterColorPen

Signed-off-by: slyao <slyao@tencent.com>

#### What this PR does / why we need it:

support podAnnotations

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-12 06:12 UTC, AWaterColorPen commented
@prometheus-community/helm-charts-admins @monotek
please help for a review

2020-11-14 13:49 UTC, monotek requested changes
new feature should raise minort version.

2020-11-16 06:58 UTC, AWaterColorPen commented
> new feature should raise minort version.

raise minor version to 0.9.0

2020-11-21 16:34 UTC, monotek approved these changes

2020-11-21 16:34 UTC, merged