[prometheus-postgres-exporter] Add option to change deployment command
prometheus-community/helm-charts pull request #3070
Opened 2023-02-24 18:46 UTC by Vonter

#### What this PR does / why we need it

Adds an option to configure the `command` on the `Deployment` created with `prometheus-postgres-exporter`, similar to the option available in the [`prometheus-cloudwatch-exporter`](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/values.yaml#L15-L27)

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-02-26 14:42 UTC, monotek requested changes
New feature should raise minor version

2023-02-26 18:04 UTC, zanhsieh requested changes

2023-02-26 18:04 UTC, zanhsieh commented on charts/prometheus-postgres-exporter/templates/deployment.yaml
> +          {{- end }}
```suggestion
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
```
```

2023-03-01 18:19 UTC, monotek approved these changes

2023-03-01 18:31 UTC, merged