[prometheus] Remove use of API proxy
prometheus-community/helm-charts pull request #3081
Opened 2023-02-28 08:42 UTC by SuperQ

#### What this PR does / why we need it

Update the defaults for the `prometheus` chart to not use the API proxy to access kubelet and cadvisor metrics. This is not necessary with the ServiceAccount token. This matches the scrape configuration of
`kube-prometheus-stack`.

#### Which issue this PR fixes

- fixes https://github.com/prometheus-community/helm-charts/issues/3079

#### Special notes for your reviewer

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-02-28 08:43 UTC, SuperQ commented
@tomkukral would you be able to test this PR?

2023-03-01 07:46 UTC, tomkukral commented
> @tomkukral would you be able to test this PR?

Yes, I will deploy it today or tomorrow.

2023-03-01 12:47 UTC, tomkukral commented
@SuperQ it doesn't work on my cluster.

![screenshot_2023-03-01_130719](https://user-images.githubusercontent.com/6077499/222136245-0a167de9-8eb0-4f99-9333-9b10a9d28922.png)

I have tried to upgrade to `v2.42.0` but it haven't helped. 

Kubelet don't accept what auth is Prometheus providing
```
Mar 01 13:36:08 a2 kubelet[2867174]: I0301 13:36:08.868237 2867174 httplog.go:131] "HTTP" verb="GET" URI="/metrics/cadvisor" latency="6.949411ms" userAgent="Prometheus/2.42.0" audit-ID="" srcIP="192.168.200.199:49134" resp=403 statusStack=<
Mar 01 13:36:08 a2 kubelet[2867174]:         Mar 01 13:36:08 a2 kubelet[2867174]:         goroutine 11918 [running]:
Mar 01 13:36:08 a2 kubelet[2867174]:         k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc0021c9ad0, 0xc001bdea90?)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:324 +0x90
Mar 01 13:36:08 a2 kubelet[2867174]:         k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc0021c9ad0, 0x1?)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:306 +0x25Mar 01 13:36:08 a2 kubelet[2867174]:         github.com/emicklei/go-restful/v3.(*Response).WriteHeader(...)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/github.com/emicklei/go-restful/v3/response.go:221
Mar 01 13:36:08 a2 kubelet[2867174]:         github.com/emicklei/go-restful/v3.(*Response).WriteErrorString(0xc00066aee0, 0x193?, {0xc0006d1b80, 0x50})Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/github.com/emicklei/go-restful/v3/response.go:201 +0xb7Mar 01 13:36:08 a2 kubelet[2867174]:         k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc001c2c5c0, 0x4647840?, 0xc001c2c501?)Mar 01 13:36:08 a2 kubelet[2867174]:                 pkg/kubelet/server/server.go:314 +0x596Mar 01 13:36:08 a2 kubelet[2867174]:         github.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter(0x74656d2f33312e38?, 0x4e920a8?, 0xc001c2c5a0?)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/github.com/emicklei/go-restful/v3/filter.go:21 +0x47Mar 01 13:36:08 a2 kubelet[2867174]:         github.com/emicklei/go-restful/v3.(*Container).HandleWithFilter.func1({0x4e920a8?, 0xc001c2c5a0}, 0xc001f8c400)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/github.com/emicklei/go-restful/v3/container.go:397 +0x297Mar 01 13:36:08 a2 kubelet[2867174]:         net/http.HandlerFunc.ServeHTTP(0xc00109c750?, {0x4e920a8?, 0xc001c2c5a0?}, 0x0?)Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/server.go:2109 +0x2f Mar 01 13:36:08 a2 kubelet[2867174]:         github.com/emicklei/go-restful/v3.(*Container).Handle.func1({0x4e920a8?, 0xc001c2c5a0?}, 0x0?)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/github.com/emicklei/go-restful/v3/container.go:380 +0x14dMar 01 13:36:08 a2 kubelet[2867174]:         net/http.HandlerFunc.ServeHTTP(0x40e90b?, {0x4e920a8?, 0xc001c2c5a0?}, 0xc0023d5a88?)Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/server.go:2109 +0x2fMar 01 13:36:08 a2 kubelet[2867174]:         net/http.(*ServeMux).ServeHTTP(0xc000a6fe98?, {0x4e920a8, 0xc001c2c5a0}, 0xc001f8c400)
Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/server.go:2487 +0x149Mar 01 13:36:08 a2 kubelet[2867174]:         github.com/emicklei/go-restful/v3.(*Container).ServeHTTP(0x4e93e20?, {0x4e920a8?, 0xc001c2c5a0?}, 0x4e56048?)Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/github.com/emicklei/go-restful/v3/container.go:316 +0x1f5Mar 01 13:36:08 a2 kubelet[2867174]:         k8s.io/apiserver/pkg/server/httplog.withLogging.func1({0x4e90e18, 0xc000a6fe98}, 0xc001f8c200)
Mar 01 13:36:08 a2 kubelet[2867174]:                 vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:130 +0x339Mar 01 13:36:08 a2 kubelet[2867174]:         net/http.HandlerFunc.ServeHTTP(0xc0004fc800?, {0x4e90e18?, 0xc000a6fe98?}, 0x4?)Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/server.go:2109 +0x2fMar 01 13:36:08 a2 kubelet[2867174]:         k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc0001d0c80, {0x4e90e18, 0xc000a6fe98}, 0xc001f8c200)Mar 01 13:36:08 a2 kubelet[2867174]:                 pkg/kubelet/server/server.go:1049 +0x662Mar 01 13:36:08 a2 kubelet[2867174]:         net/http.serverHandler.ServeHTTP({0x713ff60?}, {0x4e90e18, 0xc000a6fe98}, 0xc001f8c200)
Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/server.go:2947 +0x30c
Mar 01 13:36:08 a2 kubelet[2867174]:         net/http.initALPNRequest.ServeHTTP({{0x4e92b18?, 0xc002f080c0?}, 0xc00073c380?, {0xc0006b6780?}}, {0x4e90e18, 0xc000a6fe98}, 0xc001f8c200)
Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/server.go:3556 +0x245
Mar 01 13:36:08 a2 kubelet[2867174]:         net/http.(*http2serverConn).runHandler(0xc0021fcba0?, 0x0?, 0x0?, 0x0?)
Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/h2_bundle.go:5910 +0x78
Mar 01 13:36:08 a2 kubelet[2867174]:         created by net/http.(*http2serverConn).processHeaders
Mar 01 13:36:08 a2 kubelet[2867174]:                 /usr/lib/golang/src/net/http/h2_bundle.go:5645 +0x5b9
Mar 01 13:36:08 a2 kubelet[2867174]:  > addedInfo=<
Mar 01 13:36:08 a2 kubelet[2867174]:
Mar 01 13:36:08 a2 kubelet[2867174]:         logging error output: "Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=metrics)"
Mar 01 13:36:08 a2 kubelet[2867174]:  >
```
Can you provide more information about what kind of auth method is Prometheus using? I can do more debug. My Kubernetes is 1.25, almost default installation by `kubeadm`.

There were some changes regarding ServiceAccount secrets in 1.24 ... is Prometheus using this?

2023-03-01 15:29 UTC, SuperQ commented
Sorry, I don't actually know what the access control stuff is supposed to be in this configuration. I guess more research is required.

2023-03-01 15:46 UTC, tomkukral commented
Ok, no problem. I will try to do research. Do you have any working cluster with this configuration so I can replicate it?

2023-03-01 16:31 UTC, tomkukral commented
Can you give me dump of clusterroles and service accounts which were created by operator? I'd like to replicate same behavior

2023-03-01 16:34 UTC, SuperQ commented
You should be able to produce this locally from the helm-charts repo:

```
helm dependency build kube-prometheus-stack
helm template test kube-prometheus-stack
```

2023-03-16 15:44 UTC, tomkukral commented
![screenshot_2023-03-16_164225](https://user-images.githubusercontent.com/6077499/225672183-df13f58c-bd9e-4786-b3e3-1174a498b904.png)

Confirmed working on `kube-prometheus-stack`. Now I will try to investigate which auth is it using.

Just a small node for somebody trying to replicate it `helm template test kube-prometheus-stack` won't do CRD so you have to use `helm install` or include CRD by command for template.

2023-03-16 20:11 UTC, tomkukral commented
I seems to be incorrect default configuration of `kubeadm`.

When I have edited file `/etc/systemd/system/kubelet.service.d/kubeadm.conf` and commented line
```
#Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
```
then prometheus is able to use direct kubelet scraping without proxy. I will verify consequences of commenting this line.

2023-03-16 22:02 UTC, tomkukral commented
Token is valid and recognized by apiserver
```
 curl http://localhost:8001/apis/authentication.k8s.io/v1/tokenreviews -X POST -H 'Content-Type: application/json; charset=utf-8' -d @tokenreview.json
{
  "kind": "TokenReview",
  "apiVersion": "authentication.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null,
    "managedFields": [
      {
        "manager": "curl",
        "operation": "Update",
        "apiVersion": "authentication.k8s.io/v1",
        "time": "2023-03-16T22:00:32Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:spec": {
            "f:token": {}
          }
        }
      }
    ]
  },
  "spec": {
    "token": "ey..."
  },
  "status": {
    "authenticated": true,
    "user": {
      "username": "system:serviceaccount:prometheus:prometheus-server",
      "uid": "af27ed64-a39c-452b-bd7c-ec09605833e8",
      "groups": [
        "system:serviceaccounts",
        "system:serviceaccounts:prometheus",
        "system:authenticated"
      ],
      "extra": {
        "authentication.kubernetes.io/pod-name": [
          "prometheus-server-cd9577fdf-7m4pz"
        ],
        "authentication.kubernetes.io/pod-uid": [
          "d66c9da7-af9f-4de5-b244-04e09a06d2f4"
        ]
      }
    },
    "audiences": [
      "https://kubernetes.default.svc.k8s"
    ]
  }
}
```

2023-04-26 06:56 UTC, tomkukral commented
It must be related to some configuration of webhook auth. I must find some time to dig deeper. Not stale.

2023-06-30 20:59 UTC, tomkukral commented
Testing it again on new installation

2023-06-30 21:17 UTC, tomkukral commented
@SuperQ can you rebase your branch? I don't have permission to do it.

2023-07-01 10:07 UTC, SuperQ commented
@tomkukral Done, let me know if there are other changes that need to be made.

2023-08-07 07:16 UTC, SuperQ commented
Not stale.

2023-09-17 06:05 UTC, SuperQ commented
Not stale

2023-12-15 06:55 UTC, SuperQ commented
Not stale.

2024-03-10 05:23 UTC, zanhsieh requested changes

2024-03-10 05:23 UTC, zanhsieh commented on charts/prometheus/Chart.yaml
>  version: 25.17.0
```suggestion
version: 25.17.1
```

2024-04-22 12:46 UTC, SuperQ commented
Still not stale.

2025-02-01 00:06 UTC, closed without merging