Change chart PSP default state to off
prometheus-community/helm-charts pull request #3127
Opened 2023-03-16 02:40 UTC by azend

#### What this PR does / why we need it
The helm chart for the `prometheus-kafka-exporter` defaults to using the included PSP. PSPs have been deprecated now and are removed in K8s v1.25. K8s v1.25 is out, stable, and in general circulation. It doesn't make sense to default to chart values that break the chart on upgrade or prevent installation in the case of a new installation.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- N/A - References no ticket created for this issue.

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-26 06:19 UTC, zanhsieh requested changes
@azend 
Thanks for the contribution. Would you mind to bump the version in Chart.yaml to latest so the CI could merge this PR later on please?

2023-05-31 23:16 UTC, zanhsieh requested changes

2023-05-31 23:16 UTC, zanhsieh commented on charts/prometheus-kafka-exporter/Chart.yaml
> +version: 3.0.0
I would say bumping the minor version would be better.

2023-06-01 14:08 UTC, zanhsieh approved these changes

2023-06-01 14:11 UTC, zeritti approved these changes

2023-06-01 14:14 UTC, merged