[kube-prometheus-stack] Additional labels for ServiceMonitors
prometheus-community/helm-charts pull request #3132
Opened 2023-03-17 17:38 UTC by nlamirault

#### What this PR does / why we need it

This PR adds support for additional labels on the ServiceMonitor resource created for Alertmanager, Prometheus, ThanosRuler and ThanosSidecar  deployment.

Same behavior of PrometheusOperator ServiceMonitor and exporter ServiceMonitor (core-dns, kube-api-server, kubelet, ...)

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-03-30 07:59 UTC, QuentinBisson commented
Can you bump the minor version? @monotek could you review when you have time?

2023-03-30 11:08 UTC, monotek requested changes

2023-03-30 11:08 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 45.7.2
```suggestion
version: 45.9.0
```

2023-03-30 11:09 UTC, monotek approved these changes

2023-03-31 05:47 UTC, dotdc approved these changes
LGTM, can we merge?

2023-04-04 09:02 UTC, merged