[kube-prometheus-stack] fix kps deployment when thanos field is set to null
prometheus-community/helm-charts pull request #3163
Opened 2023-03-27 22:25 UTC by renjugeo

kps deployment fails when disabling thanos sidecar by setting `prometheus.prometheusSpec.thanos` field to null due to the reference of a field `thanos.secretProviderClass` in csi-secret.yaml. This change gives the ability to disable thanos sidecar by setting `prometheus.prometheusSpec.thanos=null`

#### What this PR does / why we need it
This PR fixes the kps deployment failure when `prometheus.prometheusSpec.thanos` field is set to null and thus gives the ability to disable thanos sidecar by setting `prometheus.prometheusSpec.thanos=null` in the overriding values files.

#### Which issue this PR fixes

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-03-30 18:05 UTC, renjugeo commented
@monotek could you review this please?

2023-04-04 09:02 UTC, monotek requested changes
chart version needs to be raised

2023-04-04 09:09 UTC, renjugeo commented
@monotek updated chart version

2023-04-04 16:23 UTC, monotek approved these changes

2023-04-05 16:56 UTC, monotek approved these changes

2023-04-05 18:56 UTC, merged