[prometheus] Add support for pod topology spread constraints
prometheus-community/helm-charts pull request #3183
Opened 2023-04-02 16:24 UTC by zeritti

Signed-off-by: zeritti <47476160+zeritti@users.noreply.github.com>
#### What this PR does / why we need it

With this PR I am proposing to introduce support for [pod topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) in deployment and statefulset templates allowing for desired distribution of Prometheus' pods across zones and nodes.

#### Which issue this PR fixes

- fixes #3164

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-02 22:02 UTC, zanhsieh requested changes

2023-04-02 22:02 UTC, zanhsieh commented on charts/prometheus/templates/deploy.yaml
>      {{- end }}
```suggestion
    {{- with .Values.server.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | indent 8 }}
    {{- end }}
```

2023-04-03 05:55 UTC, zeritti commented on charts/prometheus/templates/deploy.yaml
>      {{- end }}
Thank you, @zanhsieh, changed.

2023-04-03 07:08 UTC, zanhsieh approved these changes

2023-04-05 12:41 UTC, merged