prometheus-node-exporter - Patch nodeSelector on node-exporter daemonset
prometheus-community/helm-charts pull request #3190
Opened 2023-04-04 19:11 UTC by marciogmorales

#### What this PR does / why we need it

On a heterogenous Kubernetes cluster with Windows nodes, the daemonset pods try to be scheduled on all nodes as it doesn't have noSelector by OS type, and Linux is the only one supported for node-exporter.

This proposed change adds the kubernetes.io/os: Linux as nodeSelector in order to avoid failed loop on pod scheduling on Windows nodes.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

I'm starting addressing the node-exporter daemonset, however the same fix will be needed on other prometheus deployments, which I'll work on once this PR is merged to the main.

#### Checklist

- [] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-04 19:32 UTC, zanhsieh requested changes
@marciogmorales 
Thanks for the contribution. Beside the change I suggested, would you mind to bump the version in Chart.yaml so the CI can merge this PR please?

2023-04-04 19:32 UTC, zanhsieh commented on charts/prometheus-node-exporter/templates/daemonset.yaml
> +        kubernetes.io/os: {{ .Values.nodeselector.os }}
I would let the users picks their own generic purpose spec here:

```suggestion
      {{- with .Values.nodeselector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2023-04-04 19:32 UTC, zanhsieh commented on charts/prometheus-node-exporter/values.yaml
> +  os: linux
Set to `{}` as backward compatible.
```suggestion
nodeselector: {}
#   kubernetes.io/os: linux
```

2023-04-05 14:27 UTC, marciogmorales commented
@zanhsieh I think we will need to force the nodeSelector to Linux OS and not let it as optional value, because the Chart deployment fails on an heterogeneous cluster. Thoughts?

2023-04-05 14:53 UTC, zanhsieh commented
> @zanhsieh I think we will need to force the nodeSelector to Linux OS and not let it as optional value, because the Chart deployment fails on an heterogeneous cluster. Thoughts?

As long as that's backward compatible, I am fine with it.

2023-04-05 14:56 UTC, marciogmorales commented
> 

Should I re-write the code as I did in the first modification?

2023-04-05 19:23 UTC, marciogmorales reviewed
Fixed several inconsistent that parameters were referenced to wrong values. Added nodeSelector to be mapped to Linux instead of an optional value.

2023-04-06 01:55 UTC, zanhsieh requested changes

2023-04-06 01:55 UTC, zanhsieh commented on charts/prometheus-node-exporter/templates/daemonset.yaml
> -      {{- end }}
@marciogmorales 
Could you put back the `tolerations` please?

2023-04-06 21:00 UTC, marciogmorales reviewed
Removing empty 278 line

2023-04-09 02:53 UTC, zanhsieh requested changes

2023-04-09 02:53 UTC, zanhsieh commented on charts/prometheus-node-exporter/templates/daemonset.yaml
> +      {{- with .Values.nodeselector }}
@marciogmorales 
You miss an `{{- end }}` in line 278 if you'd like to keep `{{- with .Values.nodeselector }}`.

2023-04-11 16:04 UTC, marciogmorales commented
Thank you @zanhsieh . Fixed the issue.

2023-05-30 14:19 UTC, jcpunk commented
I'll confess some interest in this.

2023-05-31 13:35 UTC, jcpunk commented on charts/prometheus-node-exporter/templates/daemonset.yaml
> +      {{- with .Values.affinity }}
These `with` blocks look wrong to me...

2023-05-31 23:12 UTC, merged