[prometheus-smartctl-exporter]: expose serviceMonitor `interval` and `scrapeTimeout`
prometheus-community/helm-charts pull request #3197
Opened 2023-04-06 08:52 UTC by yellowhat

#### What this PR does / why we need it

* expose serviceMonitor `interval` option
* expose serviceMonitor `scrapeTimeout` option

#### Which issue this PR fixes

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-smartctl-exporter]`)

2023-04-06 16:05 UTC, kfox1111 approved these changes
lgtm

2023-04-13 11:09 UTC, yellowhat commented
@kfox1111 may I ask for a review?

Thanks

2023-04-13 17:29 UTC, kfox1111 approved these changes
lgtm

2023-04-13 20:52 UTC, yellowhat commented
@kfox1111 may I ask for an approval?

Thanks

2023-04-13 20:53 UTC, kfox1111 submitted a review, later dismissed
lgtm

2023-04-13 20:53 UTC, kfox1111 commented
Not sure I have enough permissions to do so. I tried.

2023-04-13 20:54 UTC, yellowhat commented
It is still "Review required"

2023-04-14 12:55 UTC, yellowhat commented
@kfox1111 can you suggest who can I tag to approve it?

Thanks

2023-04-14 16:55 UTC, kfox1111 commented
I think @zanhsieh approved your last one.

2023-04-14 16:55 UTC, kfox1111 submitted a review, later dismissed

2023-04-15 00:40 UTC, zanhsieh approved these changes

2023-04-15 00:42 UTC, zanhsieh requested changes

2023-04-15 00:42 UTC, zanhsieh commented on charts/prometheus-smartctl-exporter/templates/servicemonitor.yaml
> +    {{- end }}
Why not go with `{{ with }}` ?
```suggestion
    {{- with .Values.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
```

2023-04-15 08:31 UTC, yellowhat commented
@zanhsieh What about now?

2023-04-15 17:04 UTC, zanhsieh approved these changes

2023-04-15 17:04 UTC, merged