[charts/alertmanager] Adding hostAliases to Alertmanager chart.
prometheus-community/helm-charts pull request #3209
Opened 2023-04-10 03:19 UTC by DandyDeveloper

@monotek @naseemkullah 

#### What this PR does / why we need it
Adding hostAlises support to the Alertmanager chart. This is a necessary requirement for my organization due to some interesting network decisions. 

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-10 11:24 UTC, naseemkullah approved these changes

2023-04-11 04:00 UTC, DandyDeveloper commented
@naseemkullah Looks like we need some approval to run workflows as well?

2023-04-11 09:27 UTC, monotek requested changes

2023-04-11 09:27 UTC, monotek commented on charts/alertmanager/values.yaml
> +hostAliases: {}
```suggestion

hostAliases: {}
```

2023-04-11 09:27 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 0.27.1
new feature should raise minor version

2023-04-13 08:38 UTC, DandyDeveloper commented
@naseemkullah Seems I need re-approval :)

2023-04-13 14:45 UTC, monotek requested changes

2023-04-13 14:52 UTC, monotek approved these changes

2023-04-13 14:52 UTC, merged