[prometheus-operator-admission-webhook] Bump application version to 0.64.0
prometheus-community/helm-charts pull request #3229
Opened 2023-04-12 18:57 UTC by zeritti

Signed-off-by: zeritti <47476160+zeritti@users.noreply.github.com>

#### What this PR does / why we need it
This PR bumps the admission webhook application to release 0.64.0.

#### Which issue this PR fixes
None

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-14 16:58 UTC, zeritti commented
@monotek Will you please review this PR and merge if ok as the chart does not have a reviewer. I would appreciate it, indeed.

2023-04-15 00:59 UTC, zanhsieh requested changes
@zeritti 
Thank you for the contribution. Since you bump the minor version, does it mean the users need to know something to prevent breaking if they'd like to upgrade? If yes, would you mind to write it up in Upgrade Chart section of README.md file?

2023-04-15 07:25 UTC, zeritti commented
@zanhsieh Thank you. No, there is no such change present in the release that would need to be mentioned in an upgrade note.

2023-04-15 17:05 UTC, zanhsieh approved these changes

2023-04-15 17:07 UTC, merged