[kube-prometheus-stack] Allow setting persistence settings for grafana
prometheus-community/helm-charts pull request #323
Opened 2020-11-07 11:26 UTC by wilsonge

#### What this PR does / why we need it:
Allows persisting grafana storage to a PV - meaning that no dashboard setups get lost when pods get deleted.

#### Notes to reviewers
Relevent options in grafana helm chart https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L230-L244 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-09 17:44 UTC, bismarck requested changes
Not sure why this is needed in the kube-prometheus-stack chart since you can already override this?  Dashboards should already persist across restarts since they're stored as configmaps.

2020-11-09 17:46 UTC, closed without merging

2020-11-11 01:43 UTC, Vickey-Wu commented
I have the same request, i need to persistent my grafana dashbaord, when i delete and deploy it again i lost my dashboard

2020-11-11 04:55 UTC, scottrigby commented
@bismarck is right. A user may override any values of a dependent chart from the parent, it's not required to explicitly specify those in the parent chart's values file.

2020-11-11 06:02 UTC, Vickey-Wu commented
> @bismarck is right. A user may override any values of a dependent chart from the parent, it's not required to explicitly specify those in the parent chart's values file.

Hi, could you please show me how to override values to persistent grafana data even when i delete and deploy it again. Thank you!

2020-11-11 13:11 UTC, wilsonge commented
You need to set enabled to true ;)

2020-11-11 13:26 UTC, Vickey-Wu commented
> You need to set enabled to true ;)

Sorry, I didn't notice that...