[prom-label-proxy] add ServiceMonitor suuport
prometheus-community/helm-charts pull request #3249
Opened 2023-04-17 16:55 UTC by kariya-mitsuru

#### What this PR does / why we need it

Metrics is supported since app version 0.6.0, so add metrics port settings and ServiceMonitor settings.

#### Which issue this PR fixes

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-05-26 14:32 UTC, monotek requested changes

2023-05-26 14:32 UTC, monotek commented on charts/prom-label-proxy/Chart.yaml
> +version: 0.2.1
new feature should raise minor version

2023-05-28 09:09 UTC, jkroepke reviewed
LGTM, please address the comments from monotek

2023-05-30 10:52 UTC, monotek approved these changes

2023-05-30 11:41 UTC, jkroepke approved these changes

2023-05-30 11:41 UTC, merged