[.github meta resource] Refactor current bug template to request more information
prometheus-community/helm-charts pull request #326
Opened 2020-11-08 22:29 UTC by fktkrt

Signed-off-by: fktkrt <fktkrt@gmail.com>

#### What this PR does / why we need it:

This PR extends the bug-temaplate currently in use with useful context informations. The goal of this PR to acquire more details for each bug reports, hence fixing the issue faster.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped (although this might not be needed in this case)
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-09 05:52 UTC, torstenwalter requested changes
Can you revert changes in Chart.yaml. it's not necessary to bump a chart version of you only modify files outside of charts directory.

2020-11-09 08:16 UTC, fktkrt commented
> Can you revert changes in Chart.yaml. it's not necessary to bump a chart version of you only modify files outside of charts directory.

Sure, it's done.

2020-11-09 12:05 UTC, torstenwalter commented on .github/ISSUE_TEMPLATE/bug_report.md
> +``**
```suggestion
```
```

To close the console block from above.

2020-11-10 05:15 UTC, gkarthiks commented
seems @fktkrt you have to do the DCO

2020-11-10 05:16 UTC, gkarthiks reviewed
/lgtm, just the DCO is blocking

2020-11-10 21:32 UTC, monotek approved these changes

2020-11-11 04:19 UTC, torstenwalter requested changes
@fktkrt you marked https://github.com/prometheus-community/helm-charts/pull/326/files#r519758839 as resolved, but I think the issue is still present.

2020-11-11 18:01 UTC, fktkrt commented
> @fktkrt you marked https://github.com/prometheus-community/helm-charts/pull/326/files#r519758839 as resolved, but I think the issue is still present.

You're right, sorry, it's fixed now.
I hope the effects of these changes are are making up the review time for this simple PR in the long run. :)

2020-11-11 20:53 UTC, torstenwalter approved these changes

2020-11-11 20:54 UTC, merged

2020-11-11 20:58 UTC, torstenwalter commented
@fktkrt If you would know how often I missed something ;-)

Thanks for the improved template 💯