[alertmanager] - 3286 Enahance test connection template
prometheus-community/helm-charts pull request #3294
Opened 2023-04-27 00:31 UTC by jkutes

#### What this PR does / why we need it
Ability to enable/disable Alertmanager test connection pod and pass annotations via values.yaml
This is needed to control the pod in more complicated multi chart deployment and istio sidecar.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #3286 

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-27 07:29 UTC, monotek requested changes

2023-04-27 07:29 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 0.29.1
new feature should raise minor version

2023-04-27 08:12 UTC, monotek requested changes

2023-04-27 08:12 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 0.29.1
```suggestion
version: 0.30.0
```

2023-04-27 16:09 UTC, jkutes reviewed
make sense
Naseem, please approve!

2023-04-28 10:47 UTC, monotek requested changes

2023-04-28 10:47 UTC, monotek commented on charts/alertmanager/values.yaml
> +  enabled: true
Should we enable that by deafult?
I would let it disabled.

```suggestion
  enabled: false
```

2023-04-28 16:36 UTC, jkutes commented
Gentlemen, if you would approve.
Thank you.

2023-05-01 19:33 UTC, jkutes commented
How can get this approved?

2023-05-01 19:39 UTC, monotek approved these changes

2023-05-01 19:39 UTC, merged