[prometheus] Make Prometheus configmap reload can have custom reload url
prometheus-community/helm-charts pull request #3298
Opened 2023-04-27 09:34 UTC by nguyenhoaibao

#### What this PR does / why we need it

So we can custom the reload url to make it work with basic authentication, for example.

#### Which issue this PR fixes

- fixes #3295 

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-04-27 14:25 UTC, zanhsieh requested changes

2023-04-27 14:25 UTC, zanhsieh commented on charts/prometheus/templates/sts.yaml
> +          {{- end }}
```suggestion
          {{- $default_url := printf "http://127.0.0.1:9090/%s/-/reload" .Values.server.prefixURL }}
          - --reload-url={{ default $default_url .Values.configmapReload.reloadUrl }}
```

2023-04-27 14:25 UTC, zanhsieh commented on charts/prometheus/templates/deploy.yaml
> +          {{- end }}
```suggestion
          {{- $default_url := printf "http://127.0.0.1:9090/%s/-/reload" .Values.server.prefixURL }}
          - --reload-url={{ default $default_url .Values.configmapReload.reloadUrl }}
```

2023-04-28 01:55 UTC, nguyenhoaibao commented on charts/prometheus/templates/sts.yaml
> +          {{- end }}
Done

2023-04-28 01:56 UTC, nguyenhoaibao commented on charts/prometheus/templates/deploy.yaml
> +          {{- end }}
Done

2023-04-28 08:33 UTC, zanhsieh approved these changes

2023-04-28 15:05 UTC, zanhsieh approved these changes

2023-04-29 01:02 UTC, merged