[prometheus-pushgateway] fix apiVersion for PDB
prometheus-community/helm-charts pull request #3300
Opened 2023-04-27 10:59 UTC by akamac

2023-04-29 01:05 UTC, zanhsieh requested changes
@akamac 
Thank you for the contribution. Would you mind to bump the version in Chart.yaml so the CI would get it merged once approved?

2023-05-02 19:26 UTC, akamac commented
> @akamac Thank you for the contribution. Would you mind to bump the version in Chart.yaml so the CI would get it merged once approved?

done

2023-05-04 22:11 UTC, zanhsieh approved these changes

2023-05-08 20:18 UTC, zeritti approved these changes

2023-05-08 20:20 UTC, merged