[prometheus-postgres-exporter] Correct role
prometheus-community/helm-charts pull request #3395
Opened 2023-05-17 16:49 UTC by zeritti

#### What this PR does / why we need it

If PodSecurityPolicy API is not available in a cluster, a `use` permission on resources `podsecuritypolicies` should not be created through the role template.

#### Which issue this PR fixes

None

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-05-18 01:57 UTC, zanhsieh requested changes

2023-05-18 01:57 UTC, zanhsieh commented on charts/prometheus-postgres-exporter/templates/role.yaml
> +{{- if (and .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy")) }}
Extra `(` `)` should not be necessary.
```suggestion
{{- if and .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
```

2023-05-18 07:01 UTC, zeritti commented on charts/prometheus-postgres-exporter/templates/role.yaml
> +{{- if (and .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy")) }}
Corrected, thank you.

2023-05-20 14:50 UTC, zanhsieh approved these changes

2023-05-20 14:50 UTC, merged