[kube-prometheus-stack] - resolve issue 3396, no null labels allowed for PrometheusRules
prometheus-community/helm-charts pull request #3400
Opened 2023-05-18 21:31 UTC by scott-grimes

#### What this PR does / why we need it

Resolves bug for issue #3396 , PrometheusRule cannot have null labels

#### Which issue this PR fixes

- fixes #3396

#### Special notes for your reviewer

If the given rule does not already have a label, and the user has not passed in their own, the empty `labels:` field is now omitted 

```diff
 expr: |-
        kube_pod_container_resource_limits{resource="cpu",job="kube-state-metrics"}  * on (namespace, pod, cluster)
        group_left() max by (namespace, pod, cluster) (
         (kube_pod_status_phase{phase=~"Pending|Running"} == 1)
         )
      record: cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits
+     {{- if .Values.defaultRules.additionalRuleLabels }}
      labels:
-{{- if .Values.defaultRules.additionalRuleLabels }}
-{{ toYaml .Values.defaultRules.additionalRuleLabels | indent 8 }}
-{{- end }}
+        {{ toYaml .Values.defaultRules.additionalRuleLabels | nindent 8 }}
+     {{- end }}
```

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-05-18 21:43 UTC, buroa submitted a review, later dismissed

2023-05-19 08:27 UTC, GMartinez-Sisti requested changes
LGTM. Can you please check the comments?

2023-05-19 08:27 UTC, GMartinez-Sisti commented on charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-state-metrics.yaml
> +        sum( 2 ^ max by (cluster, shard_ordinal) (kube_state_metrics_shard_ordinal{job="kube-state-metrics"}) ) by (cluster)
Same as above.

2023-05-19 08:27 UTC, GMartinez-Sisti requested changes
LGTM. Can you please check the comments?

2023-05-22 10:45 UTC, buroa commented
@scott-grimes Some comments requiring your attention here.

2023-05-22 13:39 UTC, scott-grimes commented
Was not intended to add the "cluster" filter. Looks like the sources of the manifests have always just pointed to the `main` branch of `prometheus-operator/kube-prometheus` instead of a pinned release 😬 

https://github.com/prometheus-community/helm-charts/blob/b7cfb524bebd1012019e6985219ac9f81209c8a8/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L46C105-L48

Recent changes at the source picked up:

https://github.com/prometheus-operator/kube-prometheus/pull/2111/files#diff-3285fbe8a2541da1df55e88100cbfcc04f6bb1df77402a3e6a846beda3aa05c5

2023-05-22 14:42 UTC, GMartinez-Sisti approved these changes

2023-05-22 16:32 UTC, scott-grimes commented
@GMartinez-Sisti done!

2023-05-22 17:10 UTC, GMartinez-Sisti approved these changes

2023-05-22 17:12 UTC, buroa approved these changes

2023-05-22 17:32 UTC, merged