[prometheus] added support for external_labels to server.global section of prometheus chart.
prometheus-community/helm-charts pull request #342
Opened 2020-11-11 07:01 UTC by hoffmanntravis

#### What this PR does / why we need it:
Adds support for external_labels to prometheus chart.  This is especially useful for thanos as it requires these external labels.  Additional detail in issue below.
#### Which issue this PR fixes
Addresses this issue:
https://github.com/prometheus-community/helm-charts/issues/340
Note that this worked in my testing, but there may be a better approach.  This is very much a _proposed_ change

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-11 07:11 UTC, hoffmanntravis commented
This is working in my limited example that I tested and deploy. The values showed up in the config as expected and Thanos picked them up. However, I'll relent that there may be a better way of doing this overall or something I have missed, so only approve accordingly. Also, this is my first PR to this repo so if I missed the mark anywhere my apologies.

Prometheus log snippet:
level=info ts=2020-11-11T06:36:34.734523631Z caller=reloader.go:222 component=reloader msg="started watching config file and recursively rule dirs for changes" cfg= out= dirs=
level=info ts=2020-11-11T06:36:35.745115859Z caller=sidecar.go:165 msg="successfully loaded prometheus external labels" **external_labels="{environment=\"dev\", region=\"cae\"}**"
level=info ts=2020-11-11T06:36:35.74516196Z caller=intrumentation.go:48 msg="changing probe status" status=ready

2020-11-14 13:19 UTC, monotek requested changes
I alos don't see where the "external_labels" var is used in the chart?

2020-11-14 13:19 UTC, monotek commented on charts/prometheus/values.yaml
> +    external_labels: {}
This should be camelcase

2020-11-14 13:19 UTC, monotek commented on charts/prometheus/Chart.yaml
> +version: 11.16.9
New feature should raise minor version.

2020-11-16 05:17 UTC, hoffmanntravis commented
@monotek 

> I alos don't see where the "external_labels" var is used in the chart?

I was thinking the line below, but after running some more tests I think I was incorrect on the premise of this PR.  I thought I needed to add the value explicitly for the helm chart to pick it up.  However, unless I am missing something in the test deploys I just ran, I think it's pulling in the value through the line below despite it not being explicitly set in values.yml.  If you can indeed override values without specifically setting them in the values.yml I believe this PR is not needed and can be abandoned.

https://github.com/prometheus-community/helm-charts/blob/4346bfad3b8d4a77ccb9cb276406bca8a846d7e5/charts/prometheus/templates/server/cm.yaml#L16

2020-11-17 23:20 UTC, hoffmanntravis commented
Closing as I don't think this is needed per comments above and linked issue

2020-11-17 23:20 UTC, closed without merging