[prometheus-windows-exporter] Add chart
prometheus-community/helm-charts pull request #3476
Opened 2023-06-08 00:33 UTC by jkroepke

#### What this PR does / why we need it

Add helm chart for windows export.

Tested on a AKS with WS 2022 nodes.

<img width="1264" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/1560587/7b85d29a-ed85-4f63-b770-57cabd3cffd8">

<img width="1503" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/1560587/9cdc8ce1-6df1-457a-8347-82077f492e81">

Based on https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/kubernetes.md

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-06-08 09:32 UTC, monotek requested changes

2023-06-08 09:39 UTC, jkroepke commented on charts/prometheus-windows-exporter/Chart.yaml
> +version: 1.0.0
Done

2023-06-08 09:39 UTC, jkroepke commented on charts/prometheus-windows-exporter/README.md
> +## Upgrading Chart
Done

2023-06-12 11:45 UTC, monotek reviewed
How do we actualy test this?
Is the exporter binary not a windows exe file and we would need windows nodes?

2023-06-12 11:57 UTC, jkroepke commented
In theory, yet. We need a Linux node for the control plane (because there are not windows container for the Kubernetes control plane) and a windows nodes for the binary itself. It can be archived through WSL....

I guess the complexity of such an test environment are high that no one could maintain this here.

tbh, we can not test this in GH Actions.

2023-06-12 19:13 UTC, jkroepke commented
@monotek But we are still testing, if the manifests are valid and does not contain any error. However the DaemonSet will have replica 0 on the GH action pipelines. Theoretically, it chart itself is tested.

2023-06-13 09:12 UTC, jkroepke commented
I'm plan to use the helm chart in one of our managed service project. 

@lippertmarkus if you have the time, maybe you can also this chart on your infrastructure?

2023-06-18 08:39 UTC, jkroepke commented
@monotek how to move forward here?

2023-06-20 09:41 UTC, monotek commented
I don't have any windows nodes.

2023-06-20 11:42 UTC, monotek commented
So you have testet the chart now on your windows nodes?

2023-06-20 15:15 UTC, jkroepke commented
@monotek Yes. The screenshot form first post document that it works.

I setup an AKS cluster in azure with windows nodes on a personal subscription from my company. With AKS, it's a no brainer to setup windows nodes.

2023-06-20 15:16 UTC, monotek approved these changes

2023-06-20 15:16 UTC, merged