Fix indentation to allow IDE collapse of sections
prometheus-community/helm-charts pull request #350
Opened 2020-11-12 08:44 UTC by foxylion

When a comment has not the same indentation as the other items
an IDE like VS Code will collapse only the section above until
the comment that is not correctly indented.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-12 08:59 UTC, foxylion commented
I have added the line "Signed-off-by: ..." to my commit message. A version bump is not needed, this does not change the behavior of the chart.

2020-11-14 13:51 UTC, monotek requested changes
please raise chart version

2020-11-14 14:09 UTC, foxylion commented
@monotek I did now.

2020-11-14 14:23 UTC, monotek approved these changes

2020-11-15 02:51 UTC, gkarthiks approved these changes

2020-11-15 02:51 UTC, merged