[prometheus-stackdriver-exporter] make deployment env value configurable
prometheus-community/helm-charts pull request #3513
Opened 2023-06-20 15:45 UTC by prune998

#### What this PR does / why we need it

So far, Golang apps deployed in Kubernetes start with a `GOMAXPROCS` defined to the total number of cores/CPU on the node.

This leads to high throttling and under-performance by creating too many goroutines.

This PR adds a way to configure the `env` portion of the deployment so we can set any env variable, inclusing the `GOMAXPROCS` one.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes none

#### Special notes for your reviewer

From a prod GKE cluster, here's the `stackdriver-exporter` deployed using `100m` request CPU on a 8 node server: 25% of the request is used:

![image](https://github.com/prometheus-community/helm-charts/assets/1110398/c10ec464-30d6-4754-b092-b894bb43c350)

After adding the `GOMAXPROCS=1` env variable, CPU usage is down to 16%:

![image](https://github.com/prometheus-community/helm-charts/assets/1110398/6842fbf3-4628-4bdc-8a1b-e1bf5f98e057)

Another solution would be to use https://github.com/uber-go/automaxprocs in the `stackdriver-exporter`, but it's not a bad idea to make the `env` configurable anyways.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-06-22 07:04 UTC, rpahli requested changes

2023-06-22 12:47 UTC, prune998 commented on charts/prometheus-stackdriver-exporter/templates/deployment.yaml
> +          {{- if or .Values.stackdriver.serviceAccountSecret .Values.stackdriver.serviceAccountKey }}
and is it a problem ? Empty `env:` block will just do nothing once applied. it's not an issue as far as I know, unless there's a reason ? 
The other way around would be a bunch of `if and or`... I can do the change but it's useless to me...

2023-06-22 18:02 UTC, zanhsieh commented on charts/prometheus-stackdriver-exporter/templates/deployment.yaml
> +          {{- if or .Values.stackdriver.serviceAccountSecret .Values.stackdriver.serviceAccountKey }}
@prune998 
Dunno if this work. You might test it out:

```suggestion
          {{- $extraEnvs := .Values.extraEnvs }}
          {{- if or .Values.stackdriver.serviceAccountSecret .Values.stackdriver.serviceAccountKey }}
          {{- $extraEnvs = append .Values.extraEnvs list dict "name" "GOOGLE_APPLICATION_CREDENTIALS" "value" "/etc/secrets/service-account/credentials.json" }}
          {{- end }}
          {{- with $extraEnvs }}
          env:
          {{- range $key, $value := . }}
            {{- if $value }}
            - name: {{ $key | quote }}
              value: {{ $value |quote }}
            {{- end }}
          {{- end }}
          {{- end}}
```

2023-06-23 06:47 UTC, rpahli commented on charts/prometheus-stackdriver-exporter/templates/deployment.yaml
> +          {{- if or .Values.stackdriver.serviceAccountSecret .Values.stackdriver.serviceAccountKey }}
at least the resulting manifest looks a little bit cleaner if you put it in a `with` block.

2023-09-17 05:42 UTC, closed without merging