[kube-state-metrics] Add endpointslices to ClusterRole/Role
prometheus-community/helm-charts pull request #3514
Opened 2023-06-20 23:15 UTC by nicholascapo

#### What this PR does / why we need it

When `endpointslices` are enabled in collectors (not the default), `kube-state-metrics` logs the following error:
```
2023-06-20T17:51:58.346283983-05:00 E0620 22:51:58.346134       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:monitoring:prometheus-kube-state-metrics" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
```

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-06-21 09:18 UTC, dotdc requested changes
LGTM but I see this as a fix, could you bump the version to 5.8.1 instead?

2023-06-21 16:42 UTC, nicholascapo commented
> LGTM but I see this as a fix, could you bump the version to 5.8.1 instead?

Yeah, I went back and forth, changed to patch now.

2023-06-22 08:48 UTC, dotdc commented
Your second commit is not properly signed (Signed-off-by), and the DCO check is failing.
Can you fix it so we can merge?

2023-06-22 14:44 UTC, mrueg approved these changes

2023-06-22 14:45 UTC, merged