[kube-prometheus-stack] #356 add support for multicluster in grafana dashboards
prometheus-community/helm-charts pull request #357
Opened 2020-11-13 11:19 UTC by batas

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #356

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-13 16:20 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 11.1.2
Wouldn't this be `11.2.0` ?

rest everything looks good to me. but will wait for one more reviewer as well.

2020-12-04 10:09 UTC, mwennrich commented
Would really love to see this merged :pray: :smiley:

2020-12-05 10:35 UTC, monotek requested changes
Please resolve merge conflicts

2020-12-10 12:31 UTC, monotek approved these changes

2020-12-11 08:54 UTC, gkarthiks approved these changes

2020-12-11 08:54 UTC, merged