[Alertmanager ] add enabled property into config block
prometheus-community/helm-charts pull request #3579
Opened 2023-07-10 21:16 UTC by figuerascarlos

#### What this PR does / why we need it
Due to `values.schema.json` validation is not posible to set config block to `false`. I would like to set config to `false` because I  use extraSecretMounts to populate the configuration  due some sensible information.
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-07-19 07:59 UTC, monotek requested changes

2023-07-19 07:59 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 0.33.2
new feature should raise minor version.
```suggestion
version: 0.34.0
```

2023-07-24 12:44 UTC, AnastasiosDados commented
Nice, I was having the same issue as I want to inject my config via extraVolumeMounts and extraVolumes and it is not possible at the moment as it enforces to have config values.

2023-08-07 09:55 UTC, monotek approved these changes

2023-08-07 09:59 UTC, merged