[prometheus-rabbitmq-exporter] allow passing an external ConfigMap to override env vars
prometheus-community/helm-charts pull request #3582
Opened 2023-07-11 15:30 UTC by davido912

#### What this PR does / why we need it
Following https://github.com/prometheus-community/helm-charts/pull/3574, I added a way to template the URL so that parent charts can template the URL into it without having to hardcode it. However, it appears subcharts don't read values from the [parent chart](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/).

Therefore, to allow for customisation of the envs vars, I moved all the env vars to a configmap and added the option to add an externally supplied configmap which will override whatever is in the first one. 

According to the [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/), for envFrom: 

"List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated."

So the last overriding configmap which was added here will override, whereas anything in env will override everything in envFrom. Therefore, when for the password, when a secret is supplied, env takes precedence. 

I hope this was clear and would appreciate feedback. Couldn't think of a better way to give some control back to the user.

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-07-13 08:25 UTC, davido912 commented
@monotek perhaps you can assist in getting this through or checking this out, given you checked the previous PR :)

2023-07-17 13:30 UTC, zanhsieh requested changes

2023-07-17 13:30 UTC, zanhsieh commented on charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
> +        {{- end }}
```suggestion
        {{- with .Values.annotations }}
          {{- toYaml .| nindent 8 }}
        {{- end }}
```

2023-07-17 13:30 UTC, zanhsieh commented on charts/prometheus-rabbitmq-exporter/templates/configmap.yaml
> +  {{- end }}
```suggestion
  {{- with .Values.additionalLabels }}
    {{- toYaml . | indent 4 }}
  {{- end }}
```

2023-07-19 07:56 UTC, davido912 commented
@zanhsieh applied the changes

2023-07-19 15:49 UTC, zanhsieh approved these changes

2023-07-19 15:51 UTC, zanhsieh approved these changes

2023-07-20 06:04 UTC, davido912 commented
Apparently we're missing one more review (@desaintmartin / @Juanchimienti / @monotek ) 🙌

2023-07-20 14:19 UTC, monotek approved these changes

2023-07-20 14:20 UTC, monotek approved these changes

2023-07-20 14:20 UTC, merged