[prometheus-mysql-exporter]: upgrade cloud-sql-proxy v2
prometheus-community/helm-charts pull request #3583
Opened 2023-07-11 20:49 UTC by mclavel

#### What this PR does / why we need it
- upgrade cloud-sql-proxy to v2.4.0 (support v2)
- set `securityContext` config to use minimal permissions
- extend `livenessProbe`, `readinessProbe` & `startupProbe` to use internal healtcheck

#### Which issue this PR fixes

No issue

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-07-13 15:43 UTC, monotek requested changes

2023-07-13 15:43 UTC, monotek commented on charts/prometheus-mysql-exporter/Chart.yaml
>  appVersion: v0.14.0
exporter could be updated too

```suggestion
appVersion: v0.15.0
```

2023-07-13 15:43 UTC, monotek approved these changes

2023-07-13 16:24 UTC, monotek requested changes
please implement breaking changes of: https://github.com/prometheus/mysqld_exporter/releases/tag/v0.15.0

2023-07-14 23:05 UTC, mclavel commented
I pushed some changes to give support to the exporter v0.15.0 🥲

2023-07-14 23:31 UTC, monotek approved these changes

2023-07-14 23:31 UTC, merged