ICMP: Suggest setting `net.ipv4.ping_group_range` in `podSecurityContext`
prometheus-community/helm-charts pull request #3616
Opened 2023-07-19 11:56 UTC by fatz

#### What this PR does / why we need it
To enable ICMP probes `net.ipv4.ping_group_range` must be set in some environments.

This PR adds a hint to the release notes aside of the hint to set `securityContext.capabilities.add: ["NET_RAW"]` for enabling ICMP.

This will IMO make it easier for users to get ICMP probes working

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-09-27 12:45 UTC, monotek requested changes
some text should be added why its needed and maybe in which environments.
also chart version needs to be updated.

2024-01-08 16:58 UTC, monotek requested changes
chart version needs to be updated

2024-06-24 02:28 UTC, nijave commented
This seems possibly related to cri-o. I ran into this issue with k8s 1.29 on cri-o/Ubuntu 22.04

https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md

2025-02-15 06:47 UTC, sebhoss commented
Related to https://github.com/prometheus-community/helm-charts/issues/2360 and https://github.com/prometheus-community/helm-charts/issues/2483

2025-06-26 22:41 UTC, closed without merging