[prometheus-statsd-exporter] - add conditional for hpa apiVersion
prometheus-community/helm-charts pull request #3635
Opened 2023-07-24 23:04 UTC by tylenwells

#### What this PR does / why we need it
autoscaling/v2beta1 api for horizontalPodAutoscalers was [removed in k8s 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125)
This PR adds a conditional to use autoscaling/v2 API version if the k8s version of your cluster is 1.25 or greater.
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer
@scDisorder - @-mentioning you per the instructions above. Please review when you have the time, thank you!
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-07-26 13:05 UTC, zeritti requested changes
Thank you, @tylenwells, for your PR. Please, see my comment below.

2023-08-02 18:43 UTC, oshaughnessy commented
i'm running into issues with autoscaling/v2beta1 -- i see warnings in my K8S 1.25 clusters and failures in 1.26. i'd love to see a solution merged in, whether or not the code is optimal. not ideal, perhaps, but how about approving & merging as-is and updating with better code as a separate PR? :-)

2023-08-04 02:17 UTC, zanhsieh approved these changes

2023-08-04 02:29 UTC, zanhsieh approved these changes

2023-08-04 07:21 UTC, zeritti approved these changes

2023-08-04 07:23 UTC, merged

2023-08-07 20:01 UTC, tylenwells commented
Leaving a note here for anyone who comes across this: 

This change allows for the updated apiVersion to be used, but doesn't account for the change in spec formatting for the new apiVersion. #3681 takes care of that. 

old ver:
```yaml
metrics:
   - type: Resource
      resource:
        name: cpu
        targetAverageUtilization:  {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
```

new ver: 
```yaml
metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
```