[prometheus-statsd-exporter] fix hpaspec for autoscaling/v2
prometheus-community/helm-charts pull request #3681
Opened 2023-08-07 19:51 UTC by tylenwells

#### What this PR does / why we need it
Changes introduced in #3635 allowed for the new apiVersion but didn't update the spec changes. This fixes that by adding conditionals for spec formatting.
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer
@scDisorder - Apologies for missing this the first time around, caught it when working around the original issue locally but didn't make it into the PR before getting merged. 

If you would like to use a template here, we could do that. I just did it using semVerCompare for now but would be willing to template it if you prefer.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-08-07 20:04 UTC, tylenwells commented
Example of the part of the spec that changed:

old ver:
```yaml
metrics:
   - type: Resource
      resource:
        name: cpu
        targetAverageUtilization:  {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
```

new ver: 
```yaml
metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
```

2023-09-09 10:05 UTC, zeritti requested changes

2023-09-22 23:01 UTC, zanhsieh approved these changes

2023-09-23 07:37 UTC, zeritti approved these changes

2023-09-23 07:38 UTC, merged