[alertmanager] Updates Alertmanager image to v0.26.0
prometheus-community/helm-charts pull request #3720
Opened 2023-08-24 14:33 UTC by arukiidou

#### What this PR does / why we need it

- Updates Alertmanager image to [v0.26.0](https://quay.io/repository/prometheus/alertmanager?tab=tags&tag=v0.26.0) 
  - maintenance.

#### Which issue this PR fixes

- none.

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-08-25 02:23 UTC, monotek requested changes

2023-08-25 02:23 UTC, monotek commented on charts/alertmanager/Chart.yaml
> +version: 1.5.1
```suggestion
version: 1.6.0
```

2023-08-25 03:12 UTC, arukiidou commented on charts/alertmanager/Chart.yaml
> +version: 1.5.1
fixed.

2023-08-26 11:09 UTC, monotek approved these changes

2023-08-26 11:09 UTC, merged

2023-08-26 12:06 UTC, arukiidou commented
thankyou!