[prometheus-adapter] Add sidecar container support
prometheus-community/helm-charts pull request #3737
Opened 2023-08-29 14:52 UTC by rpriyanshu9

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-08-29 15:09 UTC, rpriyanshu9 commented
👋🏼 @MattiasGees @hectorj2f @steven-sheehy Could you please take a look?

2023-08-31 17:03 UTC, rpriyanshu9 commented
PTAL @hectorj2f @MattiasGees @steven-sheehy

2023-09-12 15:49 UTC, steven-sheehy requested changes

2023-09-12 15:49 UTC, steven-sheehy commented on charts/prometheus-adapter/Chart.yaml
> +version: 4.4.2
```suggestion
version: 4.6.0
```

2023-09-12 15:49 UTC, steven-sheehy commented on charts/prometheus-adapter/values.yaml
> +sideCarContainers: []
`extraContainers` is more widely used in this repository. Also, move it above `extraVolumes` so it's more sorted.

```suggestion
# Additional containers to add to the pod
extraContainers: []
```

2023-09-27 12:28 UTC, rpriyanshu9 commented
@steven-sheehy I've implemented the requested changes. Could you please take a look?

2023-09-29 14:32 UTC, steven-sheehy approved these changes
LGTM. Thanks for your contribution

2023-09-29 14:36 UTC, merged