[prometheus-adapter] Add missing dnsPolicy for hostNetwork
prometheus-community/helm-charts pull request #375
Opened 2020-11-18 07:22 UTC by TamasSzigeti

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-21 18:33 UTC, monotek requested changes
I would prefer to have the dns policy outside of the "{{- if .Values.hostNetwork.enabled }}" and make it configurable.
Default value for dnsPolicy should be "Default".

2020-11-22 07:43 UTC, TamasSzigeti commented
> I would prefer to have the dns policy outside of the "{{- if .Values.hostNetwork.enabled }}" and make it configurable.
> Default value for dnsPolicy should be "Default".

Thank you, done.

2020-11-22 16:26 UTC, monotek approved these changes

2020-12-02 16:17 UTC, steven-sheehy commented
LGTM, can you fix the conflicts?

2020-12-02 16:37 UTC, TamasSzigeti commented
@steven-sheehy Done

2020-12-02 16:41 UTC, steven-sheehy approved these changes
Thanks

2020-12-02 16:41 UTC, merged

2020-12-03 09:43 UTC, msvticket commented
The default dnsPolicy in EKS is not Default, it is ClusterFirst. This change makes the DNS lookup fail for DNS-lookup of in-cluster service: lookup prometheus on XX.XX.XX.XX:53: no such host. To correctly. I just created a PR with a fix for this.