[prometheus] Adding additionalPorts and servicePort
prometheus-community/helm-charts pull request #3779
Opened 2023-09-11 18:56 UTC by mortenbirkelund

#### What this PR does / why we need it

Similar to #2163 for the kube-prometheus-stack, this PR will make it possible to add an oauth proxy as a sidecar container, and change the ingress to point to an additional port in your service, that then goes to your oauth proxy. Nice and simple way of adding oauth to Prometheus. 
#### Which issue this PR fixes
No issues opened for this chart, but this have been solved for the kube-prometheus-stack chart, so why not also make it possible in the prometheus chart. 

#### Special notes for your reviewer
I have checked the helm chart with my changed, and it seems to work fine, but let me know if any changes is required. 

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-09-12 15:02 UTC, zanhsieh approved these changes

2023-09-12 19:49 UTC, zeritti requested changes

2023-09-12 19:49 UTC, zeritti commented on charts/prometheus/Chart.yaml
> +version: 24.4.1
This change should be considered minor:

```suggestion
version: 24.5.0
```

2023-09-13 09:42 UTC, mortenbirkelund commented on charts/prometheus/Chart.yaml
> +version: 24.4.1
Agree, it should be a minor version.

2023-09-13 10:03 UTC, zeritti approved these changes

2023-09-13 10:35 UTC, merged