[prometheus-kafka-exporter]: Add LoadBalancerIp
prometheus-community/helm-charts pull request #3830
Opened 2023-09-27 13:38 UTC by KimJoonSeo

#### What this PR does / why we need it
I added an loadBalancerIP configuration to specify a static IP when using NodePort service type.
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- This PR has a similar context with PR #3828 .

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-09-27 17:10 UTC, zeritti commented
> I added an loadBalancerIP configuration to specify a static IP when using NodePort service type.

You probably meant _when using LoadBalancer service type_. Using `spec.type=NodePort` with `spec.loadbalancerIP` won't work as the current code does not allow it. Furthemore, the latter applies only to the LoadBalancer type.

2023-09-27 17:38 UTC, zeritti requested changes

2023-09-27 17:38 UTC, zeritti commented on charts/prometheus-kafka-exporter/values.yaml
> +  # Specifies a reserved static IP. It must be used with service.type=LoadBalancer.
```suggestion
  # Specifies a reserved static IP. Used with service.type=LoadBalancer.
  # The field is deprecated, implementation-specific annotations should be set instead.
```

2023-09-27 17:38 UTC, zeritti commented on charts/prometheus-kafka-exporter/values.yaml
> +  # Specifies a custom nodePort for external use. It must be used with service.type=NodePort.
The field need not be used as it is optional.

```suggestion
  # Specifies a custom nodePort for external use. Used with service.type=NodePort.
```

2023-09-28 04:46 UTC, KimJoonSeo commented
> > I added an loadBalancerIP configuration to specify a static IP when using NodePort service type.
> 
> You probably meant _when using LoadBalancer service type_. Using `spec.type=NodePort` with `spec.loadbalancerIP` won't work as the current code does not allow it. Furthermore, the latter applies only to the LoadBalancer type.

That's correct. I meant to do it when using LoadBalancer service type.

2023-09-28 13:32 UTC, merged