[prometheus-stackdriver-exporter] bump stackdriver exporter to 0.14.1
prometheus-community/helm-charts pull request #3847
Opened 2023-09-30 15:56 UTC by DrFaust92

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-10-16 09:08 UTC, rpahli requested changes

2023-10-16 09:08 UTC, rpahli commented on charts/prometheus-stackdriver-exporter/Chart.yaml
> +appVersion: "v0.14.1"
the double quotes are not necessary

2023-10-27 08:47 UTC, DrFaust92 commented on charts/prometheus-stackdriver-exporter/Chart.yaml
> +appVersion: "v0.14.1"
removed

2023-11-06 08:44 UTC, rpahli approved these changes

2023-11-06 08:44 UTC, merged