[prometheus] Migrate to chart v2
prometheus-community/helm-charts pull request #387
Opened 2020-11-18 13:03 UTC by zanhsieh

Signed-off-by: zanhsieh <zanhsieh@gmail.com>

#### What this PR does / why we need it:
Initial attempt to move to chart v2, since helm v2 has been out of support since Nov. 15th, 2020.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus]`)

2020-11-18 23:44 UTC, monotek requested changes

2020-11-18 23:44 UTC, monotek commented on charts/prometheus/Chart.yaml
> +type: application
dependencies should go to chart.yaml too.

2020-11-18 23:46 UTC, monotek commented on charts/prometheus/README.md
> +- Kubernetes 1.16+
If we go for kubernetes 1.16 all extension beta apis should be removed.

For example: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/ingress.yaml#L10

2020-11-18 23:47 UTC, monotek requested changes
container images could be updated to.

2020-11-19 02:15 UTC, zanhsieh commented
> container images could be updated to.

This one I will need to separate PR since too many moving parts.

2020-11-19 09:43 UTC, monotek requested changes
Imho it's perfect to do that if we introduce a new major version.

2020-11-21 18:57 UTC, monotek commented on charts/prometheus/Chart.yaml
> +
please remove empty line

2020-11-21 18:58 UTC, monotek requested changes
please remove empty line in chart.yaml

2020-11-22 13:40 UTC, zanhsieh commented
> please remove empty line in chart.yaml

@monotek 
The lint will complain about this. It needs an empty line on the end.

2020-11-22 15:44 UTC, monotek approved these changes

2020-11-22 15:44 UTC, merged