[prometheus-redis-exporter] Migrate to chart v2
prometheus-community/helm-charts pull request #389
Opened 2020-11-18 14:08 UTC by zanhsieh

Signed-off-by: zanhsieh <zanhsieh@gmail.com>

#### What this PR does / why we need it:
Initial attempt to move to chart v2, since helm v2 has been out of support from Nov. 15th, 2020.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-redis-exporter]`)

2020-11-21 18:42 UTC, monotek requested changes
maybe we should add the chart type too?

see: https://helm.sh/docs/topics/charts/#chart-types

2020-11-22 16:26 UTC, monotek approved these changes

2020-11-23 07:25 UTC, acondrat approved these changes
lgtm

2020-11-23 07:25 UTC, acondrat commented
Is everyone happy merging this?

2020-11-23 10:15 UTC, merged