[prometheus-postgres-exporter] Migrate to chart v2
prometheus-community/helm-charts pull request #390
Opened 2020-11-18 14:21 UTC by zanhsieh

Signed-off-by: zanhsieh <zanhsieh@gmail.com>

#### What this PR does / why we need it:
Initial attempt to move to chart v2, since helm v2 has been out of support from Nov. 15th, 2020.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-postgres-exporter]`)

2020-11-21 18:43 UTC, monotek requested changes
maybe we should add the chart type too?

see: https://helm.sh/docs/topics/charts/#chart-types

2020-11-22 16:27 UTC, monotek approved these changes

2020-11-23 17:04 UTC, zanhsieh commented
@scottrigby 
Could you help me to review this PR please?

2020-11-28 16:06 UTC, scottrigby requested changes
Would you please add an "Upgrading" section, with a subheader for "2.0.0", and make crystal clear that this version requires Helm 3? I see you added to prerequisites but this would also help make clear when the change happened for users who may need to take longer upgrading from Helm 2 to 3. Thanks!

2020-11-30 14:54 UTC, closed without merging