[prometheus-json-exporter] fix: configmap name standard
prometheus-community/helm-charts pull request #3926
Opened 2023-10-20 19:31 UTC by t3mi

#### What this PR does / why we need it
Corrects ConfigMap name formula to be dependent on the configurable `prometheus-json-exporter.fullname` template like other resources in the chart. Without this, its not possible correctly maintain multiple instances of the exporter as part of single release.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-10-21 06:52 UTC, zanhsieh requested changes
@t3mi 
Thanks for the contribution. Since this is a minor version bump, can you write up some reminder in README.md that the user has to know for upgrading?

2023-10-21 11:31 UTC, t3mi commented
@zanhsieh added.

2023-10-22 11:21 UTC, zanhsieh approved these changes

2023-10-22 12:26 UTC, xiu approved these changes

2023-10-22 12:27 UTC, merged