Add support for enebaling disabling http2 on servicemonitor for kube …
prometheus-community/helm-charts pull request #3955
Opened 2023-11-02 12:55 UTC by nikhil-bhat

…state metrics

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-11-02 19:32 UTC, dotdc requested changes
Hi @nikhil-bhat,
LGTM, could you bump the chart's version to `5.15.0`?

2023-11-03 12:59 UTC, dotdc commented
@nikhil-bhat your last commit is not signed, that's why the DCO is failing.
Could you fix that so we can merge?

2023-11-03 13:09 UTC, nikhil-bhat commented
@dotdc thanks a lot , I have addressed all the comments

2023-11-03 13:19 UTC, nikhil-bhat commented
noticed that https://github.com/prometheus-community/helm-charts/pull/3954/files needs to be merged to fix the lint test

2023-11-08 20:31 UTC, dotdc approved these changes

2023-11-08 20:32 UTC, merged

2023-11-08 20:32 UTC, dotdc commented
Thank you for your contribution @nikhil-bhat !