[prometheus-snmp-exporter] Add optional auth section
prometheus-community/helm-charts pull request #4020
Opened 2023-11-17 21:22 UTC by iPenguin

#### What this PR does / why we need it

This PR passes the auth parameters available in newer versions of snmp-exporter from the chart to the application configuration.

#### Which issue this PR fixes

- fixes #3940

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-12-18 15:59 UTC, iPenguin commented
Hi @xiu, just checking to see if you have any feedback for this PR?

Thanks,
Brian

2024-02-27 05:47 UTC, walker-tom commented
Thank you for your PR, similar changes have been implemented in #4086 but they didn't include a default value for the `ServiceMonitor` `auth`. If you'd like to update your PR to include this default value then I'll give it a review, thanks!

2024-02-27 05:48 UTC, walker-tom requested changes
Thank you for your PR, similar changes have been implemented in https://github.com/prometheus-community/helm-charts/pull/4086 but they didn't include a default value for the `ServiceMonitor` `auth`. If you'd like to update your PR to include this default value then I'll give it a review, thanks!

2024-02-27 18:19 UTC, iPenguin commented
Hi @walker-tom I've fixed the merge conflict. Do you need me to do anything else?

Thanks,
Brian

2024-02-27 18:26 UTC, walker-tom commented
> Hi @walker-tom I've fixed the merge conflict. Do you need me to do anything else?
> 
> Thanks, Brian

Hi Brian, thanks for updating your PR, could you update the Chart version in `Chart.yaml`, I think it got lost during the merge conflict. Thanks!

2024-02-27 21:43 UTC, iPenguin commented
:facepalm: Thanks. I think that should fix it.

2024-02-28 05:06 UTC, walker-tom requested changes

2024-02-28 05:06 UTC, walker-tom commented on charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
> +      - {{ .auth | default $.Values.serviceMonitor.auth }}
Sorry only just noticed, there is already an `auth` field referenced on lines 29-31, could you remove those in favour of this please.

2024-02-28 18:14 UTC, walker-tom approved these changes

2024-02-28 18:14 UTC, merged

2024-02-29 03:16 UTC, kevinastone commented
This change seems to be broken in the default case where you don't specify an auth in the `params[*]`.  It's attempting to apply the default `$.Values.serviceMonitor.auth` (which is an array, defaulting to `[public_v2]`) to a single item in the array:

```
      auth:
      - {{ .auth | default $.Values.serviceMonitor.auth }}
```

 So it's ending up being:
 ```
    auth:
    - [public_v2]
```


Here's the error from my HelmRelease install:

```
ServiceMonitor.monitoring.coreos.com "snmp-exporter-prometheus-snmp-exporter-<target1>" is invalid: spec.endpoints[0].params.auth[0]: Invalid value: "array": spec.endpoints[0].params.auth[0] in body must be of type string: "array" && cannot patch "snmp-exporter-prometheus-snmp-exporter-<target2>" with kind ServiceMonitor: ServiceMonitor.monitoring.coreos.com "snmp-exporter-prometheus-snmp-exporter-<target2>" is invalid: spec.endpoints[0].params.auth[0]: Invalid value: "array": spec.endpoints[0].params.auth[0] in body must be of type string: "array"
````

2024-02-29 14:07 UTC, iPenguin commented
> This change seems to be broken in the default case where you don't specify an auth in the `params[*]`. It's attempting to apply the default `$.Values.serviceMonitor.auth` (which is an array, defaulting to `[public_v2]`) to a single item in the array:

I apologize for the mistake. Thanks for fixing it.

2024-05-18 13:03 UTC, walker-tom commented
@abctaylor You will need to create an `auths` configuration for your targets in your SNMP Exporter. As documented in [auth-split-migration.md](https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md) this is now separate to the `modules` configuration. You can see examples in [the generator file format](https://github.com/prometheus/snmp_exporter/tree/main/generator#file-format) for the settings available for SNMPv3. You then have at least two options for getting this configuration into your Container:

1. Create an `auths` configuration YAML file for the exporter in a `Secret` and mount that into your Container using `extraVolumes` and `extraVolumeMounts`, then pass in an argument `--config.file=/path/to/extra/auths/file` via the extra `extraArgs`. SNMP Exporter will then load up a this additional configuration
2. Add the `auths` configuration to your existing SNMP Exporter configuration file, set the relevant sensitive data as environment variables using `envFrom` and then reference those env vars in your `auths` section using `--config.expand-environment-variables` as mentioned [here](https://github.com/prometheus/snmp_exporter/blob/main/README.md#configuration)

Hope this helps.