[prometheus-adapter] Only set priorityClassName if non-empty
prometheus-community/helm-charts pull request #4026
Opened 2023-11-20 22:56 UTC by iangudger

Argo CD rejects the deployment when the priorityClassName key is present without a value.

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-11-20 23:17 UTC, steven-sheehy requested changes

2023-11-20 23:17 UTC, steven-sheehy commented on charts/prometheus-adapter/templates/deployment.yaml
>        priorityClassName: {{ .Values.priorityClassName }}
Don't repeat yourself
```suggestion
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
```

2023-11-21 03:53 UTC, iangudger commented on charts/prometheus-adapter/templates/deployment.yaml
>        priorityClassName: {{ .Values.priorityClassName }}
Done.

2023-11-21 04:47 UTC, steven-sheehy approved these changes

2023-11-21 04:47 UTC, merged