Allow user-defined matchLabels for deployment and servicemonitor in prometheus-cloudwatch-exporter
prometheus-community/helm-charts pull request #406
Opened 2020-11-23 11:03 UTC by paweldudzinski

#### What this PR does / why we need it:

The changes will allow the end user to define custom matchLabels for deployment and serviceMonitor. This is crucial for having metrics in Prometheus Operator.

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-11-23 11:58 UTC, adambabik commented on charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
> +{{ toYaml .Values.deployment.matchLabels | indent 6 }}
You can align indentation of `if` and `toYaml` where it belongs if you use `nindent`.

```suggestion
      {{ toYaml .Values.deployment.matchLabels | nindent 6 }}
```

The same comment about indentation applies to other changes in this PR.

2020-11-23 12:49 UTC, torstenwalter commented
@paweldudzinski Can you elaborate why you need to specify these. I don't understand the need for it.

2020-11-23 12:51 UTC, torstenwalter commented
Isn't a `ServiceMonitor` used to tell prometheus operator which metric to scrape?
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources

2020-11-23 13:07 UTC, paweldudzinski commented
> Isn't a `ServiceMonitor` used to tell prometheus operator which metric to scrape?
> https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources

@torstenwalter The ServiceMonitor has a label selector to select Services and their underlying Endpoint objects. The labels have to match. Some setups might have special labels that are required. For example, in my specific case the existing setup of predefined labels is not enough to fully match the resources.

2020-11-23 14:03 UTC, torstenwalter commented
I don;t see why you need to adjust selectors for the deployent and the service objects. It's an immutable fiels in Kubernetes. Having it configurable via values.yaml might lead to the impression that people can change it at any point in time. That's not the case!

2020-11-23 14:35 UTC, paweldudzinski commented
Let me describe our case. There are several way to configure Prometheus Operator so it scrapes metrics. Our PO bases on label called `owner`, other configuration may base on different labels. In order for it to work we need to setup such label in deployment and then match those labels. Therefore the need of extra labels. Just like in a service: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/templates/service.yaml#L12 it can be applied to any other resource.

2020-11-23 15:15 UTC, torstenwalter commented
For that it should be sufficient to introduce additional labels for the pod like:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/deployment.yaml#L26-L28

There is no need to use them as `matchLabels` in deployment or `selector` in service.

2020-11-23 15:42 UTC, paweldudzinski commented
ok, I missed that possibility to customize the pod labels - thanks for that. That changes a lot. 
Yet, for my case I'd still need to do the same thing (add labels) for deployment.
PR is updated just to this use case. @torstenwalter do you think I'd be possible?

2020-11-23 16:55 UTC, torstenwalter requested changes

2020-11-23 16:55 UTC, torstenwalter commented on charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
> +{{- end }}
I you move these down to `template.metadata.labels` and name them `pod.labels` then it's fine for me.

2020-11-23 16:55 UTC, torstenwalter commented on charts/prometheus-cloudwatch-exporter/values.yaml
> +  labels: {}
I suggest to either use:
```suggestion
deployment:
  podLabels: {}
```
or
```suggestion
pod:
  labels: {}
```

2020-11-23 17:18 UTC, paweldudzinski commented
@torstenwalter all done (same style as prometheus-blackbox). thanks for guidance.

2020-11-24 07:08 UTC, torstenwalter approved these changes
LGTM

2020-11-24 07:09 UTC, merged

2020-11-24 07:10 UTC, torstenwalter commented
@paweldudzinski Thank you for the contribution and the discussion about it.