[kube-state-metrics] Default to Recreate
prometheus-community/helm-charts pull request #4096
Opened 2023-12-18 17:23 UTC by wiardvanrij

#### What this PR does / why we need it

See issue/ticket.

#### Which issue this PR fixes

- fixes #4095

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2023-12-18 20:20 UTC, dotdc requested changes
Like explained in https://github.com/prometheus-community/helm-charts/issues/4095, I would keep `RollingUpdate` as the default strategy.

2023-12-18 20:20 UTC, dotdc commented on charts/kube-state-metrics/templates/deployment.yaml
> +    type: {{ .Values.updateStrategy | default "Recreate" }}
Please revert to `RollingUpdate`

2023-12-18 20:20 UTC, dotdc commented on charts/kube-state-metrics/values.yaml
> +# updateStrategy: RollingUpdate
I would rework this paragraph taking into account that `RollingUpdate` is the default.
You can also add : 
```yaml
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
```

2024-01-09 13:37 UTC, mrueg commented
I would suggest to keep RollingUpdate as the default as well, rather than Recreating. 
If you run ksm with more than 1 replica, you have to deal with the instance in your query as well.
If recreate fails for some reason and a rollback is needed, you will observe larger gaps in your metrics.

2024-01-10 09:31 UTC, dotdc requested changes
@wiardvanrij Could you bump the chart to 5.15.4 so we can merge?

2024-02-29 09:22 UTC, dotdc commented
Done in #4318

2024-02-29 09:22 UTC, closed without merging