[prometheus-node-exporter] Add variable to change port for node-exporter daemonset
prometheus-community/helm-charts pull request #4167
Opened 2024-01-22 15:29 UTC by nfrazier08

#### What this PR does / why we need it

This PR:
- Adds a variable in the daemonset to be able to change the port used rather than hard-coded in the ternary operator
- It also adds the option to change the name for the kubeRBACProxy container port, with the default still being 'http'
- Adds the option for a hostPort for kubeRBACProxy 

#### Special notes for your reviewer

My team found that the hard-coded port for the daemonset was not compatible with what is needed for our clusters. Adding a variable allows for backwards compatibility while making it more flexible. We also wanted to be able to add an option for a hostPort and change the name of the containerPort as well. 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

@gianrubio @zanhsieh @zeritti

2024-01-22 20:31 UTC, zeritti requested changes
Thank you, @nfrazier08, for your PR. Please, see my comments below.

2024-01-22 21:09 UTC, nfrazier08 commented on charts/prometheus-node-exporter/values.yaml
> +  # Specify the port used for the daemonset
Thank you @zeritti, I have made these suggested changes.

2024-01-22 21:10 UTC, nfrazier08 commented on charts/prometheus-node-exporter/values.yaml
> +  hostPort: false
Your point here makes sense - thanks. I changed the name to enableHostPort to reduce confusion.

2024-01-23 11:31 UTC, zeritti approved these changes

2024-01-24 14:19 UTC, zanhsieh approved these changes

2024-01-24 14:19 UTC, merged