[node-exporter] Fix sidecars containers volumeMounts merge
prometheus-community/helm-charts pull request #4177
Opened 2024-01-24 15:05 UTC by ebuildy

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-01-26 01:41 UTC, zanhsieh requested changes

2024-01-26 01:41 UTC, zanhsieh commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 4.27.0
A fix should bump to patch version.

```suggestion
version: 4.26.1
```

2024-01-28 22:58 UTC, zeritti requested changes
Thank you, @ebuildy, for your PR. Please, see my comments below.

2024-01-28 22:58 UTC, zeritti commented on charts/prometheus-node-exporter/templates/_helpers.tpl
> +{{- end }}
Please, keep a new line character previously present at the end of the file.

2024-01-29 11:58 UTC, zanhsieh approved these changes

2024-01-29 16:04 UTC, zeritti approved these changes

2024-01-29 16:06 UTC, merged