[prometheus-node-exporter]
prometheus-community/helm-charts pull request #4191
Opened 2024-01-26 20:13 UTC by nfrazier08

#### What this PR does / why we need it

For our purposes of this chart, we would like to be able to customize the node-exporter daemonset with the following variables:

- For both the Node Exporter and KubeRBACProxy containers, variables have been added to configure `terminationMessagePath` and `terminationMessagePolicy`
- For the KubeRBACProxy container port, a variable has been added to configure the port protocol
- Specify container `restartPolicy` for Node Exporter container
- A variable was added to configure the `terminationGracePeriodSeconds`
- For both the `/proc` and `/sys` filesystems, a variable has been added to configure the `mountPropagation`
- A variable was also added to configure env variable for the KubeRBACProxy container
- Bug Fix: There was a missing trim dash for the KubeRBACProxy container resources that created an extra space and so it was added to remove the unneeded space

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

@zeritti @gianrubio @zanhsieh

2024-01-29 00:25 UTC, zanhsieh requested changes
@nfrazier08 
Can you separate feature branch and bug fix? You can choose patching the bug go first or the feature go first, but not both.

2024-01-29 14:57 UTC, nfrazier08 commented
@zanhsieh Thanks for taking a look at this PR. I will do the bug fix in a following PR and have removed it from this PR.

2024-01-30 06:21 UTC, zanhsieh requested changes

2024-01-30 06:21 UTC, zanhsieh commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 4.27.1
```suggestion
version: 4.27.0
```

2024-01-30 13:05 UTC, zeritti requested changes
@nfrazier08 Thank you for your PR. This PR, though, covers too many different and unrelated changes on:
- termination params
- volume mounts
- restart policy
- support for environment variables
- container ports

Please, prefer related changes in a PR, ideally on a single topic/area. It is reasonable, indeed, to raise more than one PR on these changes.

2024-01-30 15:24 UTC, nfrazier08 commented
@zeritti - Thank you, I will go ahead and split these changes up into separate PRs - starting with this one for adding termination params.

2024-01-30 18:47 UTC, zeritti requested changes
When seeing a set of related parameters with a toggle, the first thing to occur to me is a map: the toggle if set enables all the fields in the map. An example of a map that one might name, say, `terminationMessageParams` in the values file:

```yaml
## values.yaml
# Enable or disable container termination message settings
# https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/
terminationMessageParams:
  enabled: false
  # If enabled, specify the path for termination messages
  terminationMessagePath: /dev/termination-log
  # If enabled, specify the Policy for termination messages
  terminationMessagePolicy: File
```

and in the template (example for the main container):

```yaml
## template
{{- if .Values.terminationMessageParams.enabled }}
{{- with .Values.terminationMessageParams }}
terminationMessagePath: {{ .terminationMessagePath }}
terminationMessagePolicy: {{ .terminationMessagePolicy }}
{{- end }}
{{- end }}
```

I have not yet seen a case where containers in the same pod are using different termination message parameters. If this indeed occurs as you foresee, the code has to be applied per container in both the values and the template like you show. Otherwise, it can be set in the values just once and shared across the two containers. 

Using `configureTerminationMessagePath` as a toggle may mislead as it does not configure just `terminationMessagePath`.

Alternatively, without a toggle:

```yaml
# Specify the path for termination messages
terminationMessagePath: ""
# Specify the Policy for termination messages
terminationMessagePolicy: ""
```

```yaml
{{- if .Values.terminationMessagePath }}
terminationMessagePath: {{ .Values.terminationMessagePath }}
{{- end }}
{{- if .Values.terminationMessagePolicy }}
terminationMessagePolicy: {{ .Values.terminationMessagePolicy }}
{{- end }}
```

2024-01-30 20:26 UTC, nfrazier08 commented
@zeritti You are right, I like the idea of a toggle better and I don't think the terminationMessagePath or terminationMessagePolicy are going to be different for each container.

2024-01-31 08:16 UTC, zeritti requested changes

2024-01-31 19:42 UTC, zanhsieh requested changes

2024-01-31 19:42 UTC, zanhsieh commented on charts/prometheus-node-exporter/values.yaml
> +# Specify grace period for graceful termination of pods. Defaults to 30
```suggestion
# Specify grace period for graceful termination of pods. Defaults to 30 if null or not specified
```

2024-01-31 20:20 UTC, nfrazier08 commented on charts/prometheus-node-exporter/values.yaml
> +# Specify grace period for graceful termination of pods. Defaults to 30
Changed.

2024-02-01 07:05 UTC, zanhsieh approved these changes

2024-02-01 07:05 UTC, merged