[prometheus-snmp-exporter] Add Tom as maintainer
prometheus-community/helm-charts pull request #4224
Opened 2024-02-04 19:05 UTC by walker-tom

#### What this PR does / why we need it

Adds myself as a maintainer of the promtheus-snmp-exporter Chart as agreed in #4158.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4158 

#### Special notes for your reviewer

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-02-05 07:26 UTC, xiu approved these changes
LGTM @prometheus-community/helm-charts-admins, can you review and merge? Thanks!

2024-02-06 09:57 UTC, monotek commented
@SuperQ or @brancz

can you please add @walker-tom to the https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers group?

2024-02-07 12:03 UTC, SuperQ requested changes

2024-02-07 12:03 UTC, SuperQ commented on .github/CODEOWNERS
> +/charts/prometheus-snmp-exporter/ @miouge1 @xiu @walker-tom
This needs to be sorted.

```suggestion
/charts/prometheus-snmp-exporter/ @miouge1 @walker-tom @Nexucis 
```

2024-02-13 07:07 UTC, SuperQ commented
CC @miouge1

2024-02-13 09:05 UTC, monotek approved these changes

2024-02-14 21:07 UTC, SuperQ approved these changes

2024-02-14 21:08 UTC, SuperQ commented
@xiu, can you re-approve as codeowner?

2024-02-14 21:28 UTC, xiu approved these changes

2024-02-14 21:59 UTC, merged