[prometheus-nginx-exporter] Fix Annotation Use in Chart
prometheus-community/helm-charts pull request #4239
Opened 2024-02-09 15:23 UTC by lukasklinger

#### What this PR does / why we need it
The prometheus-nginx-exporter has two ways to add additional annotations to the resources created by it, the `additionalAnnotations` field and the `podAnnotations` field. Using them in the current version of the chart either breaks the templating or - in the case of the `podAnnotations` field - has no effect.

This PR unifies the use of the `additionalAnnotations` field across the different resources and integrates the `podAnnotations` field into a new helper so that annotations added in this field have an effect.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-02-11 12:47 UTC, zeritti requested changes
Thank you, @lukasklinger, for your PR. Please, see my comments below.

2024-02-11 12:47 UTC, zeritti commented on charts/prometheus-nginx-exporter/templates/deployment.yaml
> +  annotations: {{ toYaml .Values.additionalAnnotations | nindent 4 }}
There is nothing wrong with the previous code. In fact, we should prefer not to render an empty field. Applies to all the changes.

```yaml
{{- with .Values.additionalAnnotations }}
annotations: {{ toYaml . | nindent 4 }}
{{- end }}
```

2024-02-11 12:47 UTC, zeritti commented on charts/prometheus-nginx-exporter/templates/role.yaml
> +  annotations: {{ toYaml .Values.additionalAnnotations | nindent 4 }}
```yaml
{{- with .Values.additionalAnnotations }}
annotations: {{ toYaml . | nindent 4 }}
{{- end }}
```

2024-02-11 12:47 UTC, zeritti commented on charts/prometheus-nginx-exporter/templates/serviceaccount.yaml
> +  annotations: {{ toYaml .Values.additionalAnnotations | nindent 4 }}
```yaml
{{- with .Values.additionalAnnotations }}
annotations: {{ toYaml . | nindent 4 }}
{{- end }}
```

2024-02-11 12:47 UTC, zeritti commented on charts/prometheus-nginx-exporter/templates/servicemonitor.yaml
> +  annotations: {{ toYaml .Values.additionalAnnotations | nindent 4 }}
```yaml
{{- with .Values.additionalAnnotations }}
annotations: {{ toYaml . | nindent 4 }}
{{- end }}
```

2024-02-12 10:16 UTC, lukasklinger commented
Thanks for the review! I've integrated the feedback 🙂

2024-02-12 10:40 UTC, zeritti approved these changes

2024-02-12 10:44 UTC, merged