[prometheus-postgres-exporter] allow overriding image registry
prometheus-community/helm-charts pull request #4345
Opened 2024-03-07 14:37 UTC by yann-soubeyrand

#### What this PR does / why we need it

This PR allows overriding the registry from which to fetch the Prometheus Postgres exporter, independently from the repository. This is useful in cases such as when using AWS ECR pull through cache where the registry must be changed but not the repository.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-03-07 17:08 UTC, zeritti requested changes
Thank you, @yann-soubeyrand, for your PR. For a major change which this indeed is, please, add a short upgrade note in README to advise users on how to adjust custom values before upgrading (applicable to users who modified the repository field).

2024-03-08 09:47 UTC, yann-soubeyrand commented
@zeritti you’re right, I should have done this in the first place :wink:

2024-03-08 16:16 UTC, zeritti requested changes
Thank you, @yann-soubeyrand, for the changes. I am further suggesting a small addition.

2024-03-08 16:16 UTC, zeritti commented on charts/prometheus-postgres-exporter/README.md
> +Image repository has been split into two values: the new `image.registry` value and the already existing `image.repository` value. No change is required when using the default for `image.repository`.
```suggestion
Image repository has been split into two values: the new `image.registry` value and the already existing `image.repository` value. No change is required when using the default for `image.repository`. If you have previously modified field `image.repository`, please, set the two fields accordingly. 
```

2024-03-09 11:01 UTC, zeritti approved these changes

2024-03-10 03:26 UTC, merged