[kube-prometheus-stack] Add labels to template for prometheus
prometheus-community/helm-charts pull request #442
Opened 2020-12-02 17:04 UTC by Leweyy

Signed-off-by: Lewis Brimfield <lewis.brimfield@wejo.com>

#### What this PR does / why we need it:
Adds option to add labels to prometheus

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-03 18:20 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> +appVersion: 0.44.0
Please do not change the appVersion. This corresponds to the mage version [here](https://github.com/prometheus-community/helm-charts/blob/64e66a78a379eed1b80fb1e8633838de6647d53f/charts/kube-prometheus-stack/values.yaml#L1416)

2020-12-05 10:36 UTC, monotek requested changes
Please  update version to 12.5.0

2021-01-09 18:46 UTC, monotek approved these changes

2021-01-29 10:18 UTC, vsliouniaev approved these changes

2021-01-29 13:27 UTC, gkarthiks commented
@Leweyy Can you please rebase to resolve the conflicts?

2021-01-29 13:28 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> -version: 12.10.6
@Leweyy Can you please rebase to resolve the conflicts?

2021-03-14 14:17 UTC, closed without merging