No value extra args
prometheus-community/helm-charts pull request #4508
Opened 2024-05-02 13:24 UTC by h0tbird

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

This enables the inclusion of additional arguments like `--web.enable-remote-write-receiver`, which do not support a value.

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-05-04 21:20 UTC, zeritti requested changes
Thank you, @h0tbird, for your PR. Please, see my comments below.

2024-05-09 16:36 UTC, h0tbird commented on charts/prometheus/templates/deploy.yaml
> +            {{- end }}
Thank you! This approach is more elegant 👍🏼
With `helm template --set`, I still have to run it with a trailing `=`:
```console
$ helm template charts/prometheus --set 'server.extraArgs.web\.enable-remote-write-receiver=' | grep remote
            - --web.enable-remote-write-receiver
```
It is fine, not sure if there is a better way 🤔

2024-05-09 16:38 UTC, h0tbird commented on charts/prometheus/templates/deploy.yaml
> +            {{- end }}
Ouch! I overlook `server.extraFlags`, this works for me too:
```console
$ helm template charts/prometheus --set 'server.extraFlags={web.enable-remote-write-receiver}' | grep remote
            - --web.enable-remote-write-receiver
```

2024-05-10 09:14 UTC, zeritti approved these changes
Thank you, @h0tbird, LGTM.

2024-05-11 18:35 UTC, merged