[prometheus-node-exporter] Add externalTrafficPolicy to prometheus node exporter service spec
prometheus-community/helm-charts pull request #4512
Opened 2024-05-02 23:14 UTC by junchil

#### What this PR does / why we need it

Add externalTrafficPolicy config option to node exporter service

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

Add externalTrafficPolicy config option to node exporter service

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-05-04 17:33 UTC, zeritti requested changes
Thank you, @junchil, for your PR. Please, see my comments below.

2024-05-04 17:33 UTC, zeritti commented on charts/prometheus-node-exporter/templates/service.yaml
>  {{- end }}
The field should not be affected by the conditional on dual stack.

I'd suggest to consider the value only if set by the user, i.e. let us keep it unset by default. 

```suggestion
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
```

2024-05-04 17:33 UTC, zeritti commented on charts/prometheus-node-exporter/values.yaml
> +  externalTrafficPolicy: Cluster
```suggestion
  externalTrafficPolicy: ""
```

2024-05-04 17:35 UTC, zeritti requested changes

2024-05-04 17:35 UTC, zeritti commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 4.33.1
A new feature should raise the minor number.

```suggestion
version: 4.34.0
```

2024-05-05 09:48 UTC, junchil commented
Hi @zeritti thank you for your review. pls review it again, thanks!

2024-05-05 16:00 UTC, zeritti approved these changes

2024-05-05 21:34 UTC, junchil commented
Hi @zeritti how can I merge this pr?

2024-05-05 21:47 UTC, merged