[prometheus-pushgateway] Adds ability to specify metricRelabelings and relabelings
prometheus-community/helm-charts pull request #453
Opened 2020-12-04 10:59 UTC by Reuuke

#### What this PR does / why we need it:

Adds the ability to add `metricRelabelings` and `relabelings` to ServiceMonitor

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-05 10:37 UTC, monotek requested changes

2020-12-05 10:37 UTC, monotek commented on charts/prometheus-pushgateway/Chart.yaml
> +version: 1.5.1
new feature should raise minor version

2020-12-07 21:11 UTC, Reuuke commented on charts/prometheus-pushgateway/Chart.yaml
> +version: 1.5.1
Bumped to 1.6.0

2020-12-08 20:27 UTC, monotek requested changes
Please sign your commits to get the DCO check passing.

2021-01-09 19:56 UTC, monotek commented
@Reuuke 
Please sign your commits to get the DCO check passing.

2021-02-03 17:46 UTC, Reuuke commented
> @Reuuke
> Please sign your commits to get the DCO check passing.

Fixed.

2021-02-04 20:53 UTC, monotek approved these changes

2021-02-04 20:54 UTC, monotek commented
@torstenwalter 
could you please merge?
waiting for maintainer review is over 2 weeks.

2021-02-04 20:59 UTC, torstenwalter approved these changes

2021-02-04 20:59 UTC, merged