[prometheus-pushgateway] Align resource label handling
prometheus-community/helm-charts pull request #456
Opened 2020-12-06 10:25 UTC by skhalash

Signed-off-by: Stanislav Khalash <stanislav.khalash@sap.com>

#### What this PR does / why we need it:
Most of the templated resources are using the `prometheus-pushgateway.defaultLabels` template to insert labels. The only difference is `Ingress` and `ServiceMonitor`, where the labels are hard-coded. This PR eliminates code duplication by aligning label handling for all resources.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-06 12:39 UTC, monotek approved these changes

2021-01-09 18:59 UTC, monotek commented
@scottrigby 
could you jump in with a review / merge please?

2021-01-12 15:53 UTC, scottrigby commented
Ah, @cstaud is also a maintainer of this chart but is not invited to the @prometheus-community/helm-charts-maintainers team 😮 I see this was worked around here https://github.com/prometheus-community/helm-charts/pull/195#issuecomment-721769838.

@prometheus-community/helm-charts-admins (@SuperQ or @bismarck) would you please invite him to the helm-charts-maintainers team? Thanks 😄 

Let's wait just a bit to get that sorted or at least give @cstaud a chance to review. I was not aware this never happened, so he was never notified of this PR and hasn't had a chance to review yet.

2021-01-12 16:03 UTC, bismarck commented
@scottrigby I don't believe I have permission to add @cstaud to the team?

2021-01-12 16:12 UTC, scottrigby commented
@bismarck apologies, autocomplete snafu 🤦‍♂️  I meant @brancz 😄 

I have also opened this issue https://github.com/prometheus-community/community/issues/31

2021-01-25 10:37 UTC, skhalash commented
@scottrigby @brancz Hey folks, sorry for bugging you, but did you have a chance to review the PR?

2021-01-25 10:58 UTC, SuperQ commented
@scottrigby Sorry, I didn't see the add member issue. Invite sent.

2021-01-25 19:24 UTC, monotek submitted a review, later dismissed

2021-01-26 00:45 UTC, zanhsieh submitted a review, later dismissed

2021-01-26 08:56 UTC, monotek approved these changes

2021-02-25 15:50 UTC, zanhsieh requested changes

2021-02-25 15:50 UTC, zanhsieh commented on charts/prometheus-pushgateway/Chart.yaml
> +version: 1.7.0
1.7.1

2021-02-27 11:40 UTC, skhalash commented on charts/prometheus-pushgateway/Chart.yaml
> +version: 1.7.0
Done

2021-02-28 00:35 UTC, monotek approved these changes

2021-03-01 02:21 UTC, zanhsieh approved these changes

2021-03-01 02:22 UTC, zanhsieh commented
@scottrigby 
could you jump in with a review / merge please?

2021-03-01 03:29 UTC, scottrigby commented
Hi yes, I believe we've waited long enough per our PROCESSES doc 👌

2021-03-01 03:29 UTC, scottrigby approved these changes

2021-03-01 03:31 UTC, scottrigby commented
Can not merge on my phone now - as settings need to be temporarily changed to do so in the GitHub app - can do on laptop tomorrow.

2021-03-04 20:20 UTC, skhalash commented
Hey @scottrigby, just a friendly reminder ;) Could you please merge it?

2021-03-05 02:50 UTC, merged

2021-03-05 02:50 UTC, scottrigby commented
Done! ✅