allow overriding service port name
prometheus-community/helm-charts pull request #4583
Opened 2024-06-03 07:27 UTC by nickaein

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-06-03 21:37 UTC, zeritti requested changes
Thank you, @nickaein, for your PR. Please, see my comments below.

2024-06-03 21:37 UTC, zeritti commented on charts/prometheus-pushgateway/Chart.yaml
> +version: 2.12.1
With a new feature, let us raise the minor number instead.
```suggestion
version: 2.13.0
```

2024-06-04 10:20 UTC, nickaein commented
Thanks @zeritti. I wasn't unsure whether I should bump the minor version. Counting it as a feature seems reasonable.

2024-06-04 15:01 UTC, zeritti approved these changes

2024-06-05 19:30 UTC, merged