[prom-label-proxy] kube-rbac-proxy support
prometheus-community/helm-charts pull request #4624
Opened 2024-06-23 17:17 UTC by sathieu

#### What this PR does / why we need it

Add kube-rbac-proxy support to prom-label-proxy.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-06-29 15:30 UTC, jkroepke commented
Hi @sathieu 

could you please add a ci test values files like https://github.com/prometheus-community/helm-charts/blob/main/charts/jiralert/ci/test-values.yaml where a full blown configuration for rbac-proxy exists? Then, everything is covered inside CI

2024-06-29 15:31 UTC, jkroepke requested changes
Hi @sathieu

could you please add a ci test values files like [main/charts/jiralert/ci/test-values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/jiralert/ci/test-values.yaml?rgh-link-date=2024-06-29T15%3A30%3A45Z) where a full blown configuration for rbac-proxy exists? Then, everything is covered inside CI

2024-07-04 10:54 UTC, sathieu commented
@jkroepke I've added `charts/prom-label-proxy/ci/kube-rbac-proxy-values.yaml`, back to you 🏀 !

2024-07-06 17:49 UTC, jkroepke commented on charts/prom-label-proxy/templates/rbac-configmap.yaml
> +  config-file.yaml: |{{ .Values.kubeRBACProxy.config | toYaml | nindent 4 }}
tbh honest, I never saw this kind of style where is pipe is inline. Pretty hard to read.
```suggestion
  config-file.yaml: |
    {{- .Values.kubeRBACProxy.config | toYaml | nindent 4 }}
```

2024-07-06 17:50 UTC, jkroepke approved these changes
LGTM 👍

2024-07-06 17:52 UTC, merged