[prometheus-adapter] Use the supported APIService API version
prometheus-community/helm-charts pull request #463
Opened 2020-12-08 12:18 UTC by mstrzele

#### What this PR does / why we need it:
* it adds support for `APIService` in version v1.

   The version v1beta1 became deprecated in Kubernetes 1.19.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #461 

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-08 20:47 UTC, monotek submitted a review, later dismissed

2020-12-12 17:10 UTC, mstrzele commented
@MattiasGees @hectorj2f @steven-sheehy wanna take a quick look at this PR? It shouldn't take much to do the review. 😉

2020-12-13 19:36 UTC, steven-sheehy requested changes
Looks good, just needs a rebase and version bump

2020-12-15 10:45 UTC, mstrzele commented
@steven-sheehy done!

2020-12-15 14:30 UTC, hectorj2f approved these changes

2020-12-15 15:57 UTC, steven-sheehy approved these changes

2020-12-15 15:58 UTC, merged