[prometheus-elasticsearch-exporter]: Prevent Duplicate Labels in ServiceMonitor
prometheus-community/helm-charts pull request #4636
Opened 2024-06-27 12:27 UTC by hlac9x

…iceMonitor

#### What this PR does / why we need it
This Pull Request resolves an issue with duplicate release labels in the ServiceMonitor when using a custom release name for Elasticsearch outside the kube-prometheus-stack. Previously, if a release label was defined in the values.yaml file, it would be applied alongside the default Helm release name, leading to duplication. 

#### Which issue this PR fixes
This fix ensures that:

- Correct Release Label: The ServiceMonitor will only use the release label defined in the values.yaml file, if provided.
- Default Helm Release Name: If no custom release label is defined, the Helm release name will be used as the default, aligning with the standard behavior within the kube-prometheus-stack.
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-06-29 09:32 UTC, zeritti reviewed
Thank you, @hlac9x, for your PR. I would like to suggest a bit more comprehensive change. 

This chart is one of a few that are still employing the old-style labels and selectors, e.g. `app`. Would you be willing to change to the current [standard labels](https://helm.sh/docs/chart_best_practices/labels/#standard-labels) and selectors, e.g. `app.kubernetes.io/name` by means of helper templates? An example is [alertmanager](https://github.com/prometheus-community/helm-charts/blob/18f399b1028084e7e924a4d1efe2ce39bbda1ee3/charts/alertmanager/templates/_helpers.tpl#L34).

This would be a major change, though, needing a note in README. We could at last move to chart v2 at the same time, taking advantage of the major change. What do you think?

2024-07-01 09:26 UTC, hlac9x commented
> Thank you, @hlac9x, for your PR. I would like to suggest a bit more comprehensive change.
> 
> This chart is one of a few that are still employing the old-style labels and selectors, e.g. `app`. Would you be willing to change to the current [standard labels](https://helm.sh/docs/chart_best_practices/labels/#standard-labels) and selectors, e.g. `app.kubernetes.io/name` by means of helper templates? An example is [alertmanager](https://github.com/prometheus-community/helm-charts/blob/18f399b1028084e7e924a4d1efe2ce39bbda1ee3/charts/alertmanager/templates/_helpers.tpl#L34).
> 
> This would be a major change, though, needing a note in README. We could at last move to chart v2 at the same time, taking advantage of the major change. What do you think?

2024-07-01 09:27 UTC, hlac9x commented
@zeritti I have update the PR. please help to review.

2024-07-02 21:43 UTC, zeritti requested changes
Thank you, @hlac9x, for your change. Please, see my comments below.

2024-07-03 01:29 UTC, hlac9x commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +    []
this was a mistake I made when testing the helm template

2024-07-03 01:29 UTC, hlac9x commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +  enabled: true
this was a mistake I made when testing the helm template

2024-07-03 01:30 UTC, hlac9x commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +  {}
this was a mistake I made when testing the helm template

2024-07-03 01:30 UTC, hlac9x commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +    release: kube-prometheus-stack
this was a mistake I made when testing the helm template

2024-07-03 01:32 UTC, hlac9x commented
@zeritti Thank you for your suggestion; there was a mistake in the values. yaml file I created while testing the Helm template. Thank you for your corrections.

2024-07-03 16:34 UTC, zeritti requested changes
Thank you, @hlac9x, for your changes. I will make some changes in README, NOTES and Chart.yaml if it is ok with you.

2024-07-03 16:34 UTC, zeritti commented on charts/prometheus-elasticsearch-exporter/values.yaml
> +    release: kube-prometheus-stack
This label's value is not applicable to all users, can be included as a comment, though.
```suggestion
labels: {}
  # release: kube-prometheus-stack
```

2024-07-03 18:32 UTC, hlac9x commented
@zeritti yes, please go ahead

2024-07-03 19:04 UTC, zeritti reviewed
@hlac9x I have extended the upgrade note as users have to know what is to be done before they can upgrade. Due to changes of the labels, NOTES also needed an update of a label. The introduced commonLabels also apply to pods. At last, we are leaving chart api v1 and thus are supporting helm v2 no more.

2024-07-04 16:14 UTC, zeritti approved these changes

2024-07-04 17:24 UTC, merged