[prometheus]Added readiness/liveness/startup probes to reload container in Prometheus pod
prometheus-community/helm-charts pull request #4696
Opened 2024-07-06 09:30 UTC by luigi-bitonti

#### What this PR does / why we need it
Readiness, liveness and startup probes were added to "configmapReload" container in Prometheus pod.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4623

#### Special notes for your reviewer

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-07-06 11:28 UTC, zeritti requested changes
Thank you, @luigi-bitonti, for your PR. Let me suggest a few changes below.

The first thing is to realise that config-reloader does not open a listening socket. We have to tell it to do so with its flag `--listen-address`. This flag has to be added to the command args and the container's `ports` field introduced. With this, we can use the httpGet probe by default. 

It is ok to reuse the code already present in the chart. We can do more with less, though. Consider these proposed fields in the values file.

```yaml
configmapReload:
  prometheus:
    containerPort: 8080        # port to listen on, argument to the flag mentioned above
    containerPortName: metrics # port name is always useful

    # We can provide access to the whole objects and take them over in templates
    livenessProbe:
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      periodSeconds: 10
      initialDelaySeconds: 2

    readinessProbe:
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      periodSeconds: 10

    # If we wish to provide the startup probe with a toggle. 
    startupProbe:
      enabled: false
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      periodSeconds: 10
```

These fields would have to be implemented in `deploy.yaml` and `sts.yaml`. What do you think?

2024-07-06 13:35 UTC, luigi-bitonti commented
I tried to adopt your suggests.

2024-07-06 17:30 UTC, zeritti requested changes
Thank you, @luigi-bitonti, for your changes. Please, see my comments and suggestions below.

2024-07-06 17:30 UTC, zeritti commented on charts/prometheus/Chart.yaml
> +version: 25.22.2
We have to make the change minor.
```suggestion
version: 25.23.0
```

2024-07-06 17:30 UTC, zeritti commented on charts/prometheus/values.yaml
> +    ## Prometheus reloader readiness and liveness probe initial delay and timeout
```suggestion
    ## Settings for Prometheus reloader's readiness, liveness and startup probes
```

2024-07-06 17:30 UTC, zeritti commented on charts/prometheus/values.yaml
> +    containerPortName: metrics
A comment will help:
```suggestion
    ## config-reloader's container port and port name for probes and metrics
    containerPort: 8080
    containerPortName: metrics 
```

2024-07-08 07:19 UTC, luigi-bitonti commented on charts/prometheus/values.yaml
> +    tcpSocketProbeEnabled: false
Why did you delete this?

2024-07-08 08:43 UTC, zeritti requested changes
Thank you, @luigi-bitonti. Please, see my comments below.

2024-07-08 08:43 UTC, zeritti commented on charts/prometheus/templates/deploy.yaml
> +            {{- toYaml $startupProbe | nindent 12 }}
Closing the conditional has somehow slipped away.
```suggestion
            {{- toYaml $startupProbe | nindent 12 }}
          {{- end }}
```

2024-07-08 08:43 UTC, zeritti commented on charts/prometheus/templates/sts.yaml
> +            {{- toYaml $startupProbe | nindent 12 }}
Closing the conditional has somehow slipped away.
```suggestion
            {{- toYaml $startupProbe | nindent 12 }}
          {{- end }}
```

2024-07-08 08:43 UTC, zeritti commented on charts/prometheus/values.yaml
> +    tcpSocketProbeEnabled: false
We do not need this field as the user can set any probe, including tcpSocket (setting default httpGet).

2024-07-08 09:29 UTC, zeritti requested changes

2024-07-08 09:29 UTC, zeritti commented on charts/prometheus/values.yaml
> +    containerPortName: metrics
Please, remove the trailing space:
```suggestion
    containerPortName: metrics
```

2024-07-08 10:22 UTC, zeritti commented
Thank you, @luigi-bitonti, for your changes. If I may ask, startupProbe is not enabled by default but should be checked by CI. Will you please enable the startupProbe in the values files 02 and 03 in the `ci` directory?

2024-07-08 11:07 UTC, zeritti approved these changes
Many thanks, @luigi-bitonti, LGTM.

2024-07-08 15:36 UTC, merged