[prometheus] added absent allowedHostPath to psp of node-exporter
prometheus-community/helm-charts pull request #470
Opened 2020-12-09 11:25 UTC by pbakulev

Signed-off-by: Pavel Bakulev <p.bakulev@bilderlings.eu>

#### What this PR does / why we need it:
PR fixes error in using podSecurityPolicy of node-exporter
```
  Type     Reason        Age                  From                  Message
  ----     ------        ----                 ----                  -------
  Warning  FailedCreate  19s (x15 over 101s)  daemonset-controller  Error creating: pods "prometheus-node-exporter-" is forbidden: unable to validate against any pod security policy: [spec.volumes[2].hostPath.pathPrefix: Invalid value: "/": is not allowed to be used]

```
#### Special notes for your reviewer:
  - addition to PR https://github.com/prometheus-community/helm-charts/pull/80
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-09 11:26 UTC, zanhsieh approved these changes

2020-12-10 11:52 UTC, monotek requested changes
Imho that error was the reason of adding: nodeExporter.extraHostPathMounts

2020-12-10 12:26 UTC, pbakulev commented
@monotek This path has been added to daemonset of node-exporter explicitly https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/node-exporter/daemonset.yaml#L124

2020-12-23 15:51 UTC, Xtigyro approved these changes

2020-12-23 15:52 UTC, Xtigyro commented
Hey @monotek - this PR sounds legit. Could you please review it once more?

2020-12-24 14:45 UTC, monotek approved these changes

2020-12-24 14:45 UTC, merged