[kube-prometheus-stack] Add scrapeClasses to prometheus resource (#4685)
prometheus-community/helm-charts pull request #4703
Opened 2024-07-08 19:06 UTC by johgoe

#### What this PR does / why we need it

This PR will add scapeClasses to the kube-prometheus-stack. It's already a feature of prometheus operator

#### Which issue this PR fixes

- fixes #4685

#### Special notes for your reviewer

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-07-08 21:27 UTC, jkroepke commented on charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
> +{{- end }}
```suggestion
{{- with .Values.prometheus.prometheusSpec.scrapeClasses }}
  scrapeClasses:
    {{- tpl (toYaml . | indent 4) $ }}
{{- end }}
```

2024-07-08 21:28 UTC, jkroepke requested changes
Please bump the chart version, thanks!

2024-07-09 05:56 UTC, johgoe commented
@jkroepke Version is bumped now.

2024-07-09 07:49 UTC, johgoe commented
@jkroepke I had to change your change to

`{{ tpl (toYaml . | indent 4) $ }}` without an intent as `{{- tpl (toYaml . | indent 4) $ }}` didn't work. The Error message was `block sequence entries are not allowed in this context`

2024-07-09 09:05 UTC, jkroepke commented
Sorry, I miss it. `nindent` should solve this case. Thats what we used for all new changes.

`{{- tpl (toYaml . | nindent 4) $ }} `

2024-07-09 13:02 UTC, johgoe commented
@jkroepke Thank you. nindent works fine. It's fixed.

2024-07-09 14:47 UTC, jkroepke approved these changes
LGTM 👍

2024-07-09 14:47 UTC, merged