fix deployment annotations
prometheus-community/helm-charts pull request #4767
Opened 2024-08-02 07:00 UTC by wsmolkowski

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-08-06 06:56 UTC, rpahli approved these changes

2024-08-23 11:30 UTC, wsmolkowski commented
@rpahli when could you merge it?

2024-08-26 07:54 UTC, rpahli commented
@wsmolkowski there are still build error. Can you pls fix the build, then we can merge your PR.

2024-09-13 11:08 UTC, rpahli commented
@wsmolkowski any update on this? can you pls fix the lint error?

2024-10-03 05:32 UTC, zanhsieh requested changes

2024-10-03 05:32 UTC, zanhsieh commented on charts/prometheus-stackdriver-exporter/templates/deployment.yaml
> +    {{ toYaml .Values.annotations | indent 4 }}
```suggestion
    {{- with .Values.annotations }}
    annotations:
    {{- toYaml .Values.annotations | indent 4 }}
    {{- end }}
```

2024-10-03 05:36 UTC, zanhsieh approved these changes

2024-10-08 06:34 UTC, rpahli approved these changes

2024-10-08 06:34 UTC, merged

2024-10-08 12:33 UTC, sboschman commented
Seems chart version 4.6.1 is broken, b/c:
```
    {{- with .Values.annotations }}
    annotations:
      {{- toYaml .Values.annotations | indent 6 }}
    {{- end }}
```

```
Error: template: prometheus-stackdriver-exporter/charts/prometheus-stackdriver-exporter/templates/deployment.yaml:9:24: executing "prometheus-stackdriver-exporter/charts/prometheus-stackdriver-exporter/templates/deployment.yaml" at <.Values.annotations>: nil pointer evaluating interface {}.annotations
```

`with` changes the context if I am not mistaken, so the `toYaml` will fail. As `.Values` should come from the root context, e.g. `$.Values.annotations` inside the `with` or simply `{{- toYaml . | indent 6 }}` should work.

2024-10-08 14:40 UTC, bc-bishwash commented
This is causing errors, with default values file:
```Error: Error: template: prometheus-stackdriver-exporter/templates/deployment.yaml:9:24: executing "prometheus-stackdriver-exporter/templates/deployment.yaml" at <.Values.annotations>: nil pointer evaluating interface {}.annotations
```

2024-10-09 09:32 UTC, devops-pump-games commented on charts/prometheus-stackdriver-exporter/templates/deployment.yaml
> +    {{- with .Values.annotations }}
I'm not sure, but looks like you should use "{{- if .Values.annotations  }}" to exclude error

```
  Error: template: prometheus-stackdriver-exporter/templates/deployment.yaml:9:24: executing "prometheus-stackdriver-exporter/templates/deployment.yaml" at <.Values.annotations>: nil pointer evaluating interface {}.annotations
  ```