[prometheus-blackbox-exporter] - Add extraConfigmapMounts to config-reloder helper template
prometheus-community/helm-charts pull request #4773
Opened 2024-08-07 06:16 UTC by nirmalkumar85

Hello @desaintmartin  @gianrubio  @rsotnychenko  @monotek 
My first contribution and thanks.

#### What this PR does / why we need it
Adds extraConfigmapMounts to config-reloader. This will align with the blackbox exporter where extraConfigmapMounts can be supplied.

In blackbox, a user can use a custom Configmap for blackbox configurations via extraConfigmapMount option to support use cases where configMap for blackbox modules are dynamically generated by external application and would be supplied as a custom configMap managed outside the helmchart. 

While we could convert all our non-sensitive configuration to a secret, however this is an anti-pattern in cases where additional process are required to validate secrets. 

The blackbox-exporter supports extraConfigmapMounts, but the config-reloader has the following problem:

The reloader will watch this path -  [- --config-file={{ .Values.configPath | default "/config/blackbox.yaml" }}](https://github.com/prometheus-community/helm-charts/blob/34a62129954c26cf9b29a8f832e8bc75665b93cf/charts/prometheus-blackbox-exporter/templates/_helpers.tpl#L183C4-L183C79)

In blackbox, a user can use a [custom configmap](https://github.com/prometheus-community/helm-charts/blob/34a62129954c26cf9b29a8f832e8bc75665b93cf/charts/prometheus-blackbox-exporter/templates/_helpers.tpl#L260) for modules. 

The config reloader cannot watch this mount. 
https://github.com/prometheus-community/helm-charts/blob/34a62129954c26cf9b29a8f832e8bc75665b93cf/charts/prometheus-blackbox-exporter/templates/_helpers.tpl#L201

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-08-07 08:55 UTC, monotek requested changes

2024-08-07 21:37 UTC, nirmalkumar85 commented on charts/prometheus-blackbox-exporter/templates/configmap.yaml
> +{{- if (eq .Values.configExistingConfigMapName: "") }}
My bad, fixed it.

2024-08-08 10:06 UTC, monotek requested changes
what about the logic in the helpers file, like: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/_helpers.tpl#L291-L294 ?

2024-08-08 10:06 UTC, monotek commented on charts/prometheus-blackbox-exporter/templates/configmap.yaml
>  {{- if and .Values.config (eq .Values.configExistingSecretName "") }}
```suggestion
{{- if and .Values.config (or (eq .Values.configExistingSecretName "") (eq .Values.configExistingConfigMapName: ""))}}
```

2024-09-25 23:05 UTC, nirmalkumar85 commented
Apologies @monotek. I was away for extended time due to personal reasons and not able to work on this.

2024-11-08 09:04 UTC, monotek commented on charts/prometheus-blackbox-exporter/Chart.yaml
> +version: 9.1.1
```suggestion
version: 9.2.0
```

2024-11-08 09:09 UTC, monotek requested changes
please fix lint

2025-04-25 02:04 UTC, closed without merging