[Fix] Fix Grafana for container_memory_working_set_bytes metric
prometheus-community/helm-charts pull request #49
Opened 2020-09-06 05:38 UTC by mohsenmottaghi

Signed-off-by: Mohsen Mottaghi <mohsenmottaghi@outlook.com>

duplicated from https://github.com/helm/charts/pull/23656

### Describe the bug:
since you merged https://github.com/helm/charts/pull/22586 we faced with duplication on our Grafana dashboards that use `container_memory_working_set_bytes` metrics
 
### What this PR does / why we need it:
we change our queries that use `container_memory_working_set_bytes` for calculating memory details to use from stable `/metrics/cadvisor` metric path

#### Which issue this PR fixes
https://github.com/helm/charts/issues/23249

2020-09-08 22:34 UTC, monotek requested changes
Please raise chart version

2020-09-09 06:35 UTC, mohsenmottaghi commented
I raised the chart version :smiley:

2020-09-09 07:09 UTC, monotek submitted a review, later dismissed

2020-09-09 15:57 UTC, monotek commented
Please resolve conflicts.

2020-09-12 10:46 UTC, closed without merging