[prometheus-blackbox-exporter] Adjust configPath handling
prometheus-community/helm-charts pull request #4915
Opened 2024-10-15 12:55 UTC by Jakob3xD

#### What this PR does / why we need it
**Issue**
I want to deploy the config map for the Blackbox config on my own, as I want to write some logic that adjust the ConfigMap more dynamically. Therefore I need to `null` the `config` value as otherwise the ConfigMap is created with the default chart values. When setting `config` to `null` the config path is set to `/etc/blackbox_exporter/config.yml` which does not exist.

**Changes**
I changed the config path logic to match the one of the config reloader. If no `configPath` is set, we use the default of `/config/blackbox.yaml` otherwise we use the `configPath` value. The default value of `/etc/blackbox_exporter/config.yml` gets removed as I don´t see the point in keeping it. If needed it can be set via `configPath`.

As it its a breaking change, I also bumped the version.

#### Which issue this PR fixes
 None

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-11-06 17:58 UTC, monotek requested changes

2024-11-06 17:58 UTC, monotek commented on charts/prometheus-blackbox-exporter/templates/_helpers.tpl
> +  - --config.file={{ .Values.configPath | default "/config/blackbox.yaml" }}
As this is a major updat anyway we might think about to rename the var to `.Values.configFile` too.
Imho this fits better as the var currently contains a filename and not only the path.
Thoughts?

2025-02-10 08:16 UTC, Jakob3xD commented on charts/prometheus-blackbox-exporter/templates/_helpers.tpl
> +  - --config.file={{ .Values.configPath | default "/config/blackbox.yaml" }}
I am really sorry for the late response. I lost track of the PR.

You are correct, that naming it configPath would match its actual purpose.

2025-02-11 10:00 UTC, monotek commented on charts/prometheus-blackbox-exporter/templates/_helpers.tpl
> +  - --config.file={{ .Values.configPath | default "/config/blackbox.yaml" }}
But the file does exist in the docker image: https://github.com/prometheus/blackbox_exporter/blob/master/Dockerfile#L9C1-L9C49

2025-02-12 08:27 UTC, Jakob3xD commented on charts/prometheus-blackbox-exporter/templates/_helpers.tpl
> +  - --config.file={{ .Values.configPath | default "/config/blackbox.yaml" }}
You are right, I was looking at the wrong container (config reloader).

I'll close the PR. However, I am asking if config reloader should be removed if no config and no config Path is set, as it wouldn't do anything.

2025-02-12 08:28 UTC, closed without merging