[Close #4940] feat(prometheus-postgres-exporter): support custom TLS config
prometheus-community/helm-charts pull request #4941
Opened 2024-10-26 11:59 UTC by volker-raschek

The following patch extends the serviceMonitor resource to allow users to apply a custom TLS configuration for TLS authentication and encryption between prometheus and the postgres-exporter. Furthermore, the protocol scheme can now be customized. The default is `http` but needs to be changed to `https`, when TLS authentication/encryption should be applied.

Nevertheless, the postgres-exporter has currently a feature gap. The application is not able to listen on HTTPS. For this reason, this patch creates the possibility to customize the TLS configuration, but this will not help until the following issue is closed.

https://github.com/prometheus-community/postgres_exporter/issues/454

If the aforementioned issue is resolved, a user-specific TLS configuration can be applied as follows.

```yaml
serviceMonitor:
  enabled: true
  scheme: https
  tlsConfig:
    caFile: /etc/prometheus/tls/ca/ca.crt
    certFile: /etc/prometheus/tls/app2app/tls.crt
    keyFile: /etc/prometheus/tls/app2app/tls.key
    insecureSkipVerify: false
    serverName: prometheus-postgres-exporter
```

Important Note: The `serverName` attribute must correspond to the CommonName or a Subject Alternative Name (SAN) of the TLS certificate. If this is not the case, prometheus will reject the connection trying to match the IP address of the pod with the CommonName / SAN.

The client certificate and private key as well as the certificate of the certificate authorithy must be mounted additionally via the `extraVolumes` and `extraVolumeMounts` option. This configuration is not standard and must also be implemented by the user if TLS client authentication is required.

2024-10-26 13:06 UTC, zeritti commented
Thank you, @volker-raschek, for your PR. Please, sign your commits.

2024-10-26 16:40 UTC, zeritti commented
Please, bump the version in Chart.yaml (this would be a minor change).

2024-10-26 16:45 UTC, zeritti requested changes

2024-10-26 16:45 UTC, zeritti commented on charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
> +{{- . | toYaml | nindent 6 }}
This way is more common:

```suggestion
{{- toYaml . | nindent 6 }}
```

2024-10-26 16:46 UTC, volker-raschek commented on charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
> +{{- . | toYaml | nindent 6 }}
I will change that.

2024-10-26 16:52 UTC, volker-raschek commented
Hi @zeritti,
I have currently a problem. I've tried to apply the configuration but receive from kubelet an error of the readyness and livenessProbe. The HTTP request returns an unexpected HTTP response, which leads to a CrashbackLoop.

```bash
$ kubectl describe pod prometheus-postgres-exporter-6899b46b7c-7lz9p
...
  Warning  Unhealthy  10m (x9 over 11m)      kubelet            Readiness probe failed: Get "https://10.244.7.17:9187/": remote error: tls: certificate required
  Warning  Unhealthy  10m (x6 over 11m)      kubelet            Liveness probe failed: Get "https://10.244.7.17:9187/": remote error: tls: certificate required
```

I'm not sure whether the httpGet request is correct if the kubelet lacks TLS authentication. 

Would it be possible to simply check the TCP socket instead of httpGet? I would add an option that leaves the default at httpGet and only checks the tcpSocket on request.

The colleagues at gitea do something similar: https://gitea.com/gitea/helm-chart/src/branch/main/values.yaml#L460

2024-10-26 17:35 UTC, zeritti commented
> Would it be possible to simply check the TCP socket instead of httpGet? I would add an option that leaves the default at httpGet and only checks the tcpSocket on request.

I'd suggest taking readiness and liveness probes' parameters out of the template as they are now and keep them in the values. In this way, they can be fully customized which is quite often needed. The template will just take each field as a whole, would include e.g. 

```yaml
{{- with .Values.livenessProbe }}
livenessProbe:
  {{- toYaml . | nindent 12 }}
{{- end }}
```

whilst values would include the current settings as defaults

```yaml
livenessProbe:
  initialDelaySeconds: 0 
  timeoutSeconds: 3 
  httpGet:
    path: /
    port: http
    scheme: HTTP
```

In this way one could set any probe type.

2024-10-27 11:19 UTC, volker-raschek commented
Hi @zeritti,
I've updated my patch. Please take a review :)

2024-10-27 13:04 UTC, zeritti requested changes

2024-10-27 13:04 UTC, zeritti commented on charts/prometheus-postgres-exporter/values.yaml
> +# `CrashBackLoop`, because kubelet receives the error message that a TLS certificate is required for authentication.
Let us keep it brief, please.

```suggestion
# Configurable probes. If TLS client authentication is enabled at the exporter, TCP probe must be used.
```

2024-10-27 13:20 UTC, volker-raschek commented on charts/prometheus-postgres-exporter/values.yaml
> +# `CrashBackLoop`, because kubelet receives the error message that a TLS certificate is required for authentication.
Applied

2024-10-27 13:39 UTC, zeritti approved these changes
LGTM

2024-10-27 18:31 UTC, merged