[prometheus] Update Helm dependency to use new kube-state-metrics chart location
prometheus-community/helm-charts pull request #497
Opened 2020-12-16 07:27 UTC by chris-vest

#### What this PR does / why we need it:

1) Updates location of `kube-state-metrics` chart dependency to https://kubernetes.github.io/kube-state-metrics - this is its new home.
2) Updates the version of the `kube-state-metrics` dependency to `"2.9.*"` - this will allow for support of using the latest features of the chart

#### Which issue this PR fixes
None.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-16 07:30 UTC, torstenwalter approved these changes

2020-12-16 07:31 UTC, chris-vest commented
@torstenwalter Looks like their new Helm repo hasn't been set up properly.

2020-12-16 07:31 UTC, chris-vest commented
```➜ helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
Error: looks like "https://kubernetes.github.io/kube-state-metrics" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes.github.io/kube-state-metrics/index.yaml : 404 Not Found```

2020-12-16 07:33 UTC, torstenwalter requested changes
CI reports:

 `Error: could not find : chart kube-state-metrics not found in https://kubernetes.github.io/kube-state-metrics`.

You need to add the repository to [ct.yaml](https://github.com/prometheus-community/helm-charts/blob/main/ct.yaml#L6-L9) to fix it.

```
chart-repos:
  - stable=https://charts.helm.sh/stable
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
  - kube-state-metrics=https://kubernetes.github.io/kube-state-metrics
```

2020-12-16 07:37 UTC, chris-vest commented
@torstenwalter Locally it doesn't work either, the `kube-state-metrics` new Chart repo doesn't have the `index.yaml` file. 

I have pivoted to just updating the allowed dependency version to `2.9.*` and not changing the chart location.

2020-12-16 07:38 UTC, torstenwalter commented
@chris-vest You are right. I just double checked it. The `gh-pages` branch is still missing in that repository and the first version still needs to be published.

2020-12-16 07:40 UTC, chris-vest commented
> @chris-vest You are right. I just double checked it. The `gh-pages` branch is still missing in that repository and the first version still needs to be published.

I'm happy to monitor it and do another PR to update to the new location once they've set that up properly.

2020-12-16 08:08 UTC, torstenwalter commented
https://github.com/kubernetes/kube-state-metrics/pull/1326

2020-12-16 08:12 UTC, chris-vest commented
> [kubernetes/kube-state-metrics#1326](https://github.com/kubernetes/kube-state-metrics/pull/1326)

I've reverted to use the new repo again.

2020-12-18 10:41 UTC, monotek commented
https://kubernetes.github.io/kube-state-metrics/index.yaml brings a 404.
Seems repo needs some more fixes: https://github.com/kubernetes/kube-state-metrics/pull/1329

2020-12-18 18:55 UTC, scottrigby commented
Hang tight. We now know this was due to automated settings controlled by prow (for anyone curious, this is it: https://github.com/kubernetes/kube-state-metrics/pull/1334#issuecomment-748113824). This PR should fix that: https://github.com/kubernetes/test-infra/pull/20291

We'll then need to make another PR like https://github.com/kubernetes/kube-state-metrics/pull/1334 again. Unless there are other issues, this should add and index the next release.

2020-12-22 18:28 UTC, scottrigby commented
Follow-up PR https://github.com/kubernetes/test-infra/pull/20322 ⏳

2021-01-13 09:24 UTC, mrueg commented
@chris-vest @monotek @torstenwalter thanks to @scottrigby the repo has been set up now: https://kubernetes.github.io/kube-state-metrics/ 

@chris-vest can you fix the merge conflicts on your PR?

2021-01-13 09:35 UTC, chris-vest commented
@mrueg All done!

2021-01-13 12:48 UTC, torstenwalter submitted a review, later dismissed

2021-01-13 12:49 UTC, torstenwalter commented
Now it just needs an approval from one of the chart maintainers and we are good to go :100:

2021-01-13 12:52 UTC, naseemkullah submitted a review, later dismissed

2021-01-13 14:26 UTC, torstenwalter commented
@naseemkullah do you want to merge it or does it need another review from you opinion?

2021-01-13 14:36 UTC, naseemkullah commented
@torstenwalter I know @monotek recently change ksm related stuff so thought he might want to have a look, but then again we have the required 2 approvers, let's merge by EOD.

2021-01-14 06:31 UTC, chris-vest commented
@torstenwalter @naseemkullah Sorry guys,  I just pushed up a change to the `values.yaml` in order to provide the right link to the chart - it'll need another review.

2021-01-14 07:43 UTC, torstenwalter approved these changes

2021-01-14 15:07 UTC, naseemkullah commented on ct.yaml
> +  - kube-state-metrics=https://kubernetes.github.io/kube-state-metrics
Are bitnami charts still required anywhere else in the repo? If not it could be removed from here.

2021-01-14 15:07 UTC, naseemkullah approved these changes

2021-01-14 15:40 UTC, merged