[prometheus-kafka-exporter] Use helm test hooks
prometheus-community/helm-charts pull request #498
Opened 2020-12-16 09:00 UTC by Minutis

#### What this PR does / why we need it: do not deploy test `kafka` and `zookeeper` pods in production.

#### Which issue this PR fixes
  - fixes 475

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-16 18:15 UTC, gkarthiks submitted a review, later dismissed

2020-12-17 08:48 UTC, Minutis commented
I am not sure how to fix pipeline. Any help is appreciated. I do not have any experience with chart testing.

2020-12-18 17:22 UTC, monotek commented
I'm not sure whats the prefered way here.

In another project i used a helm dependency for ci. See: https://github.com/kokuwaio/helm-charts/tree/main/charts/mysqldump
But might be overkill to add a chart dependency, even if disabled by default, just for ci.

On the other hand kafka used through a helm chart should work with complete configuration out of the box. Should even solve the zookeeper config, as seen in: https://artifacthub.io/packages/helm/bitnami/kafka

2020-12-28 22:14 UTC, monotek requested changes

2020-12-28 22:14 UTC, monotek commented on charts/prometheus-kafka-exporter/Chart.yaml
> +version: 0.2.1
As helm v2 api is used this is a breaking change and new chart version should be 1.0

2020-12-28 22:14 UTC, monotek commented on charts/prometheus-kafka-exporter/values.yaml
> +  enabled: true
This should be false by default.
It should be enabled only through ci like in my example.

2020-12-28 22:14 UTC, monotek commented on ct.yaml
> +  - kafka=https://charts.bitnami.com/bitnami
Please rename repo to bitnami as it also contains other charts.

2020-12-29 07:51 UTC, Minutis commented
Can't get test tun run... Didn't even do anything related to serviceaccounts, still getting:
```
Error: serviceaccounts "prometheus-kafka-exporter-es5m8l6yyp" already exists
```

2021-01-21 10:26 UTC, arvidviderberg commented
Hello, we're having the same issue and would really get this PR working. Can we help in any way? 🙂

2021-01-21 10:29 UTC, Minutis commented
Problem is with testing - I can not get these tests to pass.

2021-01-21 10:31 UTC, arvidviderberg commented
Maybe @gkarthiks or @golgoth31 can assist? 🙂

2021-01-21 11:27 UTC, golgoth31 commented
Hi all,
for the last run, we got this error:
Error: services "prometheus-kafka-exporter-gdy24x19ba" already exists

2021-01-21 11:34 UTC, golgoth31 commented
perhaps the check action is a bit old:
uses: helm/chart-testing-action@v1.0.0
while the current version is v2.0.1: https://github.com/helm/chart-testing-action/releases

2021-01-22 17:54 UTC, monotek commented
With the changes i've pushed it works locally.

Neverthelless the current error could be indeed be a problem of to old chart testing action, as lookup function was added to helm 3.1(?) and i'm not sure which helm version is used in the action.

@scottrigby @torstenwalter 
I guess we should update the ci pipline.
I've created a pr for this: https://github.com/prometheus-community/helm-charts/pull/611

2021-01-22 19:37 UTC, monotek approved these changes

2021-01-23 05:52 UTC, gkarthiks commented
I am just waiting for admins to confirm the changes are good to go across all charts.

2021-01-23 11:21 UTC, monotek commented
If #611 is merged first and this one is rebased were good to go too :)

2021-01-23 17:54 UTC, monotek submitted a review, later dismissed

2021-01-23 19:51 UTC, monotek commented
@prometheus-community/helm-charts-admins 
we have a change in the ct.yaml here so i guess on of you guys has to approve and merge...

2021-01-24 11:25 UTC, monotek approved these changes

2021-01-24 11:26 UTC, monotek commented
@gkarthiks 
i've removed the change in the ct.yaml as bitnami repo was already inside so you should be able to merge it now :)

2021-01-24 11:29 UTC, gkarthiks approved these changes
amazing changes for stabilization. Thank you all for the effort towards this. 🚀

2021-01-24 11:29 UTC, merged