[prometheus] bump to 2.55.1
prometheus-community/helm-charts pull request #4984
Opened 2024-11-09 15:01 UTC by DrFaust92

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-11-09 23:23 UTC, zanhsieh approved these changes, later dismissed

2024-11-11 18:41 UTC, zeritti requested changes

2024-11-11 18:41 UTC, zeritti commented on charts/prometheus/Chart.yaml
> +version: 25.29.1
I reckon we should bump the minor number
```suggestion
version: 25.30.0
```

2024-11-11 21:19 UTC, zeritti approved these changes

2024-11-11 21:20 UTC, merged