[prometheus-postgres-exporter] Implement multiple target with /probe …
prometheus-community/helm-charts pull request #5012
Opened 2024-11-21 19:03 UTC by festeveira

…endpoint

#### What this PR does / why we need it
This PR allows the user to use the multiple target support implemented by the exporter. It allows defining several postgres database targets, using the same or different auth modules. 

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-11-29 14:15 UTC, zanhsieh approved these changes

2024-11-29 18:15 UTC, zeritti requested changes
Thank you, @festeveira, for your PR. Please, see my comments below.

2024-12-02 10:54 UTC, festeveira commented on charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
> +          - {{ .endpoint }}:{{ .port | default 5432 }}/postgres
I'm sorry, I was not quite sure about this one. Would you implement it as a parametrizable value? From the exporter docs I'm not sure how it behaves when you point to a different database. I get the same results experimenting.

2024-12-02 18:24 UTC, zeritti requested changes

2024-12-02 18:24 UTC, zeritti commented on charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
> +          - {{ .endpoint }}:{{ .port | default 5432 }}/postgres
The path should not be there. Consider scraping instance pg01 by means of the exporter through a URL where you'd set 

```bash
/probe?target=pg01:5432&auth_module=pg01
```

The _target_ is just a PostgreSQL instance details for which will be read out of the corresponding module.

2024-12-03 15:42 UTC, festeveira commented on charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
> +          - {{ .endpoint }}:{{ .port | default 5432 }}/postgres
I understand. But, in my setup, I'm monitoring three different postgresql instances, all with different versions, 9.4, 14.2 and 15, and if I request the probe endpoint like you say I get `pg_up 0` and no other metrics. I always need to define a path with a valid database. Am I doing something wrong? Can you define the path in the `auth_modules`?

2024-12-09 02:14 UTC, zanhsieh approved these changes

2024-12-09 18:58 UTC, zeritti approved these changes
Thank you, @festeveira, LGTM.

2024-12-09 19:01 UTC, merged