[prometheus] bump to 3.0.0
prometheus-community/helm-charts pull request #5017
Opened 2024-11-23 02:43 UTC by DrFaust92

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-11-26 18:18 UTC, zeritti requested changes
Thank you, @DrFaust92, for your PR. We have to add an upgrade note with a major change. 
Users should refer to 
- migration guide at https://prometheus.io/docs/prometheus/latest/migration/#prometheus-3-0-migration-guide
- release notes at https://github.com/prometheus/prometheus/releases/tag/v3.0.0

before upgrading.

2024-11-27 01:30 UTC, DrFaust92 commented
thanks [zeritti](https://github.com/zeritti), added

2024-11-27 01:54 UTC, zanhsieh submitted a review, later dismissed

2024-11-27 13:35 UTC, zeritti submitted a review, later dismissed

2024-11-27 16:13 UTC, zeritti approved these changes

2024-11-27 16:14 UTC, merged