[prometheus-cloudwatch-exporter] Add the fsGroup:65534 to the security context
prometheus-community/helm-charts pull request #502
Opened 2020-12-17 14:40 UTC by jp

#### What this PR does / why we need it:

Configuring the fsGroup in the securityContext prevents an authentication issue when running the cloudwatch exporter in EKS

#### Which issue this PR fixes
  - fixes https://github.com/prometheus/cloudwatch_exporter/issues/303

#### Checklist
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-17 16:04 UTC, torstenwalter commented
@jp change looks good. You need to fix [DCO](https://github.com/prometheus-community/helm-charts/pull/502/checks?check_run_id=1570941943) check.

2020-12-18 15:41 UTC, monotek approved these changes

2020-12-18 15:41 UTC, monotek requested changes
please sign your commits to get dco check passing

2020-12-20 17:24 UTC, monotek approved these changes

2020-12-20 21:29 UTC, torstenwalter approved these changes

2020-12-20 21:29 UTC, merged