[prometheus-elasticsearch-exporter] Update pod labels
prometheus-community/helm-charts pull request #5031
Opened 2024-11-29 18:08 UTC by jimmybchopps

#### What this PR does / why we need it

To increase traceability throughout the application by adding more of the standardized kubernetes labels to pod workloads in addition to the stateful set itself.

#### Special notes for your reviewer

Originally, the pod labels were only get the selector labels, this update adds all including the selector labels so no labels are being removed; only a few are being added to the pod.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-11-29 18:10 UTC, jimmybchopps commented
PR ready for review please @svenmueller @desaintmartin @zeritti 

Please let me know if there are any questions.  Thanks!!!

2024-12-18 20:37 UTC, zeritti requested changes
Thank you, @jimmybchopps, for your PR. Please, see my comments below.

Adding the version label will cause an unnecessary restart of the exporter at release upgrade, even though the upgrade does not affect the pod template's spec.

2024-12-18 20:37 UTC, zeritti commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 6.5.2
Please, raise the minor version number.
 ```suggestion
version: 6.6.0
```

2024-12-22 16:16 UTC, zeritti approved these changes
LGTM

2024-12-22 16:16 UTC, merged