update and document grafana default admin creds
prometheus-community/helm-charts pull request #505
Opened 2020-12-18 04:33 UTC by adamkgray

notes:
- explicitly expose the grafana adminUser value
- generate a psuedo-random grafana admin password by default

Signed-off-by: adamkgray <adamkgray@pm.me>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-18 11:26 UTC, monotek commented on charts/kube-prometheus-stack/values.yaml
> +  adminPassword: ""
imho thats a breaking change, even if nobody should use a static password here.
not sure if it should be a bugfix or major breaking change?

please also raise chart version.

2020-12-18 11:26 UTC, monotek requested changes
.

2020-12-18 20:09 UTC, scottrigby commented
Please see this comment https://github.com/prometheus-community/helm-charts/issues/506#issuecomment-748295501

2021-01-19 12:16 UTC, monotek requested changes
Please rebase master / update version.

2021-01-29 09:56 UTC, vsliouniaev commented
I don't think it's a good idea to change the defaults like this. They are currently inheriting defaults from the upstream grafana chart, so if it doesn't make sense to do there I don't think it makes sense to do here

2021-03-14 14:17 UTC, closed without merging