[prometheus-rabbitmq-exporter] upgrade to 1.0.0
prometheus-community/helm-charts pull request #5100
Opened 2024-12-26 18:18 UTC by DrFaust92

#### What this PR does / why we need it

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2024-12-26 22:35 UTC, monotek requested changes
Readme should contain upgrade instructions /& explanation why the major upgrade.

2024-12-27 07:37 UTC, DrFaust92 commented
[monotek](https://github.com/monotek) added, a major image version change requires a bump in chart image to reflect possible upstream breaking changes

2025-01-13 03:16 UTC, DrFaust92 commented
[monotek](https://github.com/monotek) can we move this?

2025-01-21 15:17 UTC, monotek approved these changes

2025-01-21 15:18 UTC, merged