[prometheus-push-gateway] Add lifecycle hooks
prometheus-community/helm-charts pull request #5103
Opened 2024-12-29 22:05 UTC by duncaan

Fixes #5102

Add support for lifecycle hooks in the push-gateway deployment.

* Add lifecycle hooks configuration to `charts/prometheus-pushgateway/templates/deployment.yaml`
* Add lifecycle hooks configuration to `charts/prometheus-pushgateway/templates/statefulset.yaml`
* Add lifecycle hooks configuration options in `charts/prometheus-pushgateway/values.yaml`

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/prometheus-community/helm-charts/pull/5103?shareId=0d96fb60-61f4-458c-ad32-e5e0e0c1a16e).

2024-12-30 07:29 UTC, zeritti requested changes
Thank you, @duncaan, for your PR. Please, see my comments below.

2024-12-30 07:29 UTC, zeritti commented on charts/prometheus-pushgateway/templates/deployment.yaml
> +        {{- toYaml .Values.lifecycle | nindent 8 }}
I'd suggest not to set an empty field:
```suggestion
      {{- with .Values.lifecycle }}
      lifecycle:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2024-12-30 07:29 UTC, zeritti commented on charts/prometheus-pushgateway/templates/statefulset.yaml
> +        {{- toYaml .Values.lifecycle | nindent 8 }}
As above.

2024-12-30 15:26 UTC, duncaan commented on charts/prometheus-pushgateway/templates/deployment.yaml
> +        {{- toYaml .Values.lifecycle | nindent 8 }}
Thank you for the feedback.

2024-12-30 16:54 UTC, zeritti requested changes
Thanks for your changes. I did not immediately realise then that podSpec was defined in the helper template `prometheus-pushgateway.podSpec` in `_helpers.tpl`. The lifecycle field has to go in there.

2024-12-31 16:44 UTC, zeritti approved these changes
Placement of the lifecycle field has been corrected, a test case is included.

2024-12-31 16:46 UTC, merged