Rmq labels
prometheus-community/helm-charts pull request #513
Opened 2020-12-22 08:23 UTC by machine424

#### What this PR does

Allow adding labels to the pods so we can contact rabbitmq pods when a networkpolicy is enabled.

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-12-22 17:14 UTC, monotek requested changes

2020-12-30 11:51 UTC, machine424 commented on charts/prometheus-rabbitmq-exporter/Chart.yaml
> +version: 0.7.0
Actually there is another PR that bumps the version to `0.6.0` https://github.com/prometheus-community/helm-charts/pull/416, I can merge the two of them, I just want this to be released.

2021-01-09 17:58 UTC, monotek requested changes

2021-01-09 17:58 UTC, monotek commented on charts/prometheus-rabbitmq-exporter/Chart.yaml
> +version: 0.7.0
I would suggest to use 0.6.0 anyway for now so nobody merges by accident and versions are skipped.

2021-01-11 11:26 UTC, machine424 commented on charts/prometheus-rabbitmq-exporter/Chart.yaml
> +version: 0.7.0
Ok, but I kept two commits

2021-01-11 13:31 UTC, monotek approved these changes

2021-01-21 09:24 UTC, merged

2021-02-03 10:25 UTC, machine424 commented
This was merged but the version `0.6.0` wasn't bumped to `0.7.0`.

`0.6.0` wasn't "overridden" because the release step has failed.

2021-02-03 11:08 UTC, desaintmartin commented
Hm, this seems to be a issue in our workflow, since all tests passed and Github proposed me to merge anyway (but there was another merge in the meantime).