kube-prometheus-stack: Document cert-manager usage
prometheus-community/helm-charts pull request #574
Opened 2021-01-12 19:35 UTC by MythicManiac

Add instructions on how to enable admission webhook TLS certificate provisioning via cert-manager to the readme.

2021-01-12 19:37 UTC, MythicManiac commented
I don't think the CI failure regarding chart bump is valid here given that it's a README change?

2021-01-12 19:40 UTC, MythicManiac commented
Let me know if you feel like signoff and/or chart version bump is actually required in this case. Since it's just a documentation change I personally feel like those might be a bit overkill, but I'll gladly follow suit if that's how this project rolls

2021-01-15 12:37 UTC, monotek requested changes
Please raise chart version and sign your commits.

2021-01-15 13:29 UTC, MythicManiac commented
@monotek done

2021-01-16 19:29 UTC, monotek approved these changes

2021-01-20 13:21 UTC, gkarthiks commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 12.12.2
@MythicManiac can you please bump the chart version

2021-01-20 19:34 UTC, bismarck approved these changes
lgtm

2021-01-20 19:35 UTC, merged