[prometheus-pushgateway] Adds imagePullSecrets value for deployment
prometheus-community/helm-charts pull request #608
Opened 2021-01-21 17:18 UTC by nabt

Signed-off-by: Nick Abt <nicholas-abt@pluralsight.com>

#### What this PR does / why we need it:
It adds `imagePullSecrets` handling for the deployment of the `prometheus-pushgateway` chart to allow injection of `imagePullSecrets` for custom image registries.  This brings the chart in line with other prometheus charts and common practices.  Such registries are commonly in use in airgapped Kubernetes instances.

#### Which issue this PR fixes

#### Special notes for your reviewer:
@gianrubio @cstaud 

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-01-21 17:19 UTC, nabt commented
Alerting maintainers mentioned in chart:  @gianrubio @cstaud

2021-01-23 11:24 UTC, monotek requested changes
New feature should raise minor version

2021-01-29 10:56 UTC, monotek approved these changes

2021-01-31 13:34 UTC, cstaud approved these changes

2021-01-31 13:34 UTC, cstaud approved these changes

2021-02-02 14:22 UTC, hectorj2f approved these changes

2021-02-04 19:24 UTC, monotek commented
@torstenwalter 
we've reached the 2 weeks wait window of maintainer approval here.
could you please merge?

2021-02-04 20:34 UTC, torstenwalter approved these changes
LGTM

2021-02-04 20:36 UTC, merged