[prometheus] Add naseemkullah as maintainer
prometheus-community/helm-charts pull request #63
Opened 2020-09-08 03:26 UTC by naseemkullah

👋 
I've made a few contributions overtime and we have been using this chart extensively in production at Transit for over 2 years.

I'd like to look into eventually simplifying/cleaning up the chart and modularizing it by using node-exporter, pushgateway and potentially alertmanager subcharts.

2020-09-08 04:52 UTC, scottrigby requested changes

2020-09-08 04:52 UTC, scottrigby commented on charts/prometheus/Chart.yaml
> +  - name: naseem
Also add to /.github.com/CODEOWNERS

2020-09-08 04:59 UTC, scottrigby commented
I support this. Naseem helped get this repo migration conversation started with prometheus devs earlier in the year, and would be very helpful collaborating with you all and prom devs to further simplify the chart.

2020-09-08 15:44 UTC, monotek submitted a review, later dismissed
Thumps up from me too 😎

2020-09-08 19:15 UTC, Xtigyro commented
@naseemkullah I would appreciate if you could msg me on the Kubernetes Community Slack workspace - Miro Hadzhiev - so we can have a small chat and get to know each other before proceeding with this PR.

2020-09-08 19:36 UTC, Xtigyro approved these changes

2020-09-08 19:37 UTC, Xtigyro commented
@monotek There were some changes pushed - I would like to ask for a re-approval.

2020-09-08 19:38 UTC, monotek approved these changes

2020-09-08 19:43 UTC, Xtigyro commented
@scottrigby Your finishing shot please, he-he-he 🥇

2020-09-09 00:08 UTC, zanhsieh approved these changes

2020-09-09 00:49 UTC, scottrigby approved these changes

2020-09-09 00:49 UTC, merged