[prometheus-mysql-exporter] fixed link to Prometheus MySQL Exporter repo
prometheus-community/helm-charts pull request #630
Opened 2021-02-04 03:36 UTC by andyli

#### What this PR does / why we need it:

Just fixing a broken link.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

N/A

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-02-04 04:15 UTC, andyli commented
The failed test is about Chart Version bumped. Not sure if it's really needed for such a minor README fix...

2021-02-04 20:55 UTC, monotek requested changes
please raise chart version

2021-02-05 01:27 UTC, andyli commented
Bumped chart version as requested.

Pushed an irrelevant commit (removed) which added several review request, sorry about that.

2021-02-08 02:10 UTC, monotek approved these changes

2021-02-08 02:10 UTC, merged