[prometheus-mysql-exporter] Add securityContext and podSecurityContext
prometheus-community/helm-charts pull request #662
Opened 2021-02-10 09:22 UTC by ryjogo

#### What this PR does / why we need it:
Adds securityContext and podSecurityContext to be able to run the image as a `nobody` user

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-02-15 14:01 UTC, monotek requested changes

2021-02-15 14:01 UTC, monotek commented on charts/prometheus-mysql-exporter/Chart.yaml
> +version: 1.0.3
new feature should raise minor version.

2021-02-15 14:14 UTC, ryjogo commented on charts/prometheus-mysql-exporter/Chart.yaml
> +version: 1.0.3
correct, thanks.

2021-02-16 20:00 UTC, monotek requested changes

2021-02-16 20:00 UTC, monotek commented on charts/prometheus-mysql-exporter/Chart.yaml
> +version: 1.0.3
New feature should raise minor version.

2021-02-17 08:48 UTC, monotek approved these changes

2021-02-17 08:48 UTC, monotek requested changes
Please sign your commits to get the dco check passed.

2021-02-17 09:17 UTC, ryjogo commented
Apologies, forgot to sign.. should be ok now.

2021-02-17 13:55 UTC, monotek approved these changes

2021-02-17 13:55 UTC, merged