[prometheus-postgres-exporter]: Add annotations to postgres-exporter ServiceAccount
prometheus-community/helm-charts pull request #679
Opened 2021-02-16 16:18 UTC by hhtpcd

#### What this PR does / why we need it:

Allow setting annotations on the ServiceAccount used by the
postgres-exporter Deployment. If we are running a sidecar container such
as the Google Cloud SQL Proxy we can annotate the service account to
enable Workload Identity. The approach is the same in EKS clusters
also.

I notice in the `values.yaml` there is already a reference to running the
cloud SQL proxy as a sidecar container.

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-02-16 20:21 UTC, monotek requested changes

2021-02-16 20:21 UTC, monotek commented on charts/prometheus-postgres-exporter/Chart.yaml
> +version: 1.9.2
New feature should raise minor version.

2021-02-16 20:50 UTC, hhtpcd commented on charts/prometheus-postgres-exporter/Chart.yaml
> +version: 1.9.2
Thanks, addressed. Bumped to `1.10.0`

2021-02-16 21:01 UTC, monotek approved these changes

2021-02-19 09:47 UTC, hhtpcd commented
@gianrubio @zanhsieh Do let me know if there is anything missing from the pull request :)

2021-02-20 13:14 UTC, zanhsieh approved these changes

2021-02-20 13:14 UTC, merged