[prometheus-node-exporter] Kubernetes recommanded labels node exporter
prometheus-community/helm-charts pull request #694
Opened 2021-02-20 19:09 UTC by nlamirault

#### What this PR does / why we need it:

Add Kubernetes recommanded labels : 

```yaml
---
# Source: prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-prometheus-node-exporter
  namespace: default
  labels:     
    app: prometheus-node-exporter
    app.kubernetes.io/component: prometheus-node-exporter
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/part-of: prometheus-node-exporter  
    chart: prometheus-node-exporter-1.16.0
    heritage: Helm
    release: RELEASE-NAME
  annotations:
    {}
imagePullSecrets:
  []
``` 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-02-20 19:51 UTC, monotek reviewed
What's the benefit of adding these labels if they are not used in the Matchlabels?

I would rather replace the old labels but as this would make this a breaking change the major version needs to be updated.

2021-02-27 09:07 UTC, nlamirault commented
@monotek i add the labels to matchLabels et service selector.

2021-06-16 10:20 UTC, nlamirault commented
@monotek any news ?

2021-08-24 16:29 UTC, nlamirault commented
/reopen

2021-08-31 09:02 UTC, nlamirault commented
@monotek do you think we could reopen this PR ?

2021-09-20 13:43 UTC, monotek requested changes
Yes, but it needs changes.

This is not a bugfix rlease but a breaking change, which needs upgrading documentation.

Also please use the helm default for common and selector lables like "helm create" would add them.

2021-09-27 16:15 UTC, monotek requested changes

2021-09-27 16:15 UTC, monotek commented on charts/prometheus-node-exporter/README.md
> +￼Due to a change in DaemonSet labels, the upgrade requires `helm upgrade --force` in order to re-create the daemonset.
Thats not completlay true.
You also can do it like this: https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/README.md#from-chart-versions--500

2021-12-15 18:30 UTC, closed without merging