[prometheus-elasticsearch-exporter] Introduce extraVolume/Mounts
prometheus-community/helm-charts pull request #698
Opened 2021-02-22 16:35 UTC by eyenx

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

#### What this PR does / why we need it:
introduces extraVolume + Mounts if the volume you want to mount is not a secret (ex: csi volumes) for secrets-store implementation.

#### Which issue this PR fixes
n/a

#### Special notes for your reviewer:
n/a

#### Checklist

- [ x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-02-22 21:53 UTC, monotek requested changes

2021-02-22 21:53 UTC, monotek commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> -version: 4.2.0
New feature should raise minor version.

2021-02-23 05:58 UTC, eyenx commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> +version: 4.2.1
```suggestion
version: 4.3.0
```

2021-02-23 06:03 UTC, eyenx commented on charts/prometheus-elasticsearch-exporter/Chart.yaml
> -version: 4.2.0
done.

2021-02-23 12:43 UTC, caarlos0 approved these changes

2021-02-23 16:49 UTC, monotek approved these changes

2021-02-23 16:49 UTC, merged