[prometheus-node-exporter] Ability to provide imagePullSecrets
prometheus-community/helm-charts pull request #708
Opened 2021-02-24 17:32 UTC by julb

#### What this PR does / why we need it:

Ability to parameter the imagePullSecrets for the chart when pulling image from a private registry.
For backwards compat, there is no imagePullSecrets specified.

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-02-25 01:33 UTC, monotek requested changes

2021-02-25 01:33 UTC, monotek commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 1.15.1
New feature should raise minor version.

2021-02-25 08:17 UTC, julb commented on charts/prometheus-node-exporter/Chart.yaml
> +version: 1.15.1
Done.

2021-02-25 08:22 UTC, julb commented
@monotek Thanks for your review. I've done the changes.

2021-02-28 00:04 UTC, monotek submitted a review, later dismissed

2021-04-01 21:49 UTC, monotek commented
@prometheus-community/helm-charts 

Please review / merge :)

2021-04-02 18:42 UTC, bismarck requested changes
You can already set imagePullSecrets in the service account: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/serviceaccount.yaml

2021-04-16 17:23 UTC, closed without merging