[prometheus-nats-exporter] Bump prometheus-nats-expoter app version
prometheus-community/helm-charts pull request #722
Opened 2021-03-02 19:24 UTC by okgolove

Signed-off-by: Mikhail Naletov <okgolove@markeloff.net>

#### What this PR does / why we need it:
Update to the latest nats-exporter version

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-03-02 23:35 UTC, monotek requested changes
Please also raise chart version.

2021-03-03 09:40 UTC, okgolove commented
@monotek oh, forgot to do that. Haven't commited for a while :)

2021-03-03 11:33 UTC, caarlos0 approved these changes

2021-03-05 15:57 UTC, monotek approved these changes

2021-03-05 15:57 UTC, merged