[prometheus] make path.rootfs condition
prometheus-community/helm-charts pull request #737
Opened 2021-03-07 16:17 UTC by radhus

#### What this PR does / why we need it:

Makes it configurable if node-exporter daemonset should mount `/` from host or not. Default to `true` to keep existing default behavior.

As seen in issue #467, it is not always possible to mount / from host in all environments.

#### Which issue this PR fixes

  - fixes #467 (but perhaps needs similar change to the node-exporter chart as well?)

#### Special notes for your reviewer:

> For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@gianrubio , @zanhsieh , @Xtigyro , @monotek , @naseemkullah 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-03-07 23:22 UTC, monotek requested changes

2021-03-07 23:22 UTC, monotek commented on charts/prometheus/Chart.yaml
> +version: 13.4.1
New feature should raise minor version.

2021-03-08 08:26 UTC, radhus commented on charts/prometheus/Chart.yaml
> +version: 13.4.1
Fixed, bumped to `13.5.0`

2021-03-08 08:45 UTC, monotek requested changes
Version needs to be 13.6.0

2021-03-08 16:11 UTC, radhus commented
@monotek bumped it, I'd usually like to rebase the PR but the template says

> When updates to your PR are requested, please add new commits and do not squash the history.

Let me know if I shall proceed and do that or if it can be merged anyway.

2021-03-08 23:50 UTC, monotek submitted a review, later dismissed

2021-03-09 09:26 UTC, zanhsieh approved these changes

2021-03-10 15:12 UTC, radhus commented
Anything else needed to get this merged? 🙂

2021-03-10 15:53 UTC, monotek approved these changes

2021-03-10 15:53 UTC, merged