[kube-prometheus-stack] Exclude default rules from namespace enforcement
prometheus-community/helm-charts pull request #770
Opened 2021-03-17 10:39 UTC by amuraru

When enforcedNamespaceLabel is enabled the default rules installed by the
helm chart also also changed dynamically by the operator at runtime.
This breaks cluster wide recorded rules and alert rules.

This patch introduces a new parameter `prometheusDefaultRulesExcludedFromEnforce`
to list all the default rules that should be excluded from ns enforcement.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-03-17 10:44 UTC, amuraru commented
also see https://github.com/prometheus-operator/prometheus-operator/issues/3919

2021-03-19 07:19 UTC, Xtigyro commented
Hey @amuraru 👋 
Thank you for the contribution - it's appreciated! 🥇 

I'll be having a look at this PR today and hopefully will be merged by Monday.

2021-03-19 13:33 UTC, amuraru commented on charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
> +{{- if .Values.prometheus.prometheusSpec.enforcedNamespaceLabel }}
I moved this here and nest with the `prometheusDefaultRulesExcludedFromEnforce` and `prometheusRulesExcludedFromEnforce` as the latters are not applicable unless `enforcedNamespaceLabel` is set

2021-03-19 19:53 UTC, Xtigyro requested changes
@amuraru Could we please think of a way for automating the maintenance of that explicit list? With this PR if you add a new group of rules - you'll need to add it to one more place.

2021-03-20 00:00 UTC, amuraru commented
> Could we please think of a way for automating the maintenance of that explicit list? With this PR if you add a new group of rules - you'll need to add it to one more place.

thanks for your suggestion @Xtigyro - please check the new version, the patch now generates automatically the rules names dynamically in sync_prometheus_rules.py and stores them as a yaml file where they are dynamically loaded from.
lmk

2021-03-20 17:14 UTC, Xtigyro commented
@amuraru Very nice! And how about naming `files` - `aux`?

2021-03-20 18:40 UTC, amuraru commented
What about `generated` and try to move generated rules file there as well?

2021-03-20 21:40 UTC, amuraru commented
@Xtigyro please check again - I changed the generated yaml file to a helm named template.
I think it looks more compact now

2021-03-20 22:01 UTC, Xtigyro approved these changes

2021-03-20 22:02 UTC, Xtigyro commented
@amuraru Sweet! Many thanks for your excellent work! 💯

2021-03-20 22:03 UTC, merged