[kube-prometheus-stack] Adding support for multi ingress for thanos
prometheus-community/helm-charts pull request #799
Opened 2021-03-29 18:17 UTC by aronymous

sidecar

Signed-off-by: Aaron Russell <aaron@therussells.me>

#### What this PR does / why we need it:
This adds support for multi ingress for the Thanos sidecar similar to multi ingress for Prometheus.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-03-29 18:19 UTC, aronymous commented
@vsliouniaev 
@bismarck
@gianrubio
@gkarthiks
@scottrigby
@Xtigyro

2021-04-26 02:24 UTC, scottrigby commented
@aronymous I'm tempted to recommend Helm's [post rendering](https://helm.sh/docs/topics/advanced/#post-rendering) for such specific yet major changes. Are you aware of this feature?

2021-04-27 19:32 UTC, aronymous commented
> @aronymous I'm tempted to recommend Helm's [post rendering](https://helm.sh/docs/topics/advanced/#post-rendering) for such specific yet major changes. Are you aware of this feature?

@scottrigby I was not aware of this. After looking at it I am feel it is a heavy handed approach for this. 

This feature is already supported in this helm chart with alert manager / Prometheus pods. This is just adding it for Thanos sidecars as well.

2021-05-14 13:39 UTC, aronymous commented
Is there anything blocking this request? its only extending functionality that already exists for prometheus and alertmanager in this helm chart. 

@scottrigby 
@bismarck 
@gianrubio 
@gkarthiks 
@Xtigyro

2021-06-09 19:43 UTC, fktkrt commented
> > @aronymous I'm tempted to recommend Helm's [post rendering](https://helm.sh/docs/topics/advanced/#post-rendering) for such specific yet major changes. Are you aware of this feature?
> 
> @scottrigby I was not aware of this. After looking at it I am feel it is a heavy handed approach for this.
> 
> This feature is already supported in this helm chart with alert manager / Prometheus pods. This is just adding it for Thanos sidecars as well.

Yes, I am also looking forward to using this functionality, looked into it, and post rendering seems to be questionable to me as well for this functionality.

2021-06-10 17:56 UTC, fktkrt commented on charts/kube-prometheus-stack/templates/prometheus/ingressperreplicaThanosSidecar.yaml
> +                  serviceName: {{ include "kube-prometheus-stack.fullname" $ }}-thanos-{{ $i }}
Shouldn't this be `thanos-gateway` instead of `thanos`?

2021-06-10 17:56 UTC, fktkrt commented on charts/kube-prometheus-stack/templates/prometheus/serviceperreplicaThanosSIdecar.yaml
> +{{- if and .Values.prometheus.enabled .Values.prometheus.thanosServicePerReplica.enabled }}
Could you please rename this file to `serviceperreplicaThanosSidecar.yaml`?

2021-06-10 17:56 UTC, fktkrt commented on charts/kube-prometheus-stack/values.yaml
> +      prefix: "prometheus"
Shouldn't this be `thanos` to follow the conventions in the original `values.yaml`?

2021-06-11 18:58 UTC, aronymous commented
@fktkrt  Updated with those changes.

2021-06-20 07:30 UTC, Xtigyro requested changes
Please bump the Minor chart version (instead of the Patch version).

2021-06-21 12:12 UTC, aronymous commented
> Please bump the Minor chart version (instead of the Patch version).

Updated Minor Chart version

2021-06-24 18:23 UTC, fktkrt commented
If anyone comes here in the future please note that you can stack Query instances and this enables you to only worry about a single Query per cluster (Query will discover all your Prometheus replicas locally), and you'd only need to expose a Query instance you'd like to access remotely.

Also, be aware of https://github.com/thanos-io/thanos/issues/977 which is about enabling separate TLS options per store.

2021-07-19 13:51 UTC, aronymous commented
We have decided to do stacked queriers instead of this. I do not need this anymore but will leave it open in case someone else wants it.

2021-09-02 02:42 UTC, closed without merging

2022-01-25 07:10 UTC, mattheews commented
> We have decided to do stacked queriers instead of this. I do not need this anymore but will leave it open in case someone else wants it.

@aronymous Are You managed to configure separated ingress for two thanos-sidecars? Or You configured it different way and achieved the proper configuration of source for thanos-sidecars on thanos-querier?

2022-01-25 15:36 UTC, aronymous commented
We added a thanos-querier to the cluster and just use that as the entry point. and did not setup multiple ingresses for the sidecar.

2022-01-25 17:32 UTC, mattheews commented
> We added a thanos-querier to the cluster and just use that as the entry point. and did not setup multiple ingresses for the sidecar. 

Hi,

Thank you for the answer! Does it mean, within k8s cluster I should implement thanos querier and thanks this my thamos-sidecars will be visible there? Moreover, if I want further to configure such querier on the external thanos instance will it be possible to add that querier into external thanos?

Thanks,
Mathew