[kube-prometheus-stack] add optional kube-state-metrics ServiceMonitor namespace selector
prometheus-community/helm-charts pull request #827
Opened 2021-04-09 22:03 UTC by forestoden

#### What this PR does / why we need it: 

This PR adds an optional namespaceSelector to the `kube-state-metrics` ServiceMonitor. This is useful because if you override `kube-state-metrics.namespaceOverride` to deploy kube-state-metrics elsewhere, the ServiceMonitor that is deployed does not work. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #820 

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-04-11 20:26 UTC, monotek requested changes

2021-04-11 20:26 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 14.6.3
New feature should raise minor version.

2021-04-11 21:30 UTC, forestoden commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 14.6.3
fixed

2021-04-12 21:36 UTC, monotek approved these changes

2021-04-14 18:43 UTC, bismarck approved these changes
lgtm

2021-04-14 18:44 UTC, merged