[kube-prometheus-stack] support enableFeatures API
prometheus-community/helm-charts pull request #828
Opened 2021-04-10 00:29 UTC by tonychoe

#### What this PR does / why we need it:

Supports enableFeatures API of Prometheus Operator

#### Which issue this PR fixes
  - `fixes #823`

#### Special notes for your reviewer:
n/a

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-04-12 18:28 UTC, monotek requested changes

2021-04-12 18:28 UTC, monotek commented on charts/kube-prometheus-stack/Chart.yaml
> +version: 14.6.3
new feature should raise minor version

2021-04-12 20:07 UTC, tonychoe commented
@monotek thanks, I changed the version. Please review and merge.

2021-04-12 22:26 UTC, monotek submitted a review, later dismissed
Approved. 
But i can't merge as i'm not a maintainer of the chart.

2021-04-20 16:34 UTC, bismarck approved these changes
lgtm

2021-04-20 16:34 UTC, merged