[prometheus]enable hostAliases to be defined for alermanager pod
prometheus-community/helm-charts pull request #883
Opened 2021-04-23 07:55 UTC by slavonicsniper

#### What this PR does / why we need it:
so far hostaliases can be defined only in the server section for prometheus pods, this change adds the same for alertmanager pods
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-04-24 04:45 UTC, zanhsieh commented
@slavonicsniper 
Could you bump the chart version to latest please?

2021-04-25 17:46 UTC, monotek submitted a review, later dismissed

2021-05-21 01:35 UTC, zanhsieh commented
@slavonicsniper 
Could you bump the chart version to latest please?

2021-05-28 13:53 UTC, naseemkullah commented on charts/prometheus/templates/alertmanager/deploy.yaml
> +{{ toYaml .Values.alertmanager.hostAliases | indent 8 }}
```suggestion
        {{- toYaml .Values.alertmanager.hostAliases | nindent 8 }}
```

nit

2021-05-28 13:57 UTC, monotek commented
@slavonicsniper 
I've added the chart version in the github frontend and alos added @naseemkullah requested changes.
Unfortunately the dco check fails now.
As i guess i 'cant force push in your branch, could you please rebase und push again?

2021-05-28 13:58 UTC, monotek requested changes
@slavonicsniper
I've added the chart version in the github frontend and alos added @naseemkullah requested changes.
Unfortunately the dco check fails now.
As i guess i 'cant force push in your branch, could you please rebase und push again?

2021-05-28 13:59 UTC, naseemkullah submitted a review, later dismissed

2021-05-30 02:29 UTC, zanhsieh approved these changes

2021-05-30 02:31 UTC, zanhsieh commented
@slavonicsniper 
There are some DCOs you need to sign. See below "Details" next to DCO.

2021-07-13 04:18 UTC, closed without merging