kube-prometheus-stack: add alerts about file descriptor limits
prometheus-community/helm-charts pull request #915
Opened 2021-04-29 14:42 UTC by nerzhul

#### What this PR does / why we need it:

Currently we have no alert triggered if system reach fs.file-max limit

Add 2 new alerts about filesystem descriptors exhaustion.

This alert is useful to track when a node will reach fs.file-max soon

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-04-29 21:21 UTC, bismarck requested changes
@nerzhul See [note](https://github.com/prometheus-community/helm-charts/blob/c5a6be86a3e92cad291b3090adc1ef4971f69355/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml#L1-L5) at the top of the file you edited.

2021-04-30 06:55 UTC, nerzhul commented
@bismarck my bad, didn't saw this header. 
It sounds the node-exporter alerts are not in kubernetes-mixin, then i published the following MR on prometheus-operator: https://github.com/prometheus-operator/kube-prometheus/pull/1122
I hope i'm good now :)

2021-06-05 13:36 UTC, monotek requested changes
Have you seen?

https://github.com/prometheus-community/helm-charts/blob/c5a6be86a3e92cad291b3090adc1ef4971f69355/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml#L2-L4

2021-06-08 09:19 UTC, nerzhul commented
@monotek i close it, as you said the same thing as upper :) and it has been upstreamed

2021-06-08 09:19 UTC, closed without merging