[kube-prometheus-stack] Add instance namespaces arguments for prometheus-operator deployment
prometheus-community/helm-charts pull request #92
Opened 2020-09-13 14:31 UTC by GMartinez-Sisti

#### What this PR does / why we need it:
Allow configuring namespaces where prometheus-operator searches for custom resources to deploy. This allows narrowing the scope of permissions for prometheus-operator service account.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
The flags can be consulted here https://github.com/prometheus-operator/prometheus-operator/blob/master/cmd/operator/main.go#L177.

Original [PR](https://github.com/helm/charts/pull/23667).

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2020-09-14 22:01 UTC, GMartinez-Sisti commented
Fixed conflict.

2020-09-23 22:30 UTC, GMartinez-Sisti commented
Fixed conflict.

2020-09-27 09:29 UTC, gkarthiks reviewed
/lgtm, lets wait for one more approver

2020-10-11 14:31 UTC, monotek requested changes
Please resolve merge conflicts.

2020-10-11 17:15 UTC, GMartinez-Sisti commented
Fixed conflict.

2020-10-11 18:06 UTC, GMartinez-Sisti commented
Fixed conflict.

2020-10-13 17:19 UTC, monotek approved these changes

2020-10-13 17:23 UTC, gkarthiks approved these changes

2020-10-13 17:23 UTC, merged