[prometheus-pushgateway] PriorityClassName for prom-pushgateway
prometheus-community/helm-charts pull request #948
Opened 2021-05-07 15:36 UTC by blame19

Signed-off-by: Matteo Maponi <matteo.maponi@gmail.com>

#### What this PR does / why we need it:
This adds the priorityClassName argument for prometheus-pushgateway.

#### Which issue this PR fixes
  - fixes #947 

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-05-11 08:10 UTC, monotek requested changes

2021-05-11 08:10 UTC, monotek commented on charts/prometheus-pushgateway/Chart.yaml
> +version: 1.9.1
new feature should raise minor version

2021-05-14 09:42 UTC, monotek approved these changes

2021-05-26 11:32 UTC, blame19 commented
@gianrubio Could you review?

2021-05-29 09:13 UTC, monotek commented
@prometheus-community/helm-charts-admins 
please review :)

2021-06-03 08:58 UTC, blame19 commented
@gianrubio @prombot  Could you review?

2021-06-04 00:46 UTC, zanhsieh approved these changes

2021-06-04 00:47 UTC, zanhsieh commented
@cstaud 
Could you review and merge please?

2021-06-06 16:15 UTC, monotek commented
@torstenwalter @scottrigby 
please have a look.

2021-06-10 08:34 UTC, blame19 commented
@torstenwalter @scottrigby @gianrubio 
please have a look.

2021-06-14 08:49 UTC, blame19 commented
@torstenwalter @scottrigby @gianrubio
please have a look.

2021-06-17 07:25 UTC, blame19 commented
@torstenwalter @scottrigby @gianrubio @zanhsieh @monotek @cstaud 
What can I do to get this looked on?

2021-06-17 08:18 UTC, torstenwalter approved these changes

2021-06-17 08:25 UTC, merged

2021-06-17 08:26 UTC, torstenwalter commented
Reviewed and merged as admin in accordance to https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#review-process

Sorry that it took so long.