[prometheus] Updated kube-state-metrics sub-chart to version 3.0.*
prometheus-community/helm-charts pull request #968
Opened 2021-05-12 19:08 UTC by pierluigilenoci

#### What this PR does / why we need it:

Update kube-state-metrics sub-chart to v3.0.*

#### Which issue this PR fixes

None

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-05-13 11:26 UTC, monotek requested changes
I guess just raising the bugfix version of the while introducing a major version change in the dependency is not enough.

This could break things.

The kube-state-metrics changelog states some replaced metrics:
https://github.com/kubernetes/kube-state-metrics/blob/release-2.0/CHANGELOG.md
So at least some grafana charts might not work afterwards.
I'm still on kube-state-metrics v1.9.8 so i can't tell if this is true or not.

@naseemkullah @zanhsieh @gianrubio @Xtigyro 
What do you think?
Should we introduce a version bump to 14.0.0?

2021-05-14 03:10 UTC, zanhsieh commented
Agreed bump to 14.0.0.

2021-05-14 10:40 UTC, pierluigilenoci commented
@monotek @zanhsieh Done. 🚀

2021-05-14 11:17 UTC, monotek requested changes

2021-05-14 11:17 UTC, monotek commented on charts/prometheus/Chart.yaml
>      repository: https://kubernetes.github.io/kube-state-metrics
repository needs to be changed: 
```suggestion
    repository: https://prometheus-community.github.io/helm-charts
```

2021-05-14 13:16 UTC, pierluigilenoci commented
@monotek repo changed. It should now be fine.

2021-05-15 13:47 UTC, monotek approved these changes

2021-05-15 13:47 UTC, merged