[prometheus-blackbox-exporter] - Added option to customize config path by setting it into values file
prometheus-community/helm-charts pull request #980
Opened 2021-05-19 15:33 UTC by cristi-vlad

#### What this PR does / why we need it:

Add possibility to customize config file path

#### Which issue this PR fixes
-

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

2021-05-19 18:32 UTC, desaintmartin requested changes
Thanks! I am curious, what is your use case?

2021-05-19 18:32 UTC, desaintmartin commented on charts/prometheus-blackbox-exporter/values.yaml
> +configPath: {}
```suggestion
# configPath: "/foo/bar"
```

2021-05-19 18:32 UTC, desaintmartin commented on charts/prometheus-blackbox-exporter/Chart.yaml
> +version: 4.11.1
```suggestion
version: 4.12.0
```

2021-05-20 07:12 UTC, cristi-vlad commented
> Thanks! I am curious, what is your use case?

Hello. Thanks for fast update.
Our case is integration with vault & vault-agent-injector.

Thank you,
/Cristi

2021-05-20 07:18 UTC, closed without merging